### ISSUE TITLE
如果右侧的进度条能优化一下就完美了！

### ISSUE THREAD

**Issue by SherlockGougou** [donkingliang/ConsecutiveScroller#1]
现在进度条的进度不准确，希望修复一下！

**Comment by donkingliang** [comment]
多谢你的反馈。发现是滚动范围的计算错误导致的，这个问题会在后续的版本修复，谢谢。

**Comment by SherlockGougou** [comment]
还有一个功能点，悬浮置顶那里，可以加一个属性，设置后不被顶出去。
场景：商品分类tab-商品排序tab。
在手指网上滑动，可以让商品分类tab、商品排序tab都悬浮。

**Comment by donkingliang** [comment]
这个功能可以考虑在以后的版本中加上。

**Comment by donkingliang** [comment]
新版本已添加常驻吸顶的功能：
app:isPermanent="true"
