### ISSUE TITLE
滑动冲突

### ISSUE THREAD

**Issue by wangyuan0217** [donkingliang/ConsecutiveScroller#10]
子View有 banner（youthBanner）的时，banner左右滑动会触发上下拖动，

**Comment by sun804336516** [comment]
需要自己在ConsectiveLayoutScroll中拦截下触摸，如果是上下滑动则拦截

**Comment by sun804336516** [comment]
> 需要自己在ConsectiveLayoutScroll中拦截下触摸，如果是上下滑动则拦截

ConsectiveScrollerLayout
