### ISSUE TITLE
类似那种资讯新闻详情,如果最底部是Recyclerview的评论列表,怎样可以加一条评论后始终滚动到最底部呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#101]
使用RecyclerView的滚动需要当前RecyclerIView可见的时候才可以滚动:     mRecyclerView.scrollToPosition(mDatas.size() - 1); 
如果用这个库自带的ScrollTo该怎么弄呢?

**Comment by donkingliang** [comment]
先调用scrollToChild滑动到底部的Recyclerview，再调用mRecyclerView.scrollToPosition方法滑动到最后的item
