### ISSUE TITLE
一键吸顶

### ISSUE THREAD

**Issue by daiwenbo88** [donkingliang/ConsecutiveScroller#103]
项目比较着急 没时间去看源码 特来问下 一键吸顶 有相关api可调用吗

**Comment by donkingliang** [comment]
一键吸顶？？什么意思。是点击把吸顶view自动滑动到顶部吗？scrollToChild方法可以滑动指定的view到顶部

**Comment by daiwenbo88** [comment]
就是有个类似顶置按钮功能 页面中有个吸顶tabLayout  点击顶置 让tabLayout自动滑动到吸顶位置

**Comment by daiwenbo88** [comment]
目前采用折中办法 一进入页面 去测量tabLayout在屏幕的位置 保存到成员变量  需要顶置时  就调用scrollerLayout.scrollTo(0,tabLayoutHeight)来实现

**Comment by nitaoge** [comment]
`ConsecutiveScrollerLayout`的`scrollToChild(View);`这个方法可以
