### ISSUE TITLE
getOwnScrollY()获取的垂直滑动距离不正确

### ISSUE THREAD

**Issue by nitaoge** [donkingliang/ConsecutiveScroller#105]
根据在readme中
> 通过getOwnScrollY()方法获取ConsecutiveScrollerLayout的垂直滑动距离，View的getScrollY()方法获取的不是ConsecutiveScrollerLayout的整体滑动距离。

但是在`ConsecutiveScrollerLayout.OnScrollChangeListener`的`onScrollChange`方法中执行`getOwnScrollY()`. 从底部快速滑动 fling到顶部, `getOwnScrollY()`拿到值不对, 不是0, 反而`getScrollY()`拿到的是对的.

**Comment by donkingliang** [comment]
多谢反馈，我会在后面的版本修复这个问题。
