### ISSUE TITLE
多层ViewPager嵌套时，下层的吸顶布局会被遮挡

### ISSUE THREAD

**Issue by aleron08** [donkingliang/ConsecutiveScroller#106]
这是我的布局层级
```xml
<SmartRefreshLayout>
    <ConsecutiveScrollerLayout>
        <Banner/>
        <TabLayout 
            app:layout_isSticky="true"/>
        <ConsecutiveViewPager>

            <ConsecutiveScrollerLayout>
                <TabLayout 
                    app:layout_isSticky="true"/>
                <ConsecutiveViewPager>

                    <RecyclerView/>

                </ConsecutiveViewPager>
            </ConsecutiveScrollerLayout>

        </ConsecutiveViewPager>
    </ConsecutiveScrollerLayout>
</SmartRefreshLayout>
```

其中第一个吸顶的TabView显示正常，第二个TabView会被第一个遮挡

**Comment by donkingliang** [comment]
给你的第一个ConsecutiveViewPager设置viewPager.setAdjustHeight(第一个吸顶的TabView的高度);

**Comment by aleron08** [comment]
尝试了这种方案，不过有时整个viewPager会被拖上去，底部留下一个TabView高度的空白

**Comment by donkingliang** [comment]
布局被顶上去，应该是SmartRefreshLayout触发上拉加载吧？只有设置了setAdjustHeight才会这样吗？在什么情况下会出现这种问题？

**Comment by aleron08** [comment]
把SmartRefreshLayout移除后，viewPager依然会被拖上去，即TabView盖在viewPager上面，底部留下一块空白。如果不设置setAdjustHeight，ViewPager底部就不会有空白区域。
第一张图是设置了setAdjustHeight
![image](https://user-images.githubusercontent.com/22996571/88181392-58af5100-cc61-11ea-860a-c649f5cdcc70.png)
第二张图是没设置的
![image](https://user-images.githubusercontent.com/22996571/88181427-67960380-cc61-11ea-8399-461012922435.png)

**Comment by donkingliang** [comment]
能不能加一下我的QQ，把你的demo发给我看一下。1043214265

**Comment by aleron08** [comment]
> 能不能加一下我的QQ，把你的demo发给我看一下。1043214265

已经发送qq好友请求了
