### ISSUE TITLE
请问一下,我这样写的布局,为什么WebView的内容会显示不全呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#108]
1.布局是这样写的:
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white">

    <RelativeLayout
        android:id="@+id/rl_case_detail_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone">

        
        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/cl_case_detail_comment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:padding="12dp">

            <TextView
                android:id="@+id/tv_case_detail_collect"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:drawableTop="@mipmap/collect"
                android:drawablePadding="5dp"
                android:gravity="center"
                android:text="收藏"
                android:textColor="#666666"
                android:textSize="10dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintHorizontal_weight="1"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toLeftOf="@+id/tv_case_detail_like"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/tv_case_detail_like"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:drawableTop="@mipmap/dislike"
                android:drawablePadding="5dp"
                android:gravity="center"
                android:text="0"
                android:textColor="#666666"
                android:textSize="10dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintHorizontal_weight="1"
                app:layout_constraintLeft_toRightOf="@+id/tv_case_detail_collect"
                app:layout_constraintRight_toLeftOf="@+id/tv_case_detail_edit_comment"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/tv_case_detail_edit_comment"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_margin="5dp"
                android:background="@drawable/send_message_shape"
                android:gravity="center"
                android:padding="10dp"
                android:text="写评论"
                android:textColor="#FE7D01"
                android:textSize="14dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintHorizontal_weight="2"
                app:layout_constraintLeft_toRightOf="@+id/tv_case_detail_like"
                app:layout_constraintRight_toLeftOf="@+id/tv_case_detail_offer_consulting"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/tv_case_detail_offer_consulting"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_margin="5dp"
                android:background="@drawable/join_tender_shape"
                android:gravity="center"
                android:padding="10dp"
                android:text="咨询报价"
                android:textColor="@color/white"
                android:textSize="14dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintHorizontal_weight="2"
                app:layout_constraintLeft_toRightOf="@+id/tv_case_detail_edit_comment"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

        </androidx.constraintlayout.widget.ConstraintLayout>

        
        <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
            android:id="@+id/csl_case_detail"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@id/cl_case_detail_comment"
            android:scrollbars="vertical">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp"
                android:orientation="horizontal">

                <TextView
                    android:id="@+id/tv_case_detail_certificate"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@mipmap/certificate_bg"
                    android:drawableLeft="@mipmap/certificate"
                    android:drawablePadding="5dp"
                    android:paddingLeft="10dp"
                    android:text="id"
                    android:textColor="@color/white"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/tv_case_detail_type"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="5dp"
                    android:background="@drawable/orange_shape"
                    android:paddingLeft="5dp"
                    android:paddingRight="5dp"
                    android:text="平台交易案例"
                    android:textColor="#FE7D01"
                    android:textSize="11dp"
                    app:layout_constraintBottom_toBottomOf="@id/tv_case_detail_certificate"
                    app:layout_constraintLeft_toRightOf="@id/tv_case_detail_certificate"
                    app:layout_constraintTop_toTopOf="@id/tv_case_detail_certificate" />

            </LinearLayout>

            <TextView
                android:id="@+id/tv_case_detail_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="12dp"
                android:text="--"
                android:textColor="#333333"
                android:textSize="20dp" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp">

                <ImageView
                    android:id="@+id/iv_case_detail_avatar"
                    android:layout_width="14dp"
                    android:layout_height="14dp"
                    android:src="@mipmap/default_avatar"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/tv_case_detail_enterprise_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="5dp"
                    android:text="--"
                    android:textColor="#666666"
                    android:textSize="14dp"
                    app:layout_constraintBottom_toBottomOf="@id/iv_case_detail_avatar"
                    app:layout_constraintLeft_toRightOf="@id/iv_case_detail_avatar"
                    app:layout_constraintTop_toTopOf="@id/iv_case_detail_avatar" />

            </androidx.constraintlayout.widget.ConstraintLayout>

            <Space
                android:layout_width="match_parent"
                android:layout_height="10dp" />

            
            <WebView
                android:id="@+id/wv_case_detail"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:visibility="gone" />

            <Space
                android:layout_width="match_parent"
                android:layout_height="10dp" />

            <TextView
                android:id="@+id/tv_case_detail_release_date"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp"
                android:layout_marginTop="10dp"
                android:text="--"
                android:textColor="#666666"
                android:textSize="14dp" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/cl_case_detail_comment_position"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <TextView
                    android:id="@+id/tv_case_detail_comment_position"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_margin="16dp"
                    android:text="评论"
                    android:textColor="#444444"
                    android:textSize="17dp"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/tv_case_detail_comment_count"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:layout_marginTop="16dp"
                    android:text="--"
                    android:textColor="#444444"
                    android:textSize="17dp"
                    app:layout_constraintLeft_toRightOf="@id/tv_case_detail_comment_position"
                    app:layout_constraintTop_toTopOf="parent" />

            </androidx.constraintlayout.widget.ConstraintLayout>

            
            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_case_detail_comments"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

    </RelativeLayout>

    <ProgressBar
        android:id="@+id/pb_case_detail_loading"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:indeterminateTint="#FE7D01"
        android:visibility="visible" />

</FrameLayout>

2.类中代码:
 @Override
    protected void initData() {
        String url = getIntent().getStringExtra("url");
        mWebView.loadUrl(url);

        LogUtils.d("1628  "+url);

        WebSettings settings = mWebView.getSettings();
        settings.setJavaScriptEnabled(true);

        //加这个也无效
//        mWebView.setWebChromeClient(new WebChromeClient() {
//            @Override
//            public void onProgressChanged(WebView view, int newProgress) {
//                super.onProgressChanged(view, newProgress);
//                mScrollerLayout.checkLayoutChange();
//            }
//        });

        mWebView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url);
                //返回true
                return true;
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                // 网页加载完成才显示所有内容
                mWebView.setVisibility(View.VISIBLE);
                mIvMore.setImageResource(R.mipmap.horizontal_more);
                mProgressBar.setVisibility(View.GONE);
                mContentLayout.setVisibility(View.VISIBLE);
                int caseId = getIntent().getIntExtra("caseId", -1); //就是example_id
                boolean isCollect = getIntent().getBooleanExtra("isCollect", false);
                CaseLibraryBean.DataBean bean = getIntent().getParcelableExtra("bean");
                int discussNum = bean.getDiscussNum();
                boolean isPraise = bean.isIsPraise();
                int praise_id = bean.getPraise_id();
                mLike.setText(String.valueOf(bean.getPraise_num()));
//                LogUtils.d("1709  "+isPraise);
                if (isPraise) {
                    Drawable drawableTop = getResources().getDrawable(R.mipmap.like);
                    mLike.setCompoundDrawablesWithIntrinsicBounds(null, drawableTop, null, null);
                    mLike.setCompoundDrawablePadding(5);
                }

                if (isCollect) {
                    Drawable drawableTop = getResources().getDrawable(R.mipmap.collected);
                    mCollect.setCompoundDrawablesWithIntrinsicBounds(null, drawableTop, null, null);
                    mCollect.setCompoundDrawablePadding(5);
                    mCollect.setText("已收藏");
                    mCollect.setTextColor(Color.parseColor("#FFCC00"));
                }

                String title = bean.getTitle();
                mTitle.setText(title);
                String hash = bean.getHash();
                if (hash != null && !hash.isEmpty()) {
                    mCertificate.setText(hash.substring(0, 11) + "...");
                } else {
                    mCertificate.setVisibility(View.GONE);
                }

                mType.setVisibility(bean.getProject_id() == 0 ? View.GONE : View.VISIBLE);//0隐藏   1显示
                String user_name = bean.getUser_name();
                mName.setText(user_name);
                Glide.with(CaseDetailActivity.this).load(RequestUrl.IMAGE_URL + bean.getUser_avatar()).
                        placeholder(R.mipmap.default_avatar).error(R.mipmap.default_avatar).
                        apply(RequestOptions.bitmapTransform(new CircleCrop())).into(mAvatar);
                int created_time = bean.getCreated_time();
                String date = DateUtil.timeStamp2Date(String.valueOf(created_time), "yyyy-MM-dd");
                mDate.setText("发布于" + date);

                getCommentList(false);//获取评论数据
            }

            @RequiresApi(api = Build.VERSION_CODES.M)
            @Override
            public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
                super.onReceivedError(view, request, error);
                int errorCode = error.getErrorCode();
                if (errorCode == -2 || errorCode == -10 || errorCode == -6) {
//                    mWebView.setVisibility(View.GONE);
//                    mScrollerLayout.setVisibility(View.GONE);
                    mProgressBar.setVisibility(View.GONE);
                    frameLayout.removeAllViews();
                    View errorView = View.inflate(CaseDetailActivity.this, R.layout.web_error_view, null);
                    frameLayout.addView(errorView);
                }
            }
        });
        LinearLayoutManager manager = new LinearLayoutManager(this);
        manager.setOrientation(LinearLayoutManager.VERTICAL);
        mRecyclerView.setLayoutManager(manager);
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.addChildClickViewIds(R.id.tv_case_detail_comment_like);
        mAdapter.setOnItemChildClickListener(this);
        mAdapter.setOnItemClickListener(this);
    }

**Comment by donkingliang** [comment]
显示不全是webview滑动不到底部吗？还是不能滑动？

**Comment by roybill** [comment]
WebView的内容显示不全,其他布局没有影响,比如webview的下面还有其他的view,其他view可以正常显示

**Comment by donkingliang** [comment]
就是WebView的内容滑不到底部吗？能不能提供一下你的url链接给我测试一下？

**Comment by roybill** [comment]
这是显示有问题的url,作者可以试试: https://devm.lanfanglian.com/case?id=92 , 直接在电脑网页端是可以完全展示的

**Comment by roybill** [comment]
WebView的内容没有显示全

**Comment by SpielbergGao** [comment]
同上遇到了相同的问题，WebView 只展示了一半
