### ISSUE TITLE
关于ConsecutiveScroller的优化建议

### ISSUE THREAD

**Issue by jksld** [donkingliang/ConsecutiveScroller#110]
<com.mzl.sddmall.views.widget.CustomConsecutiveScrollerLayout
            android:id="@+id/scroll_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <com.youth.banner.Banner
                android:id="@+id/banner"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_300"/>

**如上代码将会导致Banner中ViewPager2的响应异常，ViewPager2本该很灵敏**。
经过调试发现，应该是**com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.dispatchTouchEvent(MotionEvent ev)**的**475行**代码**ev.setLocation(ev.getX(), mFixedY)**导致。
**这行代码改变了event的位置**
我通过如下代码，进行了简单的修复：
                              

                                
                           int pointerIndex2 = ev.findPointerIndex(mActivePointerId);
                           View target = getTouchTarget(ScrollUtils.getRawX(this, ev, pointerIndex2),
                                        ScrollUtils.getRawY(this, ev, pointerIndex2));
                                if (target instanceof Banner){

                                }else {
                                    // 如果是横向滑动，设置ev的y坐标始终为开始的坐标，避免子view自己消费了垂直滑动事件。
                                    ev.setLocation(ev.getX(), mFixedY);
                                }
同时希望楼主能够给出更好的解决方案

**Comment by donkingliang** [comment]
ev.setLocation(ev.getX(), mFixedY)这句代码是改变事件的y坐标的，应该是不会影响左右滑动事件的。我这边测试ViewPager2的左右活动还是很灵敏的。

你使用的是那个版本的ConsecutiveScroller代码，你下载最新代码试一下。
