### ISSUE TITLE
recyclerview问题

### ISSUE THREAD

**Issue by pengjunhong** [donkingliang/ConsecutiveScroller#111]
recyclerview使用谷歌的FlexboxLayoutManager，最后一条被隐藏了

**Comment by donkingliang** [comment]
多谢反馈。因为FlexboxLayoutManager布局使用canScrollVertically方法判断滑动到底部会有偏差，导致
ConsecutiveScroller认为recyclerview已经滑到底部了。我后面会针对recyclerview单独实现滑动边界的判断方法，解决这种问题。
