### ISSUE TITLE
通过AddView添加一个RecyclerView的时候，这个RecyclerView显示不全

### ISSUE THREAD

**Issue by devin1014** [donkingliang/ConsecutiveScroller#114]
显示不全的RecyclerView只能显示部分内容，滑动方向是同方向。如果两个RV都写在xml里面，没有问题。

**Comment by donkingliang** [comment]
你是不是add到了ConsecutiveScroller下的子布局，而不是add到ConsecutiveScroller里面去了。

**Comment by devin1014** [comment]
找到问题了。
`<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
    <TextView/>
    <androidx.recyclerview.widget.RecyclerView/>
    <TextView/>
    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#e0e0e0" />
</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>`
view被添加到container中，但是如果被添加的View根节点不是ConsecutiveScrollerLayout的话，这个View中的部分内容显示不全。
