### ISSUE TITLE
如何使吸顶的view可以被后续的控件覆盖，而不是吸顶view悬浮在所有其他非吸顶view上层

### ISSUE THREAD

**Issue by Matchas-xiaobin** [donkingliang/ConsecutiveScroller#115]
想要实现的效果是：

一个图片view在顶部，需要能响应触摸事件，然后要求在顶部不被推上去，但是可以被后续滑动上来的view覆盖，类似电商平台商品详情页顶部那个图片，视频部分。

还有一个效果我觉得也是挺不错的，就是可以设定特定view到达顶部后，继续滑动，但是这个view的滑动速度可以用户自定义，比如到顶部后，继续滑动，其滑动速度为50%。

希望作者能添加一下这个功能，谢谢。

**Comment by donkingliang** [comment]
第一个问题：如果你想吸顶view被后续滑动上来的view覆盖，只要继承ConsecutiveScrollerLayout，在构造方法中设置setChildrenDrawingOrderEnabled(false);就可以了。因为这个方法是protected，所以你要继承才能设置。

第二个问题：考虑到滑动速度减低，会影响到后续的view的滑动速度也要减低，所以这个功能暂时作为备案。后面可能会考虑加上。
谢谢！

**Comment by Matchas-xiaobin** [comment]
setChildrenDrawingOrderEnabled(false);

**Comment by donkingliang** [comment]
这个是全局的，所有吸顶view都生效。如果只是想设置其中一个view生效，就需要修改ConsecutiveScrollerLayout的代码，修改sortViews方法。可以看我这篇文章：https://juejin.im/post/6844904191295504397
