### ISSUE TITLE
 # main(2) java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by inshyma** [donkingliang/ConsecutiveScroller#117]
sdk version: 3.6.2

线上报错:
# main(2)
java.lang.IllegalArgumentException
pointerIndex out of range

1 android.view.MotionEvent.nativeGetAxisValue(Native Method)
--
2 android.view.MotionEvent.getY(MotionEvent.java:2382)
3 consecutivescroller.ConsecutiveScrollerLayout.boolean dispatchTouchEvent(android.view.MotionEvent)

**Comment by hyhyhykw** [comment]
+1

**Comment by qingyunchinese** [comment]
+1

**Comment by donkingliang** [comment]
是在多点触控的时候报的异常吗？能不能发一下完整的log，定位一下是什么情况下，哪一行代码包的错。报错时pointerIndex 是多少？

**Comment by donkingliang** [comment]
已修复
