### ISSUE TITLE
如何禁用ConsecutiveScroller的滑动?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#119]
比如我有一个viewpager,viewpager是嵌套在ConsecutiveScroller内的,里面有4个fragment,fragment内是列表,当我列表为空的时候想要禁止调上下滑动该如何做?

**Comment by donkingliang** [comment]
ConsecutiveScroller没有提供禁止滑动的方法。需要直接继承ConsecutiveScroller，复写事件方法禁止滑动。
