### ISSUE TITLE
不支持SwipeRefreshLayout

### ISSUE THREAD

**Issue by KotlinLan** [donkingliang/ConsecutiveScroller#12]
外层或者内层嵌套ConsecutiveScrollerLayout都无效

**Comment by donkingliang** [comment]
我测试过，SwipeRefreshLayout嵌套ConsecutiveScrollerLayout是可以的，我不知道你那边是怎么写的，为什么不可以。
ConsecutiveScrollerLayout嵌套SwipeRefreshLayout是不行的。因为ConsecutiveScrollerLayout要保证子View的内容跟着整体一起滑动。除非你给SwipeRefreshLayout设置app:layout_isConsecutive="false" app:layout_isNestedScroll="false"，让SwipeRefreshLayout内部自己处理滑动，这样就可以让SwipeRefreshLayout工作了。但是这样滑动SwipeRefreshLayout区域时，ConsecutiveScrollerLayout是不会跟着滑动的，这就是我在文档说的局部滑动的情况。
