### ISSUE TITLE
底部ViewPager中Fragment布局很复杂的问题

### ISSUE THREAD

**Issue by daiwenbo88** [donkingliang/ConsecutiveScroller#120]
当吸顶View后面是一个ViewPager时 其中包含Fragment的布局很复杂时 所给出的那些解决方案不太好使用 不过我更倾向于 可以把 ViewPager的高度在测量时固定死 比如全屏高度减去吸顶View 的高度 就是ViewPager的高度  至于其中Fragment中的View 的滑动事件就全权交给这些View 去处理 其中边界就吸顶view 吸顶状态和非吸顶状态

**Comment by donkingliang** [comment]
你想让ViewPager里fragment自己处理事件，直接设置ViewPager app:layout_isConsecutive="false"就可以了。但是这样它就不能跟其他的View连贯滑动了，需要自己做滑动冲突的处理。
