### ISSUE TITLE
当包含一个Recyclerview

### ISSUE THREAD

**Issue by qiangzengli** [donkingliang/ConsecutiveScroller#121]
包含recyclerview 展示图片的时候 ，当发生复用的时候，有时候会出现 recyclerview  自己滚动的情况

**Comment by donkingliang** [comment]
你说的自己滚动是什么情况。item复用的时候不正是列表在滚动的时候吗？

你说的是item滚动的时候会跳动吗？你的item高度是不是根据图片加载动态变化的，不是固定高度的。如果是item跳动，你可以给RecyclerView设置tag: android:tag="InterceptRequestLayout"试一下。
