### ISSUE TITLE
ViewPager内的Fragment还有ViewPager,然后后面这个ViewPager内的Fragment中的RecyclerView列表数据加载不全该怎么解决呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#123]
1.第一级的布局:
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#F5F5F5">

    <com.donkingliang.consecutivescroller.ConsecutiveViewPager
        android:id="@+id/cvp_home"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

2.第二级的布局 cvp_home(内fragment的布局):
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

  //省略一堆布局...
   <com.donkingliang.consecutivescroller.ConsecutiveViewPager
        android:id="@+id/cvp_service"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@id/rg_service" />

</androidx.constraintlayout.widget.ConstraintLayout>

3.第三级的布局 (cvp_service内fragment的布局):
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_hot_demand"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by donkingliang** [comment]
你的Fragment的根布局是ConstraintLayout吗？你的Fragment是包含在ConsecutiveScrollerLayout的里面的，所以Fragment根布局需要是滑动控件，比如ConsecutiveScrollerLayout或者RecyclerView、NestedScrollView等。这个我在文档中有说明。
如果Fragment的根布局不是滑动布局，那么它只能显示一屏，不能滑动它里面的内容。

**Comment by roybill** [comment]
我把Fragment的根布局改为ConsecutiveScrollerLayout,数据是显示全了,但是现在ViewPager怎么变为不能左右滑动了呢?用的是ConsecutiveViewPager

**Comment by donkingliang** [comment]
是最里面那个ConsecutiveViewPager不能左右滑，还是两个都不能？你左右滑动的时候有没有触发上下滑动的事件？

**Comment by roybill** [comment]
是最里面那个不能左右滑了,外面那个可以正常滑动. 左右滑动的时候上下不会动,然后左右滑动的时候可以滑,但是就是拉不过去.也就是说当我处在第一个Fragment的时候,往左滑动,可以看到第二个Fragment的布局,但是就是选不中第二个Fragment

**Comment by donkingliang** [comment]
你使用的是最新的4.2.0版本吗？这个版本应该不会有垂直滑动的冲突的。你能发一下你的布局和设置ViewPager的代码给我看一下吗？

**Comment by roybill** [comment]
谢谢,已经可以了.之前出问题是因为用的2.x的版本,现在改成最新的4.2.0就好了

**Comment by roybill** [comment]
还有个问题请教一下:最外层是ConsecutiveScrollerLayout,里面ViewPager内的Fragment还有ViewPager,然后后面这个ViewPager内的Fragment中有一个水平的RadioGroup,想要滑动到顶部的时候吸顶,但是我这样写了布局无法吸顶,该怎么解决呢?这是最里面Fragment的布局:
<?xml version="1.0" encoding="utf-8"?>
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:isPermanent="true"
    android:orientation="vertical">

    <Space
        android:layout_width="match_parent"
        android:layout_height="12dp" />

    
    <RadioGroup
        android:id="@+id/rg_service"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="12dp"
        android:layout_marginTop="19dp"
        android:layout_marginRight="12dp"
        app:layout_isSticky="true"
        android:orientation="horizontal"
        app:layout_constraintTop_toTopOf="parent">

        <RadioButton
            android:id="@+id/rb_hot_demand"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:background="@drawable/home_shape"
            android:button="@null"
            android:gravity="center"
            android:padding="10dp"
            android:text="热门需求"
            android:textColor="@drawable/filter_text_selector"
            android:textSize="12dp" />

        <RadioButton
            android:id="@+id/rb_select_service"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8dp"
            android:layout_weight="1"
            android:background="@drawable/home_shape"
            android:button="@null"
            android:gravity="center"
            android:padding="10dp"
            android:text="精选服务"
            android:textColor="@drawable/filter_text_selector"
            android:textSize="12dp" />

        <RadioButton
            android:id="@+id/rb_provider"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8dp"
            android:layout_weight="1"
            android:background="@drawable/home_shape"
            android:button="@null"
            android:gravity="center"
            android:padding="10dp"
            android:text="服务商"
            android:textColor="@drawable/filter_text_selector"
            android:textSize="12dp" />

        <RadioButton
            android:id="@+id/rb_case_library"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8dp"
            android:layout_weight="1"
            android:background="@drawable/home_shape"
            android:button="@null"
            android:gravity="center"
            android:padding="10dp"
            android:text="案例库"
            android:textColor="@drawable/filter_text_selector"
            android:textSize="12dp" />

    </RadioGroup>

    <Space
        android:layout_width="match_parent"
        android:layout_height="8dp" />

    <com.donkingliang.consecutivescroller.ConsecutiveViewPager
        android:id="@+id/cvp_service"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@id/rg_service" />

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
这样写是可以吸顶的。是不是你外层也有吸顶的View，导致你这个吸顶的view被外层的吸顶view覆盖了啊。你试一下设置一下这个ConsecutiveScrollerLayout 的吸顶偏移量scrollerLayout.setStickyOffset(offset)。

**Comment by roybill** [comment]
是外层也有吸顶的View,   setStickyOffset内的值是否可以直接拿高度呢?比如外层吸顶的高度我这样拿int height = tlShow.getHeight(); 然后 scrollerLayout.setStickyOffset( height );

**Comment by donkingliang** [comment]
是的，这个吸顶的偏移量就是你外层吸顶的高度，这样里面的吸顶才不会被重叠挡住。

**Comment by roybill** [comment]
我试了一下,通过setStickyOffset看起来是可以吸顶,但是效果不太好.就是我需要吸顶的地方会被滑上去,然后突然闪动一下才显示出来.有没有办法实现跟外层吸顶一样的自然效果呢?感觉就是依附在上面的那种.

**Comment by donkingliang** [comment]
怎么会闪动一下？你是在吸顶的时候才设置setStickyOffset吗？你应该在开始的时候就设置好setStickyOffset，你的Offset应该是固定的吧，不会变的吧

**Comment by roybill** [comment]
我就是在一开始就设置好offset的,值是通过计算外面那层吸顶的高度设置进去的,也就是setStickyOffset(外层吸顶内容的高度);
还有一个问题:就是使用ConsecutiveViewPager的时候:比如里面有两个Fragment,我在第一个fragment滑动到一半的高度,然后直接滑动到第二个fragment,这个时候第二个fragment的高度也是一半了.也就是该ConsecutiveViewPager内的每一个Fragment只要上下滑动了,其他fragment的高度位置也会跟着变化,这种该怎么解决呢?

**Comment by donkingliang** [comment]
fragment的滑动是不会影响到其他Fragment的，我不知道你是怎么出现这种问题的。我这边重来没有出现过。你能不能弄个有bug的demo给我测试一下。

**Comment by roybill** [comment]
方便给个QQ或其他联系方式吗?我发给你,这里太麻烦了

**Comment by donkingliang** [comment]
1043214265
