### ISSUE TITLE
请教个小问题在Fragment怎么使用ViewPager

### ISSUE THREAD

**Issue by 1825492258** [donkingliang/ConsecutiveScroller#124]
我在Fragment 使用ViewPager然后滑到底部就滑不动了，我应该哪里写的问题
下面是HomeFragment的布局代码
![image](https://user-images.githubusercontent.com/16134482/91551187-5cb74880-e95c-11ea-81a5-a779f75008d4.png)
![image](https://user-images.githubusercontent.com/16134482/91551244-7062af00-e95c-11ea-8af8-52d5869c9447.png)
子Fragment的布局是加了ConsecutiveScrollerLayout

**Comment by donkingliang** [comment]
子Fragment的根布局是ConsecutiveScrollerLayout吗？滑动的布局不能被非滑动的布局包裹。你检查一下你的子Fragment的布局滑不动，是不是嵌套了一层其他布局啊。

**Comment by 1825492258** [comment]
子Fragment的跟布局是ConsecutiveScrollerLayout    HomeFragment的根布局是LineLayout

**Comment by donkingliang** [comment]
子Fragment的布局是怎么样的，能放出来看一下吗？滑动的内容有没有被其他布局嵌套？

**Comment by 1825492258** [comment]
抱歉 是我的问题，HomeFragment 里面有个控件处理有问题
