### ISSUE TITLE
SmartRefreshLayout 相关问题

### ISSUE THREAD

**Issue by jiaoyongzhi** [donkingliang/ConsecutiveScroller#126]
当用SmartRefreshLayout  2.0.1 版本后  设置refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
    @Override
    public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
        // 上拉加载时，保证吸顶头部不被推出屏幕。
        // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
        scrollerLayout.setStickyOffset(offset);
    }
});
之后上拉布局时也会把吸顶View推上去

**Comment by donkingliang** [comment]
SmartRefreshLayout 2.x把核心库和header、footer分离了。你是不是没有引入你要的header、footer，所以没有显示footer，也没有回调监听啊。

**Comment by jiaoyongzhi** [comment]
//核心必须依赖
    implementation 'com.scwang.smart:refresh-layout-kernel:2.0.1'
    //谷歌刷新头
    implementation 'com.scwang.smart:refresh-header-material:2.0.1'
    //经典加载
    implementation 'com.scwang.smart:refresh-footer-classics:2.0.1'

我这么引入的

**Comment by donkingliang** [comment]
你有在Application 或者xml中指定使用的header和footer吗？如果你上拉时只看到空白，没有实现footer，那么就是你没有指定footer。如果footer，你就打印一下onFooterMoving是否回调，如果没有回调，那么就可能是SmartRefreshLayout 的回调有问题了。

**Comment by jiaoyongzhi** [comment]
我知道了 是内容小于一屏幕的时候 上拉 就会把吸顶的布局顶上去

**Comment by donkingliang** [comment]
已修改，你更新一下版本

**Comment by jiaoyongzhi** [comment]
好的 麻烦你了
