### ISSUE TITLE
吸顶布局被遮挡

### ISSUE THREAD

**Issue by breakadmin** [donkingliang/ConsecutiveScroller#127]
当存在CardView时,向上滑动,吸顶布局被遮挡

**Comment by donkingliang** [comment]
因为CardView是有一个elevation的Z轴高度的，所以它会覆盖其他的view，如果你不想它覆盖吸顶view，要么 代码设置cardView.setElevation(0);，要么设置吸顶view的elevation大于cardView的elevation。但是如果cardview的elevation为0，就没有阴影效果；如果吸顶view的elevation大于0，就会有一个阴影的效果。
