### ISSUE TITLE
布局带ViewSwitcher 问题

### ISSUE THREAD

**Issue by jiaoyongzhi** [donkingliang/ConsecutiveScroller#128]
如果其中带ViewSwitcher
轮播的时候  整体布局会往下串

**Comment by donkingliang** [comment]
你是设置动画轮播吗？我测试没有出现这种问题。你能发一下你的布局和ViewSwitcher的设置吗。

**Comment by jiaoyongzhi** [comment]
我是ConsecutiveScrollerLayout 里面的RecyclerView  的item  是ViewSwitcher

**Comment by jiaoyongzhi** [comment]
我将ConsecutiveScrollerLayout 里面的RecyclerView 的item的  ViewSwitcher  换成了      compile 'com.youth.banner:banner:2.1.0'  这个的   垂直轮播    在轮播的时候 也布局往下串  但是 次数比  用ViewSwitcher  的时候少

**Comment by donkingliang** [comment]
我在自己的demo中都试了ViewSwitcher和banner，都没有出现这个问题。发一下你的代码，给我看一下你是怎么设置的吗？或者你下载我github上的代码，在demo中修改，看能不能重现问题。

**Comment by jiaoyongzhi** [comment]
我先看看 改你Demo  我这实现起来复杂 发代码 更麻烦    我还用到vlayout 了

**Comment by jiaoyongzhi** [comment]
应该是阿里出的 vlayout 的 问题
