### ISSUE TITLE
CoordinatorLayout 中使用时 有时候会无法滑动

### ISSUE THREAD

**Issue by hyhyhykw** [donkingliang/ConsecutiveScroller#132]
可能是CoordinatorLayout的问题  更新了一下appcompat包就出现了 androidx.appcompat:appcompat:1.3.0-alpha02

<CoordinatorLayout>
    <AppbarLayout/>
    <SmartRefreshLayout>
        <ConsecutiveScrollerLayout>
            <RecyclerView/>
            <LinearLayout/>
            <LinearLayout/>
            <RecyclerView/>
        </ConsecutiveScrollerLayout>
    </SmartRefreshLayout>
</CoordinatorLayout>

**Comment by hyhyhykw** [comment]
布局是这样
`<CoordinatorLayout>
    <AppbarLayout/>
    <SmartRefreshLayout>
        <ConsecutiveScrollerLayout>
            <RecyclerView/>
            <LinearLayout/>
            <LinearLayout/>
            <RecyclerView/>
        </ConsecutiveScrollerLayout>
    </SmartRefreshLayout>
</CoordinatorLayout>`

**Comment by donkingliang** [comment]
你没有更新appcompat包之前，是没有问题的吗？
另外我用自己的dmeo更新了appcompat:1.3.0-alpha02包，按你写的布局结构，也是正常的，没有出现你说的问题哦。

**Comment by hyhyhykw** [comment]
> 你没有更新appcompat包之前，是没有问题的吗？
> 另外我用自己的dmeo更新了appcompat:1.3.0-alpha02包，按你写的布局结构，也是正常的，没有出现你说的问题哦。

sorry，现在才看到，问题还存在，似乎是RecyclerView发生了嵌套滑动，不知道你的core包是哪个版本的，我更新后core包变成1.5.0-alpha02了，稍后我做一个测试项目看一下

**Comment by donkingliang** [comment]
core包也是1.5.0-alpha02

**Comment by hyhyhykw** [comment]
> core包也是1.5.0-alpha02

我再找找原因，我写了一个测试Demo，也是好的，但App里就会出问题

**Comment by hyhyhykw** [comment]
> core包也是1.5.0-alpha02

发现问题了，startNestedScroll(int axes, int type) 这个方法偶然出现在手抬起的时候触发，并且type变成TYPE_NON_TOUCH，可能是我这个界面滑动事件太多导致的，我现在继承ConsecutiveScrollerLayout 重写这个方法 并且将type强制改为TYPE_TOUCH,问题就解决了

**Comment by hyhyhykw** [comment]
> core包也是1.5.0-alpha02

找到原因了，在嵌套滑动时，startNestedScroll(int axes, int type)多调用了一次，并且type传的值为TYPE_NON_TOUCH，我打印调用信息，发现是740行onTouchEvent里面调用了fling方法，但此时我手没有离开屏幕，我估计是发生了滑动冲突，我自己在找一下

**Comment by hyhyhykw** [comment]
> core包也是1.5.0-alpha02

我仔细看来一下 是stopNestedScroll(int type) 没有使用mChildHelper.stopNestedScroll(type) 而是直接使用的无参数方法,我用反射修改了调用方法,现在已经修复了

**Comment by donkingliang** [comment]
好滴，多谢反馈，我会在后面的版本修复一下。

**Comment by daiwenbo88** [comment]
确实 新版本 发现了某些页面无法滑动  已经回滚回旧版  但是旧版在事件分发那里有些问题

ConsecutiveScrollerLayout.dispatchTouchEvent(SourceFile:36)
--
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3227)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2920)

**Comment by qssq** [comment]
我现在的app某个界面也是这样，一直找不到原因，触摸appbarlayout的内容有时候无法滑动。
