### ISSUE TITLE
如何让已经吸顶的View消费掉滑动事件

### ISSUE THREAD

**Issue by zjns** [donkingliang/ConsecutiveScroller#133]
如何让已经吸顶的View消费掉滑动事件，使用户不能滑动吸顶的View来滑动整个页面，并且脱离吸顶状态后能正常滑动。

**Comment by donkingliang** [comment]
多谢反馈，这个建议我会在下个版本优化。

如果你现在需要实现这个功能，就会比较麻烦，你需要自定义View重写吸顶的view的dispatchTouchEvent方法，然后判断它是吸顶状态是返回false。

**Comment by zjns** [comment]
> 多谢反馈，这个建议我会在下个版本优化。
> 
> 如果你现在需要实现这个功能，就会比较麻烦，你需要自定义View重写吸顶的view的dispatchTouchEvent方法，然后判断它是吸顶状态是返回false。

**Comment by zjns** [comment]
> 多谢反馈，这个建议我会在下个版本优化。
> 
> 如果你现在需要实现这个功能，就会比较麻烦，你需要自定义View重写吸顶的view的dispatchTouchEvent方法，然后判断它是吸顶状态是返回false。

感谢感谢，这个问题也不急，只是这样用户体验可能会好些，我看京东、支付宝类似的页面都是这样子的。还有一点，滑动始终觉得不如RecyclerView流畅，特别是短距离快速滑动时，有时候没有触发fling，就会有粘滞感。所以现在还是用的两个相同的View处理吸顶。
