### ISSUE TITLE
如何判断某个child已经滑出了屏幕或出现在了屏幕中？

### ISSUE THREAD

**Issue by Leelion96** [donkingliang/ConsecutiveScroller#134]
时隔很久回来看，已经1k+star了，更新了好多内容~
想问下大佬，类似【回到顶部】那种floatButton，在顶部某个View被滑上去之后出现，之前用getLocalVisibleRect来实现，那在ConsecutiveScrollerLayout中该怎么实现呢？

**Comment by Leelion96** [comment]
我目前是这么判断的：
```
scrollerLayout.setOnVerticalScrollChangeListener(new OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY, int scrollState) {
                boolean show = mViewTop.getLocalVisibleRect(new Rect());
            }
        });
```
但感觉也太粗暴了·

**Comment by donkingliang** [comment]
view在布局中的区域时view.getTop至view.getTop+view.getHeight。然后你就可以根据布局的mScrollY滑动的距离来判断view是否显示在屏幕中了。
if(scrollerLayout.getScrollY() >= recyclerView1.getTop() && scrollerLayout.getScrollY() < view.getTop() + view.getHeight()){
                    Log.e("eee","true");
} else {
                    Log.e("eee","false");
}

然后你也可以getScrollY()加减一个偏移量来调整判断的显示区域，这样就可以调整有吸顶view的情况了。

**Comment by Leelion96** [comment]
> view在布局中的区域时view.getTop至view.getTop+view.getHeight。然后你就可以根据布局的mScrollY滑动的距离来判断view是否显示在屏幕中了。
> if(scrollerLayout.getScrollY() >= recyclerView1.getTop() && scrollerLayout.getScrollY() < view.getTop() + view.getHeight()){
> Log.e("eee","true");
> } else {
> Log.e("eee","false");
> }
> 
> 然后你也可以getScrollY()加减一个偏移量来调整判断的显示区域，这样就可以调整有吸顶view的情况了。

好的，谢谢，也是一种方案。本来我期待是有个专门的回调的，不过想了下好像意义也不大。我关闭此问题。
