### ISSUE TITLE
如何在ConsecutiveScrollerLayout外部再包裹一个布局

### ISSUE THREAD

**Issue by maiduoduo** [donkingliang/ConsecutiveScroller#138]
如何在ConsecutiveScrollerLayout外部再包裹一个布局？
比如布局一个顶部标题栏或者其他布局，不随全局滚动。

目前给ConsecutiveScrollerLayout布局添加一个根布局会导致吸顶失效。

**Comment by donkingliang** [comment]
在ConsecutiveScrollerLayout外部再包裹一个布局不会让吸顶失效。应该是吸顶的时候，被你顶部的标题栏挡住了，你看不到。
可以scrollerLayout.setStickyOffset(50)设置一个吸顶到顶部的偏移量。

**Comment by maiduoduo** [comment]
> 在ConsecutiveScrollerLayout外部再包裹一个布局不会让吸顶失效。应该是吸顶的时候，被你顶部的标题栏挡住了，你看不到。
> 可以scrollerLayout.setStickyOffset(50)设置一个吸顶到顶部的偏移量。
好的，可能是这个原因，多谢指教
