### ISSUE TITLE
嵌套viewpage使用时fragment的跟布局为ConsecutiveScroller会爆错

### ISSUE THREAD

**Issue by 643063150** [donkingliang/ConsecutiveScroller#139]
嵌套viewpage使用时fragment的跟布局为ConsecutiveScroller会爆错，爆错日志现实强制类型转换错误，viewgrop.layoutparms 不能强制转换为ConsecutiveScroller 的layoutparms，同事说一开始是没问题，输了个觉clean了一下就不行了，经过实验吧跟布局改为linearlayout就不会爆错了

**Comment by donkingliang** [comment]
有布局代码和报错信息吗？

**Comment by 643063150** [comment]
原因找打了，以前提出哦一个bug #96  应该还是这个原因，因为他是clean后引起的，我把版本降级后，自定义viewpage就没问题了，这个冲突一直都找不到 头疼
