### ISSUE TITLE
横向滑动的子控件全部被拦截了？

### ISSUE THREAD

**Issue by Matchas-xiaobin** [donkingliang/ConsecutiveScroller#14]
横向滑动的recyclerView，比如轮播图用rv实现，想要不影响左右滑动怎么做？

**Comment by donkingliang** [comment]
横向滑动本来就不拦截的啊，你看我demo里就有个左右滑动的HorizontalScrollView。recyclerView设置问横向滑动，滑动事件是不会被拦截的，可以滑动。

**Comment by Matchas-xiaobin** [comment]
我已经找到了问题，是我的问题。谢谢。
