### ISSUE TITLE
请问如何支持ViewPager2嵌套?

### ISSUE THREAD

**Issue by luoxiong94** [donkingliang/ConsecutiveScroller#140]
请问如何支持ViewPager2嵌套?

**Comment by donkingliang** [comment]
现在只支持水平滑动的ViewPager2，不支持垂直滑动的ViewPager2，也不支持ViewPager2中的item垂直滑动，因为它的垂直滑动跟ConsecutiveScrollerLayout有冲突。但是如果设置ViewPager2为app:layout_isConsecutive="false"，不跟整体布局一起滑动，则没有这个冲突。
