### ISSUE TITLE
ConsecutiveScrollerLayout 嵌套 ConsecutiveViewPager 然后tabLayout 吸顶 ，viewpage 里的Fragment能分页吗？

### ISSUE THREAD

**Issue by chapliny** [donkingliang/ConsecutiveScroller#142]
如题，viewpage 里的fragment 内容被截取（如RecyclerView 里数据显示不全，recyclerView 也是用ConsecutiveScrollerLayout包裹的，如果加上 SmartRefreshLayout 包裹recyclerView就显示不全了。去了会显示），另外webview 自带的分页好像也失效了(webview也是 viewpage里的一个fragment ，布局是ConsecutiveScrollerLayout 包裹一个webview)，不不知道其他人有没有这个情况.

**Comment by donkingliang** [comment]
我在文档中和demo里都有介绍SmartRefreshLayout的使用，它只能放在最外层，需要自己把加载的事件回调给Fragment。你可以参考一下我的demo

**Comment by ckrgithub** [comment]
https://github.com/ckrgithub/CollapsingRefresh  看看这个能符合不？可能要自己二次开发 @chapliny

**Comment by LxzBUG** [comment]
可以
