### ISSUE TITLE
吸顶部分在往上快速滑动时抖动的很厉害呀

### ISSUE THREAD

**Issue by zt3468574** [donkingliang/ConsecutiveScroller#145]
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/csv"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_below="@+id/tab_layout"
    android:background="@color/adv_bg"
    android:scrollbars="vertical">

    <LinearLayout
        android:id="@+id/ll_top_views"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="50dp"
        android:paddingTop="10dp"
        android:paddingBottom="10dp"
        android:background="#ffffff"
        android:orientation="horizontal">
        <RelativeLayout
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal">
            <ImageView
                android:id="@+id/iv_tab1"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerHorizontal="true"
                android:src="@mipmap/home_tag_hdhx"/>
            <TextView
                android:id="@+id/tv_tab1"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/iv_tab1"
                android:layout_centerHorizontal="true"
                android:text="扫一扫"
                android:textColor="#666666"
                android:textSize="13sp" />
        </RelativeLayout>

        <RelativeLayout
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal">
            <ImageView
                android:id="@+id/iv_tab2"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerHorizontal="true"
                android:src="@mipmap/home_tag_wxhd"/>
            <TextView
                android:id="@+id/tv_tab2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/iv_tab2"
                android:layout_centerHorizontal="true"
                android:text="活动创建"
                android:textColor="#666666"
                android:textSize="13sp" />
        </RelativeLayout>

        <RelativeLayout
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal">
            <ImageView
                android:id="@+id/iv_tab3"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerHorizontal="true"
                android:src="@mipmap/home_tag_fpjd"/>
            <TextView
                android:id="@+id/tv_tab3"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/iv_tab3"
                android:layout_centerHorizontal="true"
                android:text="扶贫优选"
                android:textColor="#666666"
                android:textSize="13sp" />
        </RelativeLayout>

        <RelativeLayout
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal">
            <ImageView
                android:id="@+id/iv_tab4"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerHorizontal="true"
                android:src="@mipmap/home_tag_rwzx"/>
            <TextView
                android:id="@+id/tv_tab4"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/iv_tab4"
                android:layout_centerHorizontal="true"
                android:text="任务中心"
                android:textColor="#666666"
                android:textSize="13sp" />
        </RelativeLayout>
    </LinearLayout>

    <RelativeLayout
        android:id="@+id/rl_tag_ggtg"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:paddingRight="18dp"
        android:paddingLeft="18dp"
        app:layout_isSticky="true"
        android:layout_marginTop="10dp"
        android:background="@color/white"
        android:orientation="horizontal">
        <com.base.app.view.roundview.RoundedImageView
            android:layout_width="4dp"
            android:layout_height="18dp"
            android:layout_centerVertical="true"
            android:scaleType="fitXY"
            app:riv_corner_radius="2dp"
            android:src="@color/c_4a83f0" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginLeft="14dp"
            android:text="广告推广"
            android:textColor="@color/c_4e4e4e"
            android:textStyle="bold"
            android:textSize="16sp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/c_b4b4b4"
            android:textSize="12sp"
            android:text="一站式搞定全网精准投放"
            android:layout_marginTop="18dp"
            android:layout_marginLeft="90dp"/>
    </RelativeLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:background="#ffffff">
        <com.faster.advertiser.ui2.customview.absview.BaseFLayout
            android:id="@+id/bf_ggtg"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:b_layout="@layout/item_main_ad_sc_ld"
            android:background="@mipmap/bg_border"/>
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="90dp"
            android:layout_below="@+id/bf_ggtg"
            android:paddingLeft="7dp"
            android:paddingRight="7dp"
            android:layout_marginBottom="10dp">
            <RelativeLayout
                android:id="@+id/rl_sucai"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginRight="0dp"
                android:background="@mipmap/bg_border">
                <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="10dp"
                    android:src="@mipmap/ic_sucaiku_tag"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="40dp"
                    android:text="图片素材库"
                    android:paddingTop="4dp"
                    android:textSize="11sp"
                    android:textStyle="bold"
                    android:textColor="#4e4e4e"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="60dp"
                    android:text="海量精美图片素材"
                    android:textSize="8.5sp"
                    android:textColor="#888888"/>
            </RelativeLayout>

            <RelativeLayout
                android:id="@+id/rl_luodi"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginRight="0dp"
                android:background="@mipmap/bg_border">
                <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="10dp"
                    android:src="@mipmap/ic_luodi_tag"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="40dp"
                    android:paddingTop="4dp"
                    android:text="72投落地页"
                    android:textSize="11sp"
                    android:textStyle="bold"
                    android:textColor="#4e4e4e"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="60dp"
                    android:text="制作精美投放页面"
                    android:textSize="8.5sp"
                    android:textColor="#888888"/>
            </RelativeLayout>

            <RelativeLayout
                android:id="@+id/rl_person"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginRight="0dp"
                android:background="@mipmap/bg_border">
                <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="10dp"
                    android:src="@mipmap/ic_person_tag"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="40dp"
                    android:paddingTop="4dp"
                    android:text="人群定向"
                    android:textSize="11sp"
                    android:textStyle="bold"
                    android:textColor="#4e4e4e"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="60dp"
                    android:text="人群精准投放"
                    android:textSize="8.5sp"
                    android:textColor="#888888"/>
            </RelativeLayout>

        </LinearLayout>

        
    </RelativeLayout>

    <com.faster.advertiser.ui2.customview.absview.BaseFLayout
        android:id="@+id/bf_banner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        app:b_layout="@layout/item_banner"/>

    <RelativeLayout
        android:id="@+id/rl_tag_mxmt"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginTop="8dp"
        android:paddingRight="18dp"
        android:paddingLeft="18dp"
        app:layout_isSticky="true"
        android:background="@color/white"
        android:orientation="horizontal">
        <com.base.app.view.roundview.RoundedImageView
            android:layout_width="4dp"
            android:layout_height="18dp"
            android:layout_centerVertical="true"
            android:scaleType="fitXY"
            app:riv_corner_radius="2dp"
            android:src="@color/c_4a83f0" />
        <TextView
            android:id="@+id/tv_tag_mt"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginLeft="14dp"
            android:text="明星媒体"
            android:textColor="@color/c_4e4e4e"
            android:textStyle="bold"
            android:textSize="16sp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/c_b4b4b4"
            android:textSize="12sp"
            android:text="媒体流量品质推荐"
            android:paddingLeft="8dp"
            android:paddingTop="18dp"
            android:layout_toRightOf="@+id/tv_tag_mt"/>
        <TextView
            android:id="@+id/tv_more"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="12sp"
            android:layout_alignParentRight="true"
            android:paddingTop="18dp"
            android:paddingLeft="18dp"
            android:textColor="@color/c_4a83f0"
            android:text="更多"/>
    </RelativeLayout>

    <com.zhangtao.base.stateview.LoadingView
        android:id="@+id/lp"
        android:layout_width="match_parent"
        android:layout_height="240dp"
        android:background="@color/white"
        android:clickable="true"
        app:lp_empty="state_layout_empty"
        app:lp_error="state_layout_error"
        app:lp_loading="state_layout_loading">
        <LinearLayout
            android:id="@+id/ll_medias"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"/>
        
    </com.zhangtao.base.stateview.LoadingView>

    <RelativeLayout
        android:id="@+id/rl_tag_hdcj"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:paddingRight="18dp"
        android:paddingLeft="18dp"
        app:layout_isSticky="true"
        android:background="@color/white"
        android:orientation="horizontal">
        <com.base.app.view.roundview.RoundedImageView
            android:layout_width="4dp"
            android:layout_height="18dp"
            android:layout_centerVertical="true"
            android:scaleType="fitXY"
            app:riv_corner_radius="2dp"
            android:src="@color/c_4a83f0" />
        <TextView
            android:id="@+id/tv_tag_wx"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginLeft="14dp"
            android:text="微信活动"
            android:textColor="@color/c_4e4e4e"
            android:textStyle="bold"
            android:textSize="16sp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/c_b4b4b4"
            android:textSize="12sp"
            android:text="线上营销活动快速获客"
            android:paddingTop="18dp"
            android:paddingLeft="8dp"
            android:layout_toRightOf="@+id/tv_tag_wx"/>
    </RelativeLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:paddingBottom="8dp"
        android:background="#ffffff">

        <LinearLayout
            android:layout_weight="2"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="200dp"
            android:orientation="horizontal">
            <LinearLayout
                android:id="@+id/ll_hd_views1"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="10dp"
                android:orientation="vertical"/>
            <LinearLayout
                android:id="@+id/ll_hd_views2"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingRight="10dp"
                android:orientation="vertical"/>
        </LinearLayout>
    </RelativeLayout>

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
你使用的版本是什么，吸顶抖动的问题应该是在4.0.1版本修复了的。

**Comment by zt3468574** [comment]
我用的是4.3.0

**Comment by donkingliang** [comment]
我这边没有重现到问题，不知道是什么原因引起的。你这边可以尝试一下在ConsecutiveScrollerLayout的onLayout方法中打印log，看一下是否是因为在页面滑动的过程中引起onLayout不断回调，所以页面跳动。
如果在布局滑动过程中不断改变view或下级view的布局参数(比如：大小、LayoutParams等)，就有可能因此重走onLayout方法。

**Comment by daiwenbo88** [comment]
开启硬件加速就好了  另外布局层级优化下
