### ISSUE TITLE
设置吸顶的view，view的背景是透明时，内容从view底下滚过

### ISSUE THREAD

**Issue by PeterWu520** [donkingliang/ConsecutiveScroller#148]
设置了一个吸顶的View，view的背景是透明时，滚动时会看到内容从这个view的底下流过（吸顶的View悬浮在内容上面），可以设置内容从这个view的底下淹没过去吗，就是View吸顶时，内容从这个View的底下滑动，比如垂直的LinearLayout，上面是“吸顶”的View, 下面是滚动列表

**Comment by donkingliang** [comment]
吸顶的view是悬浮在顶部的。所以如果吸顶view没有背景，会看到覆盖在下面的view。你可以给吸顶view设置一个背景颜色，这样显示就是正常的。

**Comment by PeterWu520** [comment]
页面背景是图片，吸顶的View是搜索框，如果给吸顶view设置背景，下面的背景图片会遮住一部分，看起来会比较突兀

**Comment by donkingliang** [comment]
吸顶的搜索框还有其他布局吗？，如果吸顶view不是第一个view，那么你可以把吸顶view下面的view放在一个布局里，并且设置这个布局的高度等于scrollerLayout.getHeight() - 吸顶view.getHeight();，这样view吸顶时，就不会覆盖后面的布局。

如果吸顶view是第一个view，这样做会有滑动冲突，你可以在它的前面加一个1px的空白view来解决这个问题。

**Comment by PeterWu520** [comment]
谢谢，我的吸顶view是第一个view，按照你说的方案解决了

**Comment by JokeenZhang** [comment]
能设置吸顶View始终是悬浮的效果吗？现在只能看到在滑动过程中内容View从吸顶View底下滑动

![Snipaste_2023-02-10_10-50-06](https://user-images.githubusercontent.com/33319484/217988138-87f547fd-db5c-4e45-bfb0-98ed906e811f.png)

类似以下这种效果

![Snipaste_2023-02-10_10-52-32](https://user-images.githubusercontent.com/33319484/217988527-9dbcdb01-a57e-4a42-9b27-6ae70b9b52e9.png)
