### ISSUE TITLE
布局中有editText，会把listview顶起！

### ISSUE THREAD

**Issue by zombiu** [donkingliang/ConsecutiveScroller#150]
我的布局类似：
<相对布局>
<ConsecutiveScrollerLayout>
<一系列控件>
<一个ListView>
</ConsecutiveScrollerLayout>
<底部EditView>
</相对布局>

然后我发现在弹出软键盘时，会把listview顶出去，大佬这个该怎么解决！

**Comment by donkingliang** [comment]
弹窗键盘时，会引起页面布局的调整变化的，这是系统行为。你可以尝试一下设置Activity的windowSoftInputMode，选择你想要的调整模式。一般是设置adjustResize或者adjustPan

**Comment by zombiu** [comment]
> 弹窗键盘时，会引起页面布局的调整变化的，这是系统行为。你可以尝试一下设置Activity的windowSoftInputMode，选择你想要的调整模式。一般是设置adjustResize或者adjustPan

大佬，我都试过了，行为都很怪异。可惜了，感觉嵌套滑动时，不是很适合搭配edittext，只能另想他法！
