### ISSUE TITLE
快速滑动时，OnVerticalScrollChangeListener返回的scrollY不准确

### ISSUE THREAD

**Issue by chenli309** [donkingliang/ConsecutiveScroller#151]
**重现条件：**
1、给RecyclerView设置数据时，偶数行设置显示多些字，使RecyclerView的item显示高度不是固定的；
List<String> data = new ArrayList<>();
        for (int i = 0; i < 20; i++) {
            if (i % 2 == 0) {
                data.add("哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈" + (i + 1));
            } else {
                data.add("RecyclerView3-" + (i + 1));
            }
        }
2、xml布局文件如下；
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/scrollerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical">

        <TextView
            android:id="@+id/tvHeader1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="10dp"
            android:text="上面的WebView是我的GitHub地址，如果你觉得我的GitHub对你有帮助，请给我点个Star。"
            android:textColor="@android:color/black"
            android:textSize="18sp" />

        <WebView
            android:id="@+id/webView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="10dp"
            android:text="推荐"
            android:textColor="@android:color/black"
            android:textSize="18sp" />

        
        <Space
            android:layout_width="0dp"
            android:layout_height="10dp" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView3"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never"
            android:scrollbars="none" />
    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
**WebView加载的H5内容少一些，差不多一屏的高度。**

满足上述条件后，上下快速滑动，打印日志如下：
onScrollChange scrollY = 4281 oldScrollY = 4592 OwnScrollY = 4281 scrollState = 2
onScrollChange scrollY = 3972 oldScrollY = 4281 OwnScrollY = 3972 scrollState = 2
onScrollChange scrollY = 3682 oldScrollY = 3972 OwnScrollY = 3682 scrollState = 2
onScrollChange scrollY = 3376 oldScrollY = 3682 OwnScrollY = 3376 scrollState = 2
onScrollChange scrollY = 3072 oldScrollY = 3376 OwnScrollY = 3072 scrollState = 2
onScrollChange scrollY = 2789 oldScrollY = 3072 OwnScrollY = 2789 scrollState = 2
onScrollChange scrollY = 2491 oldScrollY = 2789 OwnScrollY = 2491 scrollState = 2
onScrollChange scrollY = 2195 oldScrollY = 2491 OwnScrollY = 2195 scrollState = 2
onScrollChange scrollY = 1903 oldScrollY = 2195 OwnScrollY = 1903 scrollState = 2
onScrollChange scrollY = 1632 oldScrollY = 1903 OwnScrollY = 1632 scrollState = 2
onScrollChange scrollY = 1346 oldScrollY = 1632 OwnScrollY = 1346 scrollState = 2
onScrollChange scrollY = 1066 oldScrollY = 1346 OwnScrollY = 1066 scrollState = 2
onScrollChange scrollY = 804 oldScrollY = 1066 OwnScrollY = 804 scrollState = 2
onScrollChange scrollY = 530 oldScrollY = 804 OwnScrollY = 530 scrollState = 2
onScrollChange scrollY = 261 oldScrollY = 530 OwnScrollY = 261 scrollState = 2
onScrollChange scrollY = 93 oldScrollY = 261 OwnScrollY = 93 scrollState = 2
onScrollChange scrollY = 93 oldScrollY = 93 OwnScrollY = 93 scrollState = 0
惯性滚动到页面顶部时，返回的scrollY=93，而不是=0。

**Comment by donkingliang** [comment]
你使用的那个什么版本？

**Comment by chenli309** [comment]
Androidx的4.3.0版本
