### ISSUE TITLE
viewgroup +吸顶 tablayout + recyclerview + 吸顶 tab + viewpager(recyclerview)滑动卡顿不流畅

### ISSUE THREAD

**Issue by junfenggithub** [donkingliang/ConsecutiveScroller#153]
外层ConsecutiveScrollerLayout 嵌套 viewgroup +吸顶 tablayout + recyclerview + 吸顶 tab + ConsecutiveViewPager(fragment ->recyclerview)，fragment 内列表滑动卡顿，而且越滑越严重

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout 在多层嵌套下，滑动的体验确实不如recyclerview，但是不会引起明显的卡顿。如果卡顿明显，一般是布局复杂或者item复用是执行的操作太多引起的，另外如果item的高度不是一样高的，在item复用时也可能影响滑动。你可以尝试减少布局的嵌套，检查recyclerview的item布局和onBindViewHolder是否复杂。
