### ISSUE TITLE
ConsecutiveScroller嵌套两个RecyclerView

### ISSUE THREAD

**Issue by GaoDongDaDa** [donkingliang/ConsecutiveScroller#155]
ConsecutiveScroller嵌套了两个RecyclerView，顶部RecyclerView内容不变，底部RecyclerView使用BaseRecyclerViewAdapterHelper这个库上拉加载新数据，再次回到页面顶部后，整个页面就滑不动了。

**Comment by donkingliang** [comment]
我这边测试，没有出现这种情况。你能提供一下你的布局和代码吗？

**Comment by donkingliang** [comment]
你的RecyclerView有没有写死了高度啊
