### ISSUE TITLE
ConsecutiveScroller嵌套两个RecyclerView

### ISSUE THREAD

**Issue by GaoDongDaDa** [donkingliang/ConsecutiveScroller#156]
不好意思，最近两天有事没有工作，现在我给你发一下代码
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#ffffff"
    android:orientation="vertical"
    tools:context=".ConsecutiveScroll.ConsecutiveScrollActivity">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="44dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:text="文章详情"
            android:textColor="#333333"
            android:textSize="18dp"
            android:textStyle="bold" />

    </RelativeLayout>

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:padding="10dp"
            android:text="标题"
            android:textColor="#333333"
            android:textSize="15dp" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#ffffff"
            android:gravity="center"
            android:padding="10dp"
            android:text="用户信息"
            android:textColor="#333333"
            android:textSize="15dp"
            app:layout_isSticky="true" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:padding="10dp"
            android:text="发布时间"
            android:textColor="#333333"
            android:textSize="15dp" />

        <Space
            android:layout_width="match_parent"
            android:layout_height="20dp" />

        <View
            android:layout_width="match_parent"
            android:layout_height="10dp"
            android:background="#eeeeee" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="评论10"
            android:textColor="#333333"
            android:textSize="16dp"
            app:layout_isSticky="true" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_comment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

</LinearLayout>`
**Activity代码：**
`package com.example.demo2.ConsecutiveScroll;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.example.demo2.R;

import java.util.ArrayList;
import java.util.List;

public class ConsecutiveScrollActivity extends AppCompatActivity {

    private RecyclerView rvContent, rvComment;
    private ConsecuTiveAdapter consecuTiveAdapter;
    private List<String> list;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_consecutive_scroll);

        rvContent = findViewById(R.id.rv_content);
        rvComment = findViewById(R.id.rv_comment);

        list = new ArrayList<>();
        for (int i = 0; i < 20; i++) {
            list.add("");
        }

        rvContent.setHasFixedSize(true);
        rvContent.setNestedScrollingEnabled(false);
        ConsecuTiveAdapter adapter = new ConsecuTiveAdapter(R.layout.article_text_item, list);
        consecuTiveAdapter = new ConsecuTiveAdapter(R.layout.article_text_item, list);

        rvContent.setLayoutManager(new LinearLayoutManager(this));
        rvContent.setAdapter(adapter);

        rvComment.setLayoutManager(new LinearLayoutManager(this));
        rvComment.setAdapter(consecuTiveAdapter);

        setListener();
    }

    private void setListener() {
        consecuTiveAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                for (int i = 0; i < 5; i++) {
                    list.add("" + i);
                }
                consecuTiveAdapter.loadMoreEnd();
            }
        }, rvComment);
    }
}
`
麻烦看一下，谢谢

**Comment by donkingliang** [comment]
你两个列表都用了同一个list吗？这样list改变了，上面的recyclerview却没有刷新页面，是会有问题的哦。

**Comment by GaoDongDaDa** [comment]
哈哈不好意思，主要是为了方便给你看代码，就只用了一个list

**Comment by donkingliang** [comment]
你原本的adapter是怎么设置的？

**Comment by GaoDongDaDa** [comment]
emmmm，不好意思打扰了大佬，[笑哭]，我在原来代码里也是用的一个list哈哈哈，浪费你时间了，不好意思，我这就关闭
