### ISSUE TITLE
一个layout超过一屏，会自动被裁剪掉超出屏幕的部分

### ISSUE THREAD

**Issue by Jibinghao** [donkingliang/ConsecutiveScroller#157]

**Comment by donkingliang** [comment]
如果一个普通的view(非滑动控件)的高度会超出一屏，它需要用滑动控件如ScrollView包裹起来。因为ConsecutiveScrollerLayout是协调子view的滑动的，它本身不是一个想ScrollView无限高的layout。所以他的子view高度是不能大于它本身的高度的。

**Comment by Jibinghao** [comment]
好的 谢谢您
