### ISSUE TITLE
将recyclerview的高度设为wrap_content，加载图片后无法显示

### ISSUE THREAD

**Issue by CNCoderX** [donkingliang/ConsecutiveScroller#158]
recyclerview高度设置成wrap_content，item为ImageView，ImageView高度为wrap_content。使用picasso加载网络图片无法显示。recyclerview的高度一直为0

recyclerview是ConsecutiveScrollerLayout的直接子控件

**Comment by donkingliang** [comment]
不使用ConsecutiveScroller嵌套的时候是正常的吗？ConsecutiveScroller不应该会影响到recyclerview的item绘制的。

**Comment by CNCoderX** [comment]
> 不使用ConsecutiveScroller嵌套的时候是正常的吗？ConsecutiveScroller不应该会影响到recyclerview的item绘制的。

不使用ConsecutiveScroller可以正常显示，在adapter里指定imageview高度也可以正常显示。第一次使用picasso请求图片高度算不出来，第二次请求就有了，因为有图片缓存了。图片加载完成后调用ConsecutiveScroller的requestLayout方法也算不出来

**Comment by donkingliang** [comment]
我尝试不使用ConsecutiveScroller，当recyclerview和imageview的高度都是wrap_content的时候，第一次加载也是不显示的，第二次加载就可以正常显示了。我想是因为picasso在第二次加载的时候算不出图片的高度，所以高度为0了。

**Comment by CNCoderX** [comment]
> 我尝试不使用ConsecutiveScroller，当recyclerview和imageview的高度都是wrap_content的时候，第一次加载也是不显示的，第二次加载就可以正常显示了。我想是因为picasso在第二次加载的时候算不出图片的高度，所以高度为0了。

谢谢，这个问题已经解决了。给RecyclerView设置一个最小高度就行了
