### ISSUE TITLE
嵌套BaseRecyclerViewAdapterHelper出现问题

### ISSUE THREAD

**Issue by pengjunhong** [donkingliang/ConsecutiveScroller#159]
布局：
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/scrollerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none">

<androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rl_all_channel"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="@dimen/dp_30"
            android:paddingRight="@dimen/dp_8"/>

 </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

1.RecyclerView的adapter使用BaseRecyclerViewAdapterHelper（2.9.50）的拖拽view。2.setLayoutManager(new GridLayoutManager(this, 4, RecyclerView.VERTICAL, false));3.首次水平拖拽之后就不能往上拖拽了。（但是首次如果是往上拖拽则没有问题）。4.去掉ConsecutiveScrollerLayout 就都正常了

**Comment by donkingliang** [comment]
这是因为ConsecutiveScrollerLayout为了解决水平滑动和和垂直滑动的冲突，在判断view水平滑动时，禁止了垂直滑动事件。但是这个限制对isConsecutive=false的子view无效。你可以在开始拖拽的时候设置RecyclerView的isConsecutive=false，停止拖拽时恢复isConsecutive=true。这样就可以了。

ConsecutiveScrollerLayout.LayoutParams lp = (ConsecutiveScrollerLayout.LayoutParams)recyclerView.getLayoutParams();
 lp.isConsecutive = false;
 recyclerView.setLayoutParams(lp);

记得停止拖拽时一定要恢复isConsecutive=true，因为ConsecutiveScrollerLayout不会处理isConsecutive=false的子view的滑动冲突，所以恢复，后续的滑动不能联动。

**Comment by pengjunhong** [comment]
好的，感谢回复。我过会测试下。
