### ISSUE TITLE
局部滑动，能否动态设置？

### ISSUE THREAD

**Issue by DonYeung** [donkingliang/ConsecutiveScroller#161]
CnnsecutiveScroller，嵌套多个view,最后一个是frameLayout，动态加载了fragment，想要实现，fragment 滑动到顶部的时候才开始放开局部滑动的限制，
![image](https://user-images.githubusercontent.com/16217712/98466007-c9c24680-2207-11eb-879e-29e10769c8a6.png)

**Comment by donkingliang** [comment]
可以的。
ConsecutiveScrollerLayout.LayoutParams lp = (ConsecutiveScrollerLayout.LayoutParams) view.getLayoutParams();
        lp.isConsecutive = false;
        view.setLayoutParams(lp);

**Comment by DonYeung** [comment]
> 可以的。
> ConsecutiveScrollerLayout.LayoutParams lp = (ConsecutiveScrollerLayout.LayoutParams) view.getLayoutParams();
> lp.isConsecutive = false;
> view.setLayoutParams(lp);

通过这种方法，可以动态控制isConsecutive ，不过如果在fragment 中里面有下拉刷新，无法响应。（在使用方法中，你提及到，这里的Fragment是ConsecutiveScrollerLayout的一部分，不能在ConsecutiveScrollerLayout内部使用SmartRefreshLayout），而且fragment是一个sdk里面的页面布局，无法对其进行修改设置layout_isConsecutive="false"，这种情况是否就只能是寻求它法了？

**Comment by donkingliang** [comment]
你可以对承载Fragment的容器设置layout_isConsecutive="false"，这样Fragment就是局部滑动的，这个时候Fragment里面就可以使用SmartRefreshLayout了。
