### ISSUE TITLE
onVerticalScrollChangeListener回调问题

### ISSUE THREAD

**Issue by wp529** [donkingliang/ConsecutiveScroller#165]
作者大大你好，使用你的库很久了，库很好用，今天遇到一个滑动回调问题

##### 问题背景:

​	在滑动布局中有一个视频控件,当视频控件滑出屏幕暂停，滑进屏幕继续播放。在滑动回调中判断代码如下

```
//滑动回调中
if (scrollY > videoView.bottom) {
    //视频看不见了并且视频还在播放,暂停
    if (videoView.isPlaying()) {
        videoView.stopPlay()
    }
} else {
    //能看见视频了
    if (!videoView.pauseByUser && !videoView.isPlaying()) {
        //不是被用户主动暂停且没处于播放中,继续播放
        videoView.reStartPlay()
    }
}
//activity中
override fun onPause() {
   super.onPause()
   videoView.stopPlay()
}
```

在滑动过程中没有任何问题，但是当把滑动布局**滑到顶部**然后将app退出后台，视频不能暂停播放。

查看滑动布局的源码发现

1. 滑动到顶部时执行的scrollDown方法，mOwnScrollY += scrollOffset会导致mOwnScrollY变为负数
2. 在activity回调onPause后，会触发ConsecutiveScrollerLayout的onLayout方法，此方法中依序调用到checkTargetsScroll方法，但由于上一点会导致oldScrollY=mOwnScrollY为负数，并且重新计算滑动布局的mOwnScrollY后为0，两个值不等，回调滑动监听。
3. 上两点又是在onPause后执行最终导致我在onPause中stop，后又在滑动回调中reStartPlay出现视频还在播放的bug

不知作者大大觉得这种情况是否需要ConsecutiveScrollerLayout处理？从ConsecutiveScrollerLayout角度我想到有两种方式来解决

1. scrollDown中不允许mOwnScrollY为负值，小于0全视为0
2. 在onLayout依序回调的checkTargetsScroll方法中isLayoutChange参数不写死为true，继续使用onLayout回传的changed参数

如作者大大有更好的方式还望一起交流，谢谢！

**Comment by wp529** [comment]
原来并不是onPause会触发onLayout，而是我onPause时暂停视频导致布局改变而触发的onLayout，继而触发滑动回调。但这种情况我没法规避呀。。。

**Comment by wp529** [comment]
不从库的层面也有办法可以处理这个问题，但还是算野路子，我认为这种情况不应该触发滑动回调，因为本身也没滑动产生

**Comment by donkingliang** [comment]
好的，多谢反馈，我会在后面想办法避免一下因为onLayout触发的不必要滑动回调。

**Comment by donkingliang** [comment]
我看了代码，这个问题在4.3.0以后就应该是修复了。你使用的是旧版本吧
