### ISSUE TITLE
升级到4.4.0版本后的新问题

### ISSUE THREAD

**Issue by wp529** [donkingliang/ConsecutiveScroller#166]
​	上次提了onVerticalScrollChangeListener异常回调的问题，作者大大回复在新版本已修复，原来是4.0.0版本，今天升级4.4.0后发现异常回调问题已修复，但又遇到个新问题。

##### 问题背景

​	在ConsecutiveScrollerLayout最底部有一个RecyclerView，此RecyclerView一开始是隐藏状态，使用了BRVAH的加载更多。我会设置一个空adapter以使用BRVAH的加载更多功能，由于一开始是隐藏状态，所以RV的onBindViewHolder也不会被调用，就不会触发加载更多。升级4.4.0版本后在其他无修改的情况下发现onBindViewHolder被调用了，就导致一进入页面就会回调RV的加载更多，此为异常。由于特殊业务功能原因，我不期望RV隐藏状态下设置空的adapter会触发RV的onBindViewHolder

##### 源码追溯

​	对ConsecutiveScrollerLayout源码查看后发现，在ConsecutiveScrollerLayout的onLayout调用链中会调到scrollChild()方法，此方法里会强制调用scrolledView.scrollBy(0, y)方法，RV被调用此方法后就会触发onBindViewHolder，导致我这里加载更多被触发。所以想请问作者大大调用scrolledView.scrollBy(0, y)的用意，以及可否在调用前判断此scrolledView是否visibility == VISIBLE？

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout的滑动事件是通过scrolledView.scrollBy(0, y)来分发给子view的。onLayout时，布局的位置可能发生了变化，所以我在checkTargetsScroll方法中对所有子view检查一遍位置状态，确保显示正常，所以调用到scrolledView.scrollBy(0, y)。

不过我在checkTargetsScroll没有对GONE的子view进行过滤，这个问题我后面的版本会修复一下。

你设置了空adapter是什么意思。如果你的RV的adapter是null或者getItemCount == 0，应该是不会触发scrollBy(0, y)的。

**Comment by wp529** [comment]
空adapter的意思是只初始化了adapter，里面没有填充数据，然后给BRVAH设置了一个setLoadMoreView，加载更多其内部实现是使用多类型布局实现的，就会导致getItemCount = 1而不是0

**Comment by donkingliang** [comment]
你能在RV隐藏的时候，先不设置adapter吗，这样就不会有这个问题了。

**Comment by wp529** [comment]
可以的 在显示的时候才设置adapter 我这个是根据滑动监听来控制显示隐藏了 我设置adapter后再滑动至RV不可见 设置为GONE后若产生布局改变 也还是会回调onBindViewHolder 会出有问题吗？

**Comment by wp529** [comment]
主要是这块要做曝光 由于历史原因是通过监听View的onVisibilityChanged和onWindowVisibilityChanged方法来实现的 使用ConsecutiveScrollerLayout在滑动到RV不可见时若不隐藏RV的话 前几个 item不会回调这两个方法 所以才在滑动中控制显示隐藏。。。

**Comment by donkingliang** [comment]
你也可以自定义RV，实现IConsecutiveScroller接口，getCurrentScrollerView返回this，getScrolledViews返回null。这样onLayout的是就不会检查它的位置，也就不会调用它的scrollBy(0, y)了。

**Comment by wp529** [comment]
这样的话那你原来做的那些检查一遍位置状态对这个RV就不生效了 没问题吗？

**Comment by donkingliang** [comment]
检查位置是为了防止布局变化导致的布局显示断层，不过这些情况一般很少发生，所以不检查也是没有问题的。一般是WebView和ViewPager会出现这种问题，所以需要检查。

**Comment by wp529** [comment]
噢噢 好的 tks 感谢大佬解惑
