### ISSUE TITLE
RecyclerView 有没有类似viewPager.setAdjustHeight

### ISSUE THREAD

**Issue by jiaoyongzhi** [donkingliang/ConsecutiveScroller#167]
viewPager.setAdjustHeight(tabLayout.getHeight());

**Comment by donkingliang** [comment]
没有，但是你可以自己给RecyclerView setLayoutParams改变它的高度，效果是一样的。

**Comment by jiaoyongzhi** [comment]
> 没有，但是你可以自己给RecyclerView setLayoutParams更改它的高度，效果是一样的。

意思是我动态监听RecyclerView 的前一个吸顶控件 如果吸顶了 动态给RecyclerView setLayoutParams 是吧？

**Comment by donkingliang** [comment]
不需要监听吸顶，只要你知道RecyclerView 的前一个吸顶控件的高度，就可以提前设置好RecyclerView 的高度，不需要动态变化。

**Comment by jiaoyongzhi** [comment]
> 不需要监听吸顶，只要你知道RecyclerView的前一个吸顶控件的高度，就可以提前设置好RecyclerView的高度，不需要动态变化。

我设置了 RecyclerView.setLayoutParams   的 setMargins 距离顶部高度 但是 这样 还是不行

**Comment by jiaoyongzhi** [comment]
> > 不需要监听吸顶，只要你知道RecyclerView的前一个吸顶控件的高度，就可以提前设置好RecyclerView的高度，不需要动态变化。
> 
> 我设置了RecyclerView.setLayoutParams的setMargins距离顶部高度但是这样还是不行

我按照你ViewPager.setAdjustHeight  的那个类  我给写复制代码写了个RecyclerView的 哈哈

**Comment by jiaoyongzhi** [comment]
> 不需要监听吸顶，只要你知道RecyclerView 的前一个吸顶控件的高度，就可以提前设置好RecyclerView 的高度，不需要动态变化。

以失败告终..

**Comment by donkingliang** [comment]
设置高度，不是设置margin，ConsecutiveScrollerLayout的子view不支持上下margin的

**Comment by donkingliang** [comment]
你要设置的是RecyclerView的高度

**Comment by jiaoyongzhi** [comment]
> 你要设置的是RecyclerView的高度

大佬怎么设置 教我下 有点懵

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout.LayoutParams lp = (ConsecutiveScrollerLayout.LayoutParams)recyclerView.getLayoutParams();
lp.height = scrollerLayout.getHeight() - 吸顶view的高度；
recyclerView.setLayoutParams(lp);

**Comment by jiaoyongzhi** [comment]
> ConsecutiveScrollerLayout.LayoutParams lp = (ConsecutiveScrollerLayout.LayoutParams)recyclerView.getLayoutParams();
> lp.height = scrollerLayout.getHeight() - 吸顶view的高度；
> recyclerView.setLayoutParams(lp);

我是 tablayout 吸顶了  然后viewpager  里面的fragment  也有个布局吸顶了    按照这个设置完 确实 有setAdjustHeight 的效果  但是  fragment的 RecyclerView       继续加载更多 是没问题      往回拉的时候 滑动有问题了

**Comment by donkingliang** [comment]
你的RecyclerView 前面是不是只有吸顶的view，如果是，那么你在吸顶view的前面再放一个1px的view试一下。
或者lp.height = scrollerLayout.getHeight() - 吸顶view的高度 - 1px；

**Comment by jiaoyongzhi** [comment]
> 你的RecyclerView 前面是不是只有吸顶的view，如果是，那么你在吸顶view的前面再放一个1px的view试一下。
> 或者lp.height = scrollerLayout.getHeight() - 吸顶view的高度 - 1px；

我是在更改 RecyclerView 数据后 调用你scrollerLayout.scrollToChildWithOffset 方法了 这样就好了   达到了 我想要的结果了
