### ISSUE TITLE
TabLayou（吸顶）+ViewPager，滑动问题

### ISSUE THREAD

**Issue by android-xiao-jun** [donkingliang/ConsecutiveScroller#17]
viewpager里面 fragment中 recycleview，，第一条和上面吸顶会有问题，能优化一下吗

**Comment by donkingliang** [comment]
你好。由于ConsecutiveScroller处理的是它的直接子view的滑动，而viewpager嵌套recycleview时滑动的是里面的recycleview，所以对于这种情况支持不太好。我后面会专门对viewpager等滑动下一级view的布局做一个统一的支持方案。谢谢！

**Comment by Matchas-xiaobin** [comment]
我也遇上这个问题了，我fork了一下代码修改了下，已经搞定了这个问题了。我的思路是给这个viewpager加个属性，然后在onlayout里把这个viewpager的高度减少一个tablayout的高度就可以了。期待作者的统一支持方案。

**Comment by donkingliang** [comment]
新版本提供了对滑动子view下级view的支持接口。并在demo中添加了viewpager嵌套recycleview的处理例子。
