### ISSUE TITLE
ConsecutiveScrollerLayout is slow when i use it with two recyclerviews

### ISSUE THREAD

**Issue by yorondahacker** [donkingliang/ConsecutiveScroller#171]
Hi
this is really a great lib 
but i think it's using too much CPU and when i scroll it's really laggy (choppy)

i'm using a horizontal recyclerview above the vertical recyclerview

this is my layout...

`
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
   >

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_isConsecutive = "false">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/home_doctors_recyclerview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"

            />
    </LinearLayout>

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/home_recyclerview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"

                />

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>`

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout并没有使用太多的cpu，但是ConsecutiveScrollerLayout会代理转发子view的滑动事件，所以他的滑动效果与单纯的RecyclerView有差别，这并不会明显影响滑动流畅性。

不过如果你的RecyclerView Item的高度是不确定的，而是在显示是会变化的(比如使用高度不确定的ImageView)则可能会影响滑动效果。另外你也可以从布局复杂度、内存使用等方面着手优化。
