### ISSUE TITLE
能否设置自动滑动到ConsecutiveScrollerLayout中某个view或者某个item？

### ISSUE THREAD

**Issue by zombiu** [donkingliang/ConsecutiveScroller#173]
大佬，应该怎么做？

**Comment by donkingliang** [comment]
// 滑动到指定view的位置，可以设置一个位置偏移量
public void scrollToChild(View view);
public void scrollToChildWithOffset(View view, int offset);
public void smoothScrollToChild(View view);
public void smoothScrollToChildWithOffset(View view, int offset);

**Comment by zombiu** [comment]
谢谢大佬，我试试！
