### ISSUE TITLE
SmartRefreshLayout和ConsecutiveScrollerLayout嵌套瀑布流滑动问题

### ISSUE THREAD

**Issue by x4niko** [donkingliang/ConsecutiveScroller#175]
`<com.scwang.smart.refresh.layout.SmartRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlEnableAutoLoadMore="true">

        <com.tvbc.maiduidui.view.refresh.MddRefreshHeader
            android:id="@+id/refresh_header_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

        <com.tvbc.maiduidui.common.view.consecutivescroller.ConsecutiveScrollerLayout
            android:id="@+id/consecutive_scroller_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:scrollbars="none"
            android:background="@color/white">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recyclerview"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:overScrollMode="never"
                android:scrollbars="none"/>

            <FrameLayout
                android:id="@+id/tab_container_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:visibility="gone"
                tools:visibility="visible"
                app:layout_isSticky="true">
                <View
                    android:layout_width="match_parent"
                    android:layout_height="41dp"
                    android:background="@color/white"/>
                <com.tvbc.maiduidui.common.view.tablayout.SlidingTabLayout
                    android:id="@+id/sliding_tab_layout"
                    android:layout_width="match_parent"
                    android:layout_height="71dp"/>
            </FrameLayout>

            <com.tvbc.maiduidui.common.view.consecutivescroller.ConsecutiveViewPager
                android:id="@+id/viewpager"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:visibility="gone"
                tools:visibility="visible"/>

        </com.tvbc.maiduidui.common.view.consecutivescroller.ConsecutiveScrollerLayout>

        <com.scwang.smart.refresh.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
    </com.scwang.smart.refresh.layout.SmartRefreshLayout>`

你好，我按上面那种布局，如果ConsecutiveViewPager中的Fragment是瀑布流的话，外层上拉加载更多后，瀑布流最后一个Item会显示不全，请问要怎么解决呢，谢谢～

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout是使用的那个版本？

**Comment by donkingliang** [comment]
如果你使用的是4.2.0或者之前的版本，那么你更新一下代码试一下。

**Comment by hongqinghe** [comment]
我也遇到了这个问题，使用的是最新的版本
