### ISSUE TITLE
自动吸顶

### ISSUE THREAD

**Issue by zly-20000310** [donkingliang/ConsecutiveScroller#176]
有没有什么办法能让某一个view自动滑动顶部然后吸顶

**Comment by donkingliang** [comment]
吧view设置成可吸顶，调用scrollToChild、smoothScrollToChild方法自动滑动到顶部。

**Comment by zly-20000310** [comment]
好的，谢谢


来自 meizu 17 Pro

-------- 原始邮件 --------
发件人：donkingliang <notifications@github.com>
时间：2021年2月1日 11:28
收件人：donkingliang/ConsecutiveScroller <ConsecutiveScroller@noreply.github.com>
抄送：zly-20000310 <1228912998@qq.com>,Author <author@noreply.github.com>
主题：Re: [donkingliang/ConsecutiveScroller] 自动吸顶 (#176)
