### ISSUE TITLE
Failed to resolve: com.github.donkingliang:ConsecutiveScroller:4.4.0

### ISSUE THREAD

**Issue by lz233** [donkingliang/ConsecutiveScroller#177]
按照步骤，无法添加依赖。
![image](https://user-images.githubusercontent.com/32504382/107194421-fbc38e80-6a2a-11eb-884c-b824bf5cbc86.png)

**Comment by ktoy1943** [comment]
![image](https://user-images.githubusercontent.com/6385632/112119152-111a0400-8bf8-11eb-8649-20507206fbc6.png)
检查下配置 有没有加上
