### ISSUE TITLE
在小分辨率手机上显示不完整

### ISSUE THREAD

**Issue by Moredistant** [donkingliang/ConsecutiveScroller#178]
![IMG_20210213_152934](https://user-images.githubusercontent.com/18004892/107844761-3b1a2280-6e11-11eb-958a-2b1ffce390d0.jpg)
![Screenshot_20210213-152753_2](https://user-images.githubusercontent.com/18004892/107844762-3ce3e600-6e11-11eb-9240-ce3613b9a4dc.png)

图1手机分辨率为1920x1080
图2分辨率为2560x1312
布局上方是webview 下方是recyclerview 这两个都显示正常。就中间这个在低分辨率机上显示不正常
何解？

**Comment by donkingliang** [comment]
你截图的部分是webview还是recyclerview？如果你截图的部分是普通的控件，不是滑动控件，那么他的高度超过一屏，需要用ScrollView包裹一下。

**Comment by Moredistant** [comment]
是recyclerview

**Comment by donkingliang** [comment]
你使用的是最新版本的ConsecutiveScroller吗？

**Comment by Moredistant** [comment]
是的，最新版

**Comment by donkingliang** [comment]
你这个是RecyclerView滑不到底，还是RecyclerView只显示一屏？另外你可是尝试在RV外层嵌套一层ScrollView试一下。

如果不行，请提供一下你的布局和代码给我看一下。

**Comment by Moredistant** [comment]
抱歉，这么久才回复(不想动)。经过我刚刚仔细测试，发现是我把RecyclerView嵌套到LinearLayout引起的。作为直接子view没有这个问题

**Comment by Moredistant** [comment]
另外我还想问下，就是第一次进入有ConsecutiveScroller的activity，会有很明显的卡顿，这个问题有优化方案吗

**Comment by Moredistant** [comment]
作者不用回了，卡顿问题我也不太确定是哪的问题
