### ISSUE TITLE
RecyclerView 展示不全

### ISSUE THREAD

**Issue by Nstd** [donkingliang/ConsecutiveScroller#179]
![image](https://user-images.githubusercontent.com/3004225/109122945-427feb00-7784-11eb-88e9-64285742384f.png)
ConsecutiveScroller的第一个直接子view是一个LinearLayout（L1）
它有两个子view：
第一个子view也是LinearLayout（LL2）大概占3/4屏高度
第二个子view是RecyclerView（R2），RecyclerView有很多item，设置了`layout_heigth='wrap_content`，希望它能全展示出来
LL2 + R2的高度超出了屏幕高度，实际效果，R2无法展示全，且不能滑动。

**Comment by donkingliang** [comment]
RecyclerView等滑动的View,必须是ConsecutiveScroller的直接子view，否则不能滑动。

**Comment by donkingliang** [comment]
触发写死view的高度，否则view的高度是不会超过父布局的，你的RecyclerView最多只能占满LinearLayout剩余的空间吗，不能超出它。

你这样的布局，应该在LinearLayout外面嵌套一个ScrollView，ScrollView能让它的子view撑到最大。

**Comment by Nstd** [comment]
> 触发写死view的高度，否则view的高度是不会超过父布局的，你的RecyclerView最多只能占满LinearLayout剩余的空间吗，不能超出它。
> 
> 你这样的布局，应该在LinearLayout外面嵌套一个ScrollView，ScrollView能让它的子view撑到最大。

LinearLayout1外面再套一个ScrollView？

**Comment by donkingliang** [comment]
> > 触发写死view的高度，否则view的高度是不会超过父布局的，你的RecyclerView最多只能占满LinearLayout剩余的空间吗，不能超出它。
> > 你这样的布局，应该在LinearLayout外面嵌套一个ScrollView，ScrollView能让它的子view撑到最大。
> 
> LinearLayout1外面再套一个ScrollView？

对，套一个NestedScrollView，但这只适用于RV的item比较少的时候如果RV的item多于一屏，可能会有滑动冲突问题。

**Comment by Nstd** [comment]
> > > 触发写死view的高度，否则view的高度是不会超过父布局的，你的RecyclerView最多只能占满LinearLayout剩余的空间吗，不能超出它。
> > > 你这样的布局，应该在LinearLayout外面嵌套一个ScrollView，ScrollView能让它的子view撑到最大。
> > 
> > 
> > LinearLayout1外面再套一个ScrollView？
> 
> 对，套一个NestedScrollView，但这只适用于RV的item比较少的时候如果RV的item多于一屏，可能会有滑动冲突问题。

那也不是完全展示RV吧？只是让内嵌的RV能够滑动。但是如果需要对外层的LinearLayout1进行截图，RV就截不全了。

**Comment by donkingliang** [comment]
如果你说的截图是获取View的DrawingCache，我这个方法是可以的。如果是屏幕截图，无论如何都只能截取到屏幕内的内容。

**Comment by Nstd** [comment]
> 如果你说的截图是获取View的DrawingCache，我这个方法是可以的。如果是屏幕截图，无论如何都只能截取到屏幕内的内容。

嗯，暂时先用其他库解决了，等有空再试试这个，谢谢回复
