### ISSUE TITLE
拦截了横向滑动

### ISSUE THREAD

**Issue by w296365959** [donkingliang/ConsecutiveScroller#18]
竖直RecyclerView的item 横向滑动事件被拦截了，仿QQItem删除;
即该控件内放入2个竖直的RecyclerView ,竖直方向滑动没有问题，横向的滑动时间接收不到，无法做到item删除了

**Comment by donkingliang** [comment]
你好，现在ConsecutiveScroller对于竖直滑动的子View只分发了竖直滑动的事件。我会在后面的版本中对竖直和横向做分别处理，让竖直滑动的View也能处理横向事件。谢谢反馈。

**Comment by donkingliang** [comment]
已解决。
