### ISSUE TITLE
子布局无法滚动

### ISSUE THREAD

**Issue by cs9420** [donkingliang/ConsecutiveScroller#180]
父布局这种结构
`<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

            <androidx.constraintlayout.widget.ConstraintLayout
                    android:id="@+id/rootContent"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">
                    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
                                android:layout_width="match_parent"
                                android:layout_height="match_parent"
                           <com.google.android.material.tabs.TabLayout
                                    android:id="@+id/tab_layout"
                                    android:layout_width="match_parent"
                                    android:layout_height="@dimen/dp_40"
                             <com.donkingliang.consecutivescroller.ConsecutiveViewPager2
                                    android:id="@+id/view_pager"
                                    android:layout_width="match_parent"
                                    android:layout_height="match_parent"/>`

viewpager2里的子View只有一个RecyclerView，子View 无法滚动 没有指定高度 给RecycleView加了ConsecutiveScrollerLayout包裹也不行 求大神指教

**Comment by donkingliang** [comment]
给我看一下你设置viewpager2的代码和fragment的布局、代码

**Comment by cs9420** [comment]
viewPage2 的代码
`
private fun setViewPager() {

        binding.viewPager.offscreenPageLimit = viewModel.tabTitleList.size

        viewModel.mFragmentList.add(BehaviorRecordFragment())
        //viewModel.mFragmentList.add(LabelFragment())
        viewModel.mFragmentList.add(DistributionInfoFragment(viewModel.mId))
        //viewModel.mFragmentList.add(ReserveInfoFragment())
        binding.viewPager.adapter = object : FragmentStateAdapter(this) {
            override fun getItemCount(): Int = viewModel.tabTitleList.size

            override fun createFragment(position: Int): Fragment = viewModel.mFragmentList[position]
        }

        TabLayoutMediator(binding.tabLayout, binding.viewPager.viewPager2) { tab, position ->
            tab.text = viewModel.tabTitleList[position]
        }.attach()
    }
`

fragment的布局

`
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rvList"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:itemBinding="@{BehaviorRecordViewModel.itemBinding}"
            app:items="@{BehaviorRecordViewModel.items}"
            app:layoutManager="@{LayoutManagers.linear()}"/>

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

`

**Comment by cs9420** [comment]
会是可能使用RxFragment的问题吗？

**Comment by donkingliang** [comment]
代码和布局没有什么问题。你试一下断点调试一下ConsecutiveViewPager2中的getCurrentScrollerView方法，看一下返回的scrollerView是哪个对象。正常是返回fragment的根布局。

**Comment by cs9420** [comment]
返回的是framLayout 不是滚动的view 这会事哪里出问题了呢

**Comment by cs9420** [comment]
问题找到了，我的Fragment基类封装了一个LoadingHelper，返回的是这个LoadingHelper的framLayout，非常感谢你的库和耐心的解答。
