### ISSUE TITLE
webview+recyclerview结合使用问题

### ISSUE THREAD

**Issue by insen-ok** [donkingliang/ConsecutiveScroller#184]
1.会出现 recyclerview 断层，这个问题 能修改吗

**Comment by insen-ok** [comment]
1.就是有时候 recyclerview 向上滑动时候，webview 不会顶上去，只有当recyclerview滑动到底部时候才会顶上去

**Comment by donkingliang** [comment]
如果是在WebView加载的过程中滑动页面，出现断层，你可以设置：

**Comment by donkingliang** [comment]
webView.setWebChromeClient(new WebChromeClient() {
            @Override
            public void onProgressChanged(WebView view, int newProgress) {
                super.onProgressChanged(view, newProgress);
                scrollerLayout.checkLayoutChange();
            }
        });

**Comment by donkingliang** [comment]
另外，你可以下载我的代码，把demo中的webview url换成你的，看是否能重现你说的问题。
