### ISSUE TITLE
recyclview显示不全的问题

### ISSUE THREAD

**Issue by billdizl** [donkingliang/ConsecutiveScroller#185]
我目前遇到两个问题
1.viewview与recyclyview结合产生recyclview显示不全的问题(RecyclerView设置wrap_content显示不全,设置match_parent显示全但是如果数据过少时充不满屏幕有空隙)
2. ConsecutiveScroller嵌套LinearLayout,LinearLayout有recyclyview,显示不全的问题
第一个问题布局代码如下:
<LinearLayout
             
                android:layout_width="match_parent"
                android:layout_height="match_parent" >
<ConsecutiveScrollerLayout
  android:layout_width="match_parent"
  android:layout_height="match_parent">
<WebView
                android:id="@+id/webView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvRecommandCaseView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp"
                android:layout_marginRight="12dp" />
</ConsecutiveScrollerLayout>
</LinearLayout>
第二个问题布局代码如下:
<ConsecutiveScrollerLayout
  android:layout_width="match_parent"
  android:layout_height="match_parent">
<LinearLayout
             
                android:layout_width="match_parent"
                android:layout_height="match_parent" 
app:layout_isConsecutive="false"/>

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvRecommandCaseView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="12dp"
                android:layout_marginRight="12dp" />
</ConsecutiveScrollerLayout>

大佬 麻烦帮忙看下 如何解决

**Comment by donkingliang** [comment]
1、RecyclerView需要是ConsecutiveScrollerLayout的直接子view，如果嵌套了其他布局层级，会显示不全。
2、app:layout_isConsecutive属性只能用在ConsecutiveScrollerLayout的直接子view，且设置了app:layout_isConsecutive="false"的view不跟ConsecutiveScrollerLayout的整体布局一起滑动。

**Comment by donkingliang** [comment]
1、RecyclerView需要是ConsecutiveScrollerLayout的直接子view，如果嵌套了其他布局层级，会显示不全。
2、app:layout_isConsecutive属性只能用在ConsecutiveScrollerLayout的直接子view，且设置了app:layout_isConsecutive="false"的view不跟ConsecutiveScrollerLayout的整体布局一起滑动。
