### ISSUE TITLE
Recyvlview显示不全的问题

### ISSUE THREAD

**Issue by billdizl** [donkingliang/ConsecutiveScroller#186]
我目前遇到两个问题
1.viewview与recyclyview结合产生recyclview显示不全的问题(RecyclerView设置wrap_content显示不全,设置match_parent显示全但是如果数据过少时充不满屏幕有空隙)
2. ConsecutiveScroller嵌套LinearLayout,LinearLayout有recyclyview,显示不全的问题
第一个问题布局代码如下:
<?xml version="1.0" encoding="utf-8"?>
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/scrollerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="500dp"
        android:padding="10dp"
        android:text="上面的WebView是我的GitHub地址，如果你觉得我的GitHub对你有帮助，请给我点个Star。"
        android:textColor="@android:color/black"
        android:textSize="18sp" />
    <WebView
        android:id="@+id/webView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rvRecommandCaseView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp" />

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

第二个问题布局代码如下:
<?xml version="1.0" encoding="utf-8"?>

<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/scrollerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">

    <TextView
        android:id="@+id/tvTest"
        android:layout_width="match_parent"
        android:layout_height="500dp"
        android:padding="10dp"
        android:text="上面的WebView是我的GitHub地址，如果你觉得我的GitHub对你有帮助，请给我点个Star。"
        android:textColor="@android:color/black"
        android:textSize="18sp" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:layout_isConsecutive="false">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rvRecommandCaseView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="12dp"
            android:layout_marginRight="12dp" />
    </LinearLayout>
</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

大佬 麻烦帮忙看下 如何解决

**Comment by billdizl** [comment]
1、RecyclerView需要是ConsecutiveScrollerLayout的直接子view，如果嵌套了其他布局层级，会显示不全。
 如果嵌套了其他布局层级,显示不全没有办法解决吗?
2.ConsecutiveScrollerLayout  子类 中有一个webview 以及RecyclerView,为什么RecyclerView必须设置成match_parent才能显示,不然一点都不显示呢?

**Comment by donkingliang** [comment]
问题1，请看文档中的[滑动子view的下级view](https://github.com/donkingliang/ConsecutiveScroller#%E6%BB%91%E5%8A%A8%E5%AD%90view%E7%9A%84%E4%B8%8B%E7%BA%A7view)

问题2，我的demo中就包含webview和RecyclerView，并没有遇到你说的问题。你可以用我的demo试一下，如果在demo中也有问题，提供一下代码给我测试一下。

**Comment by billdizl** [comment]
你好 出现情况的demo 已发送过去,
1.嵌套webview recycleriew产生的问题重点的是因为我采用的瀑布流引发的,
因为设置了staggeredGridLayoutManager.setGapStrategy(StaggeredGridLayoutManager.GAP_HANDLING_NONE);
是为了防止布局错乱来设置的,但是有什么好的解决办法吗?
2. 我用文档中的滑动子view的下级view,去操作了,但是子view recyclyview仍旧没有办法滑动,项目中也是tablayout+viewpager2实现的,效果是 当fragment中的第二个头不显示时  tablayout上面的才可以跟随着recyclerView1滑动,当第二个头显示时只有recyclerView1才可以滑动






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donkingliang/ConsecutiveScroller"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [donkingliang/ConsecutiveScroller] Recyvlview显示不全的问题 (#186)





 
问题1，请看文档中的滑动子view的下级view
 
问题2，我的demo中就包含webview和RecyclerView，并没有遇到你说的问题。你可以用我的demo试一下，如果在demo中也有问题，提供一下代码给我测试一下。

**Comment by donkingliang** [comment]
> 你好 出现情况的demo 已发送过去, 1.嵌套webview recycleriew产生的问题重点的是因为我采用的瀑布流引发的, 因为设置了staggeredGridLayoutManager.setGapStrategy(StaggeredGridLayoutManager.GAP_HANDLING_NONE); 是为了防止布局错乱来设置的,但是有什么好的解决办法吗? 2. 我用文档中的滑动子view的下级view,去操作了,但是子view recyclyview仍旧没有办法滑动,项目中也是tablayout+viewpager2实现的,效果是 当fragment中的第二个头不显示时 tablayout上面的才可以跟随着recyclerView1滑动,当第二个头显示时只有recyclerView1才可以滑动
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "donkingliang/ConsecutiveScroller" ***@***.***&gt;; 发送时间:&nbsp;2021年4月8日(星期四) 下午3:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [donkingliang/ConsecutiveScroller] Recyvlview显示不全的问题 (#186) 问题1，请看文档中的滑动子view的下级view 问题2，我的demo中就包含webview和RecyclerView，并没有遇到你说的问题。你可以用我的demo试一下，如果在demo中也有问题，提供一下代码给我测试一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

？？？？ 你的demo发到了那里？我没有收到。你发我邮箱吧。1043214265@qq.com
