### ISSUE TITLE
webView 是动态 addView 在 RelativeLayout 上的，实现 IConsecutiveScroller 会报错 webView 未初始化

### ISSUE THREAD

**Issue by kezhian** [donkingliang/ConsecutiveScroller#188]
webView 是动态 addView 在 RelativeLayout 上的，实现 IConsecutiveScroller 会报错 webView 未初始化

**Comment by donkingliang** [comment]
请提供一下log和代码

**Comment by appdev** [comment]
同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动

**Comment by donkingliang** [comment]
> 同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动

文档中对X5webview的使用有说明。https://github.com/donkingliang/ConsecutiveScroller#%E4%BD%BF%E7%94%A8%E8%85%BE%E8%AE%AFx5%E7%9A%84webview

**Comment by donkingliang** [comment]
> 同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动

另外，也有可能是网页视频，所以无法滑动。
https://github.com/donkingliang/ConsecutiveScroller/issues/109

**Comment by appdev** [comment]
> > 同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动
> 
> 文档中对X5webview的使用有说明。https://github.com/donkingliang/ConsecutiveScroller#%E4%BD%BF%E7%94%A8%E8%85%BE%E8%AE%AFx5%E7%9A%84webview

就是按照文档的方式实现了 IConsecutiveScroller 接口，但是对于动态 add 的还是不行。但是对于直接在 xml 中定义的 webview 有效

**Comment by donkingliang** [comment]
> > > 同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动
> > 
> > 
> > 文档中对X5webview的使用有说明。https://github.com/donkingliang/ConsecutiveScroller#%E4%BD%BF%E7%94%A8%E8%85%BE%E8%AE%AFx5%E7%9A%84webview
> 
> 就是按照文档的方式实现了 IConsecutiveScroller 接口，但是对于动态 add 的还是不行。但是对于直接在 xml 中定义的 webview 有效

你是不是add到ConsecutiveScrollerLayout的子view下面了？要add给ConsecutiveScrollerLayout，不能add到它的下级view。

**Comment by appdev** [comment]
哦。是的，我是add到子view了。我明天在试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 晚上6:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [donkingliang/ConsecutiveScroller] webView 是动态 addView 在 RelativeLayout 上的，实现 IConsecutiveScroller 会报错 webView 未初始化 (#188)




    
同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动
  
文档中对X5webview的使用有说明。https://github.com/donkingliang/ConsecutiveScroller#%E4%BD%BF%E7%94%A8%E8%85%BE%E8%AE%AFx5%E7%9A%84webview
  
就是按照文档的方式实现了 IConsecutiveScroller 接口，但是对于动态 add 的还是不行。但是对于直接在 xml 中定义的 webview 有效
  
你是不是add到ConsecutiveScrollerLayout的子view下面了？要add给ConsecutiveScrollerLayout，不能add到它的下级view。

**Comment by appdev** [comment]
> > > > 同样，动态 addView 的 腾讯 X5webview。实现了接口IConsecutiveScroller。但是也只能显示一屏幕的内容，剩下的划不动
> > > 
> > > 
> > > 文档中对X5webview的使用有说明。https://github.com/donkingliang/ConsecutiveScroller#%E4%BD%BF%E7%94%A8%E8%85%BE%E8%AE%AFx5%E7%9A%84webview
> > 
> > 
> > 就是按照文档的方式实现了 IConsecutiveScroller 接口，但是对于动态 add 的还是不行。但是对于直接在 xml 中定义的 webview 有效
> 
> 你是不是add到ConsecutiveScrollerLayout的子view下面了？要add给ConsecutiveScrollerLayout，不能add到它的下级view。

今天试了一下，果然直接 add 到 ConsecutiveScrollerLayout 下是可以的。感谢！！问题解决了
