### ISSUE TITLE
不兼容AppBarLayout中snap设置

### ISSUE THREAD

**Issue by shi1315235** [donkingliang/ConsecutiveScroller#189]
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:contentScrim="@color/colorPrimary"
            app:layout_scrollFlags="scroll|exitUntilCollapsed|snap"
            app:statusBarScrim="@color/colorPrimary">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:background="@android:color/white"
                android:gravity="center"
                android:text="text1"
                app:layout_collapseMode="parallax" />

            <androidx.appcompat.widget.Toolbar
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_collapseMode="pin">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="AppBarLayout" />
            </androidx.appcompat.widget.Toolbar>
        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by donkingliang** [comment]
我用你的这个布局测试是可以的。你使用的是我最新版本吗？遇到的问题是什么？你可以用我的demo，套用你的这个布局试一下。

**Comment by shi1315235** [comment]
多试几次，折叠到一半停止滑动会有几率停止半途，不会自动滚动到靠近的边缘。

**Comment by donkingliang** [comment]
问题是因为ConsecutiveScrollerLayout fling结束后，没有调用stopNestedScroll，所以CoordinatorLayout没有收到滑动结束的事件。这个问题我会在后面的版本修复。现在一个补救的方法是，监听ConsecutiveScrollerLayout滑动，当滑动结束后，调一下stopNestedScroll方法。
```
    scrollerLayout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
        @Override
        public void onScrollChange(View v, int scrollY, int oldScrollY, int scrollState) {
            if (scrollState == ConsecutiveScrollerLayout.SCROLL_STATE_IDLE){
                scrollerLayout.stopNestedScroll(ViewCompat.TYPE_NON_TOUCH);
            }
        }
    });
```
