### ISSUE TITLE
ConsecutiveScrollerLayout 嵌套 WebView 滑动卡顿

### ISSUE THREAD

**Issue by l-w-h** [donkingliang/ConsecutiveScroller#190]
这是滑动时的GPU渲染分析
![807762135863d2dc5bb6e85d02d993b](https://user-images.githubusercontent.com/27988380/115813292-7e060100-a425-11eb-9216-c16273ae871d.jpg)

**Comment by l-w-h** [comment]
html的样式为：
body{
margin:0px; 
padding:0px;  
}
img {
margin:0px;
padding:0px;
width:100%;
height:auto;
}

**Comment by donkingliang** [comment]
如果是因为ConsecutiveScrollerLayout代理WebView滑动事件引起了卡顿，你可以尝试一下不是要ConsecutiveScrollerLayout或者在WebView外层嵌套一层ScrollView看一下效果。

另外从你提供的GPU渲染分析图看，应该是绘制耗时过长。你的页面和WebView是否过于复杂或者图片较多，加载大图片等

**Comment by l-w-h** [comment]
就是因为用ScrollView显示会有问题才用ConsecutiveScrollerLayout的
另外如果不用ScrollView和ConsecutiveScrollerLayout嵌套，是没有问题的

**Comment by donkingliang** [comment]
如果你没有使用吸顶功能和不需要overScroll效果，那么你可以给ConsecutiveScrollerLayout设置setWillNotDraw(true); 这个属性会对绘制有一些优化。不过大部分滑动布局的这个属性默认都是false,所以设置为true，效果应该也不会很明显。

从你提供的GPU渲染分析图看，耗时都是在绘制和执行其他任务耗时，我无法分析出到底是什么原因引起的耗时。

**Comment by l-w-h** [comment]
我找到了原因，我继承了WebView画了个圆角导致卡顿，但是为什么我把绘画操作注释了，单纯的只是继承了WebView，什么操作都没做，也会卡顿，只能用自带的WebView才会正常。。。

**Comment by l-w-h** [comment]
找到原因了，这段代码导致的卡顿。。setLayerType(View.LAYER_TYPE_SOFTWARE,null)
