### ISSUE TITLE
需求：提供可选的match_parent元素的测量方式

### ISSUE THREAD

**Issue by Nstd** [donkingliang/ConsecutiveScroller#191]
希望提供一种可选的测量方式，如果某个match_parent的元素A是可滑动的（RecyclerView），如果它的前一个元素是悬浮元素，则A的高度是Container高度减去前面悬浮元素的高度，这样可以避免额外的不必要的滑动。

**Comment by donkingliang** [comment]
你提的这个功能，我之前也有考虑过。不过权衡之下，没有做通用的功能。主页考虑如下：

ConsecutiveScrollerLayout的可滑动子view的高度，要么是包裹内容的(wrap_content)，要么是充满父布局的(match_parent)。否则布局显示会有问题。但是如果可滑动子view是ConsecutiveScrollerLayout的最后一个View，并且ConsecutiveScrollerLayout设置了吸顶View，那么这个滑动View的高度就可以是Container高度减去吸顶布局的高度，所以这个功能只有在这种情况下才是能实现的。

我在库里的ConsecutiveViewPager/ConsecutiveViewPager2就提供了setAdjustHeight方法来实现这个功能。之所以需要提供方法由使用者传入布局的调整高度，是因为ConsecutiveViewPager本身无法计算需要调整的高度，原因是：
1、吸顶模式有普通吸顶、常驻吸顶、下沉吸顶三种，多个吸顶view共存时，吸顶占用的高度不同。
2、吸顶view的吸顶位置可以设置偏移量，而不是固定的。
3、吸顶view的显示和移除是可以动态控制的，而不是在布局的时候就固定不变的。

所以只有使用这最清楚吸顶view怎么实现、显示位置和占用空间。

如果一个可滑动的View（RecyclerView），在ConsecutiveScrollerLayout最后的位置，那么也可以通过这种方式动态计算和设置自己的高度。

**Comment by Nstd** [comment]
确实，一个框架需要考虑很多东西，感谢轮主造的这个轮子~
我们现在部分场景可以使用 `autoAdjustHeightAtBottomView` 这个属性，其他的可以自己动态计算高度去改变。
