### ISSUE TITLE
需求：IConsecutiveScroller 的解耦优化

### ISSUE THREAD

**Issue by Nstd** [donkingliang/ConsecutiveScroller#192]
现在需要容器去实现 `IConsecutiveScroller` 才能判断哪个子view需要处理滑动，这样会产生额外的View。
是否可以通过自定义属性的方式（比如：app:layout_isNestedContainer），标记嵌套容器。然后给 `ConsecutiveScrollerLayout` 设置一个接口，例如：
``` java
interface IConsecutiveScroller2 {
   // 返回需要滑动的ScrollView
    public View getCurrentScrollerView(View containerView);

    // 返回需要滑动的ScrollView
    public List<View> getScrolledViews(View containerView);
}
```
如果检测到某个View有那个自定义的属性，并设置这个接口后，就调用这个接口，让用户判断哪个子view是可滑动的。

**Comment by donkingliang** [comment]
用自定义属性指定哪个子view需要处理滑动，这是个不错的主意，而是也是可实现的，比如下面这样：

```
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout 
    android:id="@+id/scrollerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">
    
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_isNestedContainer="@+id/scrollView">
        
        <ScrollView
            android:id="@+id/scrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            
        </ScrollView>
        
    </LinearLayout>

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
```

这样就可以免去自定义View实现接口，让`ConsecutiveScrollerLayout`可以根据`isNestedContainer`指定的id寻找需要滑动的子view。

不过这种方式的局限性是只能指定一个可滑动的子view，实现不了像我库里的`ConsecutiveViewPager`这种滑动子view动态改变的情况。

这种方式使用简单，而且能适用于大部分需求，可以作为后续的优化功能。

至于你提到的给 `ConsecutiveScrollerLayout` 设置一个接口，我不太明白是如何设置，以及如果通过接口返回需要滑动的view？

**Comment by Nstd** [comment]
那个自定义属性不是用来指定『哪个子view需要处理滑动』，而是设置了自定义属性的那个view才需要用`IConsecutiveScroller2`接口去检测这个view中的哪些子view需要处理滑动，如果有多个这样的ViewGroup，可以通过`View.getId()`的方式分类讨论。

比如下面这个布局：
``` xml
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout 
    android:id="@+id/scrollerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">
    
    <LinearLayout
        android:id="@+id/container1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_isNestedContainer="true">
        
        <ScrollView
            android:id="@+id/scrollView1"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            
        </ScrollView>
        
    </LinearLayout>

    <LinearLayout
        android:id="@+id/container2"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_isNestedContainer="true">
        
        <ScrollView
            android:id="@+id/scrollView2"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            
        </ScrollView>
        
    </LinearLayout>

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
```

我们可以这样实现：
``` java
IConsecutiveScroller2 listener = new IConsecutiveScroller2()  {
    @Override
    public View getCurrentScrollerView(View containerView) {
        int id = containerView.getId();
        if(id == R.id.container1) {
            return containerView.findViewById(R.id.scrollView1);
        } else if(id == R.id.container2) {
            return containerView.findViewById(R.id.scrollView2);
        }
        return null;
    }

    @Override
    public List<View> getScrolledViews(View containerView) {
        //todo 这里类似上面的做法
    }
}

(ConsecutiveScrollerLayout)findViewById(R.id.scrollerLayout).setIConsecutiveScroller2(listener);
```

`ConsecutiveScrollerLayout`里增加一个`IConsecutiveScroller2`类型的变量，检测滑动的时候用它去做判断。

**Comment by donkingliang** [comment]
你的这种方案其实就是把原来由每个子Container各自实现的`getCurrentScrollerView`，`getScrolledViews`统一交由`IConsecutiveScroller2`接口实现。这样做的好处是省去了自定义子Container、将子Container和滑动view解耦，不再有强关联。

但是这种方案相比现有的方案，也有一些劣势：
1、项目存在多处相同的子Container时，一个自定义子Container比多个ConsecutiveScrollerLayout各自setIConsecutiveScroller2好。
2、ConsecutiveScrollerLayout下有多个不同的子Container时，全部由IConsecutiveScroller2处理会显得臃肿，代码逻辑不够清晰，不如Container各自处理自己的滑动view。
3、滑动view可能需要依赖Container的状态，比如Container在不同状态下返回不同的滑动view或者自身。这种情况由Container内部处理更加灵活和合理。如果是外部处理则难以实现。

所以你提的方案，如果只是为了把子Container和滑动view解耦，那么优势并不明显。

**Comment by donkingliang** [comment]
而且这种解耦效果，使用我提到的使用自定义属性指定滑动View也是可以实现的。

**Comment by Nstd** [comment]
> 你的这种方案其实就是把原来由每个子Container各自实现的`getCurrentScrollerView`，`getScrolledViews`统一交由`IConsecutiveScroller2`接口实现。这样做的好处是省去了自定义子Container、将子Container和滑动view解耦，不再有强关联。
> 
> 但是这种方案相比现有的方案，也有一些劣势：
> 1、项目存在多处相同的子Container时，一个自定义子Container比多个ConsecutiveScrollerLayout各自setIConsecutiveScroller2好。
> 2、ConsecutiveScrollerLayout下有多个不同的子Container时，全部由IConsecutiveScroller2处理会显得臃肿，代码逻辑不够清晰，不如Container各自处理自己的滑动view。
> 3、滑动view可能需要依赖Container的状态，比如Container在不同状态下返回不同的滑动view或者自身。这种情况由Container内部处理更加灵活和合理。如果是外部处理则难以实现。
> 
> 所以你提的方案，如果只是为了把子Container和滑动view解耦，那么优势并不明显。

---

不好意思，最近有点忙，没有及时回复。对于这几个问题说下我的看法。
1. 我们这边没有相同的Container，如果用Container这种方式去做，界面耦合会有点高。不同独立逻辑放到一个Container里去处理反而会麻烦。
2. 代码逻辑的清晰问题应由使用者考虑。因为使用场景很多，框架制作者不一定能考虑所有的情况（其实1的问题，有一半也是场景问题）。所以框架提供的功能在不破坏框架逻辑清晰的情况下能满足尽量多的需求会更好。
3. 这个还是耦合性的问题。比如某个Container下有两个RecyclerView布局，需要根据不同的状态去控制这两个RV的切换显示。然后根据对应的状态返回需要滑动的RV。针对不同的功能，布局是不一样的，用接口的方式，对应功能对应处理会更简单些。

**Comment by donkingliang** [comment]
你提的建议，在使用场景上确实也有它的好处。不过已有的IConsecutiveScroller接口方式已经能满足这样的需求了，框架不应该为解决同样的需求，提供两套相似的方案。

至于耦合性的问题，只要Container实现IConsecutiveScroller接口时，不做具体实现，而是把接口方法的具体实现转给使用者即可。

**Comment by Nstd** [comment]
emmm... 这个还是仁者见仁，智者见智。如果以后还有人提类似的需求，轮主可以再考虑下。辛苦轮主 👍
