### ISSUE TITLE
如何让consecutiveScrollerLayout的非直接子view获得置顶效果？

### ISSUE THREAD

**Issue by 317Isaac** [donkingliang/ConsecutiveScroller#193]
基于目前的代码结构，consecutiveScrollerLayout内嵌套tablayout和viewpage，viewpage内嵌套了Linearlayout，textView。
如何让tablayout和textview同时保持置顶状态？
目前viewpage内的子view无法处于置顶，想知道可否使用内部再嵌套consecutiveScrollerLayout的方式做到同时置顶

**Comment by donkingliang** [comment]
可是使用内部再嵌套consecutiveScrollerLayout，让textview在内部的consecutiveScrollerLayout吸顶。不过要注意，内部的吸顶可能会被外部的吸顶覆盖，所以你需要使用setStickyOffset方法调整一下内部的吸顶位置。

**Comment by 317Isaac** [comment]
我目前使用一个自定义view继承consecutiveScrollerLayout作为viewPage内部View的根布局，此时底部ViewPage内无法继续向下滑动，我将自定义View继承修改为ScrollView后，ViewPage内可以正常上下滑动，这里是否有对内部嵌套View做限制？

**Comment by donkingliang** [comment]
使用consecutiveScrollerLayout作为viewPage内部View的根布局是可以的，你的自定义view，是否有对consecutiveScrollerLayout做了什么修改。另外你的ViewPage是我提供的ConsecutiveViewPager、ConsecutiveViewPager2吗？consecutiveScrollerLayout不能嵌套原生的ViewPage。

**Comment by 317Isaac** [comment]
自定义View是通过布局inflate加载出后添加进ViewPage的，我这边有一些业务生命周期需要通过这个自定义view下发，未对View绘制流程等做修改，使用的是ConsecutiveViewPager。但ConsecutiveViewPager并不是外层consecutiveScrollerLayout的直接子布局，不知这个是否会有影响。

**Comment by donkingliang** [comment]
> 自定义View是通过布局inflate加载出后添加进ViewPage的，我这边有一些业务生命周期需要通过这个自定义view下发，未对View绘制流程等做修改，使用的是ConsecutiveViewPager。但ConsecutiveViewPager并不是外层consecutiveScrollerLayout的直接子布局，不知这个是否会有影响。

有影响，ConsecutiveViewPager必须是ConsecutiveScrollerLayout的直接子View。需要滑动的View都必须是ConsecutiveScrollerLayout的直接子View。

**Comment by 317Isaac** [comment]
可以通过IConsecutiveScroller接口返回ConsecutiveViewPager的getScrollerViews解决这个问题吗？

**Comment by donkingliang** [comment]
可以。

**Comment by 317Isaac** [comment]
那就是我在ConsecutiveViewPager的父布局（直接子view）的getScrollerViews中返回ConsecutiveViewPager本身，还是返回ConsecutiveViewPager的getScrollerViews？

**Comment by donkingliang** [comment]
返回ConsecutiveViewPager的getCurrentScrollerView()和getScrolledViews()

**Comment by 317Isaac** [comment]
之前就是返回的getCurrentScrollerView()和getScrolledViews()，还是不行的

**Comment by donkingliang** [comment]
你是那个类实现IConsecutiveScroller接口？自定义的consecutiveScrollerLayout吗？要consecutiveScrollerLayout的直接子view实现IConsecutiveScroller接口，而不是consecutiveScrollerLayout。就是你用什么布局嵌套了ConsecutiveViewPager，就由它实现IConsecutiveScroller接口。

**Comment by 317Isaac** [comment]
我外层嵌套布局是因为有其他生命周期业务需要分发，有业务需要上层View处理动态加载，下面是我的布局。
代码在开发环境无法提供，写了一下demo

class TempLinearLayout @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : LinearLayout(context, attrs, defStyleAttr),IConsecutiveScroller {

    private lateinit var viewPage:ConsecutiveViewPager
    override fun onFinishInflate() {
        super.onFinishInflate()
        viewPage = findViewById(R.id.viewPager)
    }
    override fun getCurrentScrollerView(): View {
        return viewPage.currentScrollerView
    }

    override fun getScrolledViews(): MutableList<View> {
        return viewPage.scrolledViews
    }
}

<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/scrollerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical">

        <com.donkingliang.consecutivescrollerdemo.TempLinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <TextView
                android:id="@+id/text"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/white"
                android:padding="10dp"
                android:textColor="@android:color/black"
                android:textSize="18sp" />

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/tabLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@android:color/white"
                app:layout_isSticky="true"
                app:tabGravity="fill"
                app:tabIndicatorColor="@color/colorPrimary"
                app:tabIndicatorHeight="3dp"
                app:tabMode="scrollable"
                app:tabSelectedTextColor="@color/colorPrimary" />

            <com.donkingliang.consecutivescroller.ConsecutiveViewPager
                android:id="@+id/viewPager"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </com.donkingliang.consecutivescrollerdemo.TempLinearLayout>
    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>


<com.donkingliang.consecutivescrollerdemo.TempScrollerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="50dp"
        app:layout_isSticky="true"
        android:background="#a7f8fd"
        />
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="1000dp"
        android:background="#111111"
        />

继承自ConsecutiveScrollerLayout

class TempScrollerView @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : ConsecutiveScrollerLayout(context, attrs, defStyleAttr) {

}
</com.donkingliang.consecutivescrollerdemo.TempScrollerView>

其他部分代码与未修改界面布局关系。viewpage子view使用layoutinflate出实例。通过viewpageadapter添加到viewpage中。

**Comment by donkingliang** [comment]
[ConsecutiveScroller.zip](https://github.com/donkingliang/ConsecutiveScroller/files/6519717/ConsecutiveScroller.zip)
 
我用你的两个自定义View，是没有问题的。你看一下我发出来的demo，再排查一下你的代码吧。

**Comment by 317Isaac** [comment]
多谢您，已经找到问题，是内部子view高度有问题，无法完成滑动，已经修改。
