### ISSUE TITLE
有没有办法知道在滑动的过程中子view离顶部的距离

### ISSUE THREAD

**Issue by wallacedong** [donkingliang/ConsecutiveScroller#197]
有没有办法知道在滑动的过程中子view离顶部的距离
比如电商商品详情，滑动到评论列表上面tab标识会移到评论的位置，滑动到推荐列表上面的tab标识会移动道推荐的位置

**Comment by donkingliang** [comment]
子view.getTop - scrollerLayout.getScrollY()

**Comment by wallacedong** [comment]
> 子view.getTop - scrollerLayout.getScrollY()

我试试
