### ISSUE TITLE
比如一个LinearLayout的内部有个RecyclerView，LinearLayout的整个显示高度会超过一屏

### ISSUE THREAD

**Issue by wallacedong** [donkingliang/ConsecutiveScroller#198]
比如一个LinearLayout的内部有个RecyclerView，LinearLayout的其他部分加上RecyclerView整个显示高度会超过一屏，也就是超过ConsecutiveScroller的显示高度，这个时候需要在LinearLayout的外面套一个ScrollView吗

**Comment by donkingliang** [comment]
是的，需要。不过你把RecyclerView嵌套在ScrollView里面，就失去了RecyclerView的item复用功能，就没有必要使用ConsecutiveScrollerLayout了。

**Comment by wallacedong** [comment]
> 是的，需要。不过你把RecyclerView嵌套在ScrollView里面，就失去了RecyclerView的item复用功能，就没有必要使用ConsecutiveScrollerLayout了。

我这个也没办法复用，相当于ConsecutiveScrollerLayout里面有很多块布局，其中一块布局比较长，除了最后的RecyclerView，这个布局的其他部分都会超过一屏，最后有一块布局是个商品列表，这个我作为ConsecutiveScrollerLayout的直接子View就可以复用，上面说的那个本身就没复用的可能
