### ISSUE TITLE
配合ViewPager效果好像有点奇怪

### ISSUE THREAD

**Issue by Leelion96** [donkingliang/ConsecutiveScroller#2]

**Comment by Leelion96** [comment]
ViewPager中嵌套RecyclerView，滑动的效果变得很奇怪

**Comment by Leelion96** [comment]
非常好的库，先点个赞！

**Comment by donkingliang** [comment]
ViewPager嵌套RecyclerView，让ViewPager添加app:layout_isConsecutive="false"属性。因为ViewPager在自己的范围内滑动RecyclerView，他的区域属于局部滑动的情况。

**Comment by Leelion96** [comment]
> ViewPager嵌套RecyclerView，让ViewPager添加app:layout_isConsecutive="false"属性。因为ViewPager在自己的范围内滑动RecyclerView，他的区域属于局部滑动的情况。

我的情况类似鸿洋大神的StickyNavLayout，有Top、Tab、ViewPager（嵌套RV），上中下三个区域，Tab的区域可以吸顶，如果给VP设置了app:layout_isConsecutive="false"的话，确实有局部滑动的效果，但无法和根部局的Top、Tab等联动滑动了，大佬这个好解吗？

**Comment by Leelion96** [comment]
我本质是想用这个替换StickyNavLayout，实现coordinator的效果，之前是参照鸿洋大神的https://github.com/hongyangAndroid/Android-StickyNavLayout，我想要的效果跟这个库里面的示例图是一样的。

**Comment by Leelion96** [comment]
我发现我项目里滑动奇怪的效果，跟Demo里面，把activity_consecutive.xml里面的红色RecyclerView设置layout_isConsecutive = “true” 的效果差不多，就是RV也在滑，首页也在滑，会很奇怪

**Comment by donkingliang** [comment]
设置layout_isConsecutive = “true”会导致ConsecutiveScrollerLayout追踪处理滑动事件，所以首页也会滑动。你的需求是先让父布局滑动，后面再让RecyclerView自己滑动，这个不太符合ConsecutiveScrollerLayout的整体滑动设计。

**Comment by Leelion96** [comment]
> 设置layout_isConsecutive = “true”会导致ConsecutiveScrollerLayout追踪处理滑动事件，所以首页也会滑动。你的需求是先让父布局滑动，后面再让RecyclerView自己滑动，这个不太符合ConsecutiveScrollerLayout的整体滑动设计。

我理解，这个问题我先关闭了，我自己尝试改造我的项目，将RV分出来作为整体的一部分也许可行。

**Comment by Leelion96** [comment]
我尝试将ViewPager里面的RV独立出来，整个首页用大佬的库一体化之后不用再去单独做子View的事件分发，第一次感受到页面的滑动如此流畅！
