### ISSUE TITLE
如果容器最下方是个recyclerview，调用smoothScrollToChild会导致最后的recycler内容向上滚动到底部，用scrollTo就没事

### ISSUE THREAD

**Issue by wallacedong** [donkingliang/ConsecutiveScroller#204]

**Comment by wallacedong** [comment]
没办法我就使用了valueanimator产生一个值的序列，调用scrollTo

**Comment by wallacedong** [comment]
> 你是不是有使用吸顶功能，并且autoAdjustHeightAtBottomView="true"？

是的，正确姿势应该是啥样的

**Comment by donkingliang** [comment]
这是我在处理autoAdjustHeightAtBottomView时的bug，我已经修复了，你使用新版本试一下。

**Comment by wallacedong** [comment]
> 这是我在处理autoAdjustHeightAtBottomView时的bug，我已经修复了，你使用新版本试一下。

好的

**Comment by wallacedong** [comment]
> > 这是我在处理autoAdjustHeightAtBottomView时的bug，我已经修复了，你使用新版本试一下。
> 
> 好的

还有一个问题，smoothScrollToChild之后怎样知道滚动完成了，只能通过setOnVerticalScrollChangeListener得知吗

**Comment by wallacedong** [comment]
> > > 这是我在处理autoAdjustHeightAtBottomView时的bug，我已经修复了，你使用新版本试一下。
> > 
> > 
> > 好的
> 
> 还有一个问题，smoothScrollToChild之后怎样知道滚动完成了，只能通过setOnVerticalScrollChangeListener得知吗

我试了下，可以修改滚动速度吗，这个有点快

**Comment by donkingliang** [comment]
1、滚动完成只能通过setOnVerticalScrollChangeListener监听

2、滚动速度是在内部设置的，外部修改不了。如果要修改，需要修改代码。
