### ISSUE TITLE
recyclerview不能回调scrollStateChanges

### ISSUE THREAD

**Issue by wallacedong** [donkingliang/ConsecutiveScroller#207]
嵌套在这个布局里面之后recyclerview不能回调scrollStateChanges了吗

**Comment by donkingliang** [comment]
是，监听滑动事件使用scrollerLayout.setOnVerticalScrollChangeListener。因为嵌套在ConsecutiveScrollerLayout的view，滑动事件都有ConsecutiveScrollerLayout来处理。

**Comment by wallacedong** [comment]
> 是，监听滑动事件使用scrollerLayout.setOnVerticalScrollChangeListener。因为嵌套在ConsecutiveScrollerLayout的view，滑动事件都有ConsecutiveScrollerLayout来处理。

那有啥办法知道滚动到底部加载更多
