### ISSUE TITLE
快速的上下滑动fling效果会消失

### ISSUE THREAD

**Issue by Laddie1994** [donkingliang/ConsecutiveScroller#208]

**Comment by mliyuanbiao** [comment]
我也遇到了，demo程序就是这样，还没有接入项目中，因为滑动不够流畅

**Comment by donkingliang** [comment]
多谢反馈，我大概知道是什么原因了，我会在后续的版本中优化这个问题。

**Comment by kongnanlive** [comment]
> 多谢反馈，我大概知道是什么原因了，我会在后续的版本中优化这个问题。

我就是因为这个原因放弃的 #80 #201

**Comment by kongnanlive** [comment]
4.5.2好了很多，但是还是在反复上下快速滚动的时候卡住，就是滑动突然变慢了，也没有fling效果了。

反复上下快速滚动这种场景，用户还是会碰到的。

**Comment by 317Isaac** [comment]
同上，快速滑动会偶现卡顿
