### ISSUE TITLE
滑动偶现ANR错误

### ISSUE THREAD

**Issue by zhangmeie2006** [donkingliang/ConsecutiveScroller#210]
出现问题时4.5.1版本，新版本是否解决？

#1 main
Input dispatching timed out
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 22. Wait queue head age: 6670.2ms.)
解析原始
1
android.view.ViewGroup.findViewTraversal(ViewGroup.java:4631)
2
android.view.View.findViewById(View.java:24182)
3
android.view.ViewGroup.findViewTraversal(ViewGroup.java:4642)
4
android.view.View.findViewById(View.java:24182)
5
android.view.ViewGroup.findViewTraversal(ViewGroup.java:4642)
6
android.view.View.findViewById(View.java:24182)
7
com.donkingliang.consecutivescroller.ScrollUtils.getScrollChild(ScrollUtils.java:352)
8
com.donkingliang.consecutivescroller.ScrollUtils.getScrolledView(ScrollUtils.java:326)
9
com.donkingliang.consecutivescroller.ScrollUtils.computeVerticalScrollOffset(ScrollUtils.java:26)
10
com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.getViewsScrollOffset(ConsecutiveScrollerLayout.java:2168)
11
com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollDown(ConsecutiveScrollerLayout.java:1108)
12
com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.dispatchScroll(ConsecutiveScrollerLayout.java:1020)
13
com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollToChildWithOffset(ConsecutiveScrollerLayout.java:2099)
14
com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollToChild(ConsecutiveScrollerLayout.java:2064)
15

**Comment by donkingliang** [comment]
看日志无法定位是什么原因因为的ANR

**Comment by donkingliang** [comment]
看日志无法定位是什么原因引起的ANR

**Comment by zhangmeie2006** [comment]
> 看日志无法定位是什么原因引起的ANR

升级到了4.5.2版本，测试发现还是有anr：
1，使用场景是滚动到吸顶view  FloatConsecutiveScrollerLayout.scrollToChild(吸顶view)

2，进行了定位，发现是scrollToChildWithOffset()方法的do{}while死循环了：
       do {
                    if (scrollOrientation < 0) {
                        dispatchScroll(-200);
                    } else {
                        dispatchScroll(200);
                    }
                } while (mScrollToIndex != -1);

3，发现scrollToChild()->scrollToChildWithOffset()->dispatchScroll()->scrollDown()->没有走scrollChange()且mScrollToIndex没改变，具体断点信息如下：第三张图是死循环代码

<img width="1212" alt="405FFD06-7480-4C53-8640-9697DE0D2AA3" src="https://user-images.githubusercontent.com/87069003/125403579-42595280-e3e8-11eb-8807-3458c95d05be.png">
<img width="1109" alt="883BA288-F807-4C51-9261-51E2AD883CD5" src="https://user-images.githubusercontent.com/87069003/125403527-340b3680-e3e8-11eb-9991-e935c6dde2dd.png">
<img width="677" alt="B18FB51B-711C-419E-9E91-7408AA994991" src="https://user-images.githubusercontent.com/87069003/125403600-48e7ca00-e3e8-11eb-922c-d8eabb5b6316.png">

**Comment by zhangmeie2006** [comment]
<img width="1228" alt="ECA1AF2E-7D9D-4DCF-AF64-7D7BE47486A9" src="https://user-images.githubusercontent.com/87069003/125405709-96653680-e3ea-11eb-9b75-169819090201.png">

**Comment by donkingliang** [comment]
如果是由于mScrollToIndex没有改变导致死循环，那么你断点看一下下面的代码为什么没有执行到。
![image](https://user-images.githubusercontent.com/5499532/125408001-05438f00-e3ed-11eb-897c-17151dd97ee9.png)

**Comment by zhangmeie2006** [comment]
getScrollY() + getPaddingTop() + viewScrollOffset <= scrollAnchor || isScrollTop()
444 + 0 + 0 <= 282 || false
<img width="1237" alt="1E8DD2FD-5742-4B75-A6B2-B378191D06FC" src="https://user-images.githubusercontent.com/87069003/125420063-929729ae-6356-41ea-bced-2f9001c3945f.png">


是isScrollTop()判断不对？getScrollY()=444
<img width="1335" alt="68508480-B886-4F66-9D8C-F86B9F5E652D" src="https://user-images.githubusercontent.com/87069003/125420558-2a7a117b-c2fb-42ee-91a0-f86d0bb5b2aa.png">

**Comment by zhangmeie2006** [comment]
<img width="1320" alt="4A6C31F1-7F58-4F14-8F0D-75E50DB8A7EF" src="https://user-images.githubusercontent.com/87069003/125420879-4bbab0c5-d65a-4304-bf9e-13833d22748d.png">

**Comment by donkingliang** [comment]
还没有滑动到顶部吧，所以isScrollTop()返回false。如果布局已经滑到顶部，isScrollTop()返回false就是不正常的。

你能发个demo给我调试吗？

**Comment by zhangmeie2006** [comment]
isScrollTop()没有问题，是不是这样引起的？
1，ConsecutiveScrollerLayout控件最底下是一个TextView，TextView上面是RecyclerView；
2，步骤1，最底下TextView隐藏，scrollToChild能正常滚动到吸顶view；
3，步骤2，操作后最底下TextView设置显示，scrollToChild调用后TextView是不能滚动的childScrollOffset=0，没有走scrollChild(),直接调用的scrollSelf()方法，但是高度是没有变化的，不会触发滚动
int childScrollOffset = ScrollUtils.getScrollTopOffset(lastVisibleView);
![image](https://user-images.githubusercontent.com/87069003/125426861-174b2808-ad7c-49a6-a902-4de5ab3f99c0.png)


![image](https://user-images.githubusercontent.com/87069003/125426755-9d9789b7-baf0-4b04-8a80-2492a54e6909.png)

**Comment by zhangmeie2006** [comment]
> 还没有滑动到顶部吧，所以isScrollTop()返回false。如果布局已经滑到顶部，isScrollTop()返回false就是不正常的。
> 
> 你能发个demo给我调试吗？
项目问题，我只能把删减后布局发你

**Comment by zhangmeie2006** [comment]
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
            android:id="@id/swipe_target"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            
            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/space_10"
                android:background="@color/mainbg_v2"/>

            <androidx.recyclerview.widget.RecyclerView
                android:id="@id/product_recycle_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/layout_top"
                android:background="@color/mainbg_v2"
                android:overScrollMode="never"
                android:scrollbars="vertical" />

            <TextView
                android:id="@+id/tv_empty_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingTop="@dimen/space_12"
                android:background="@color/mainbg_v2"
                android:paddingBottom="@dimen/space_20"
                android:textColor="@color/gray2_v2"
                android:gravity="center"
                android:text="——· 亲，已经到底啦! ·——"
                android:visibility="gone" />


        </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
我这边无法重现到问题。你能写个能重现问题的demo吗？

另外你可以在scrollUp和scrollDown方法加入下面这段代码试一下。这需要你导入源码修改。
![image](https://user-images.githubusercontent.com/5499532/125555067-179413fe-4ae1-44bc-9ca7-74bc7f4528d8.png)

这只是为了防止mScrollToIndex没有改变导致死循环。但是我认为mScrollToIndex没有改变是由于其他原因造成的。

**Comment by hongqinghe** [comment]
我这边也偶现了ANR 问题，看堆栈信息和上面类似
![image](https://user-images.githubusercontent.com/25189458/143190982-44516335-300d-4697-ac95-2538f3a5a309.png)
