### ISSUE TITLE
超过一屏的数据，最底部是个横向Recycleview并且滑到最右边时，无法上下滚动

### ISSUE THREAD

**Issue by ujffdi** [donkingliang/ConsecutiveScroller#212]
https://user-images.githubusercontent.com/20896405/125557871-f8bd386f-fc6b-4843-90ec-4ce47894ac33.mp4

麻烦给我留个邮箱，我写了个demo。也复现了这个情况

**Comment by ujffdi** [comment]
使用最新的4.5.2版本

**Comment by ujffdi** [comment]
解决方案：在RecycleView套多一层FrameLayout即可

**Comment by donkingliang** [comment]
>  1626234345472218.mp4 
> 麻烦给我留个邮箱，我写了个demo。也复现了这个情况

1043214265@qq.com  谢谢

**Comment by ujffdi** [comment]
> > 1626234345472218.mp4 这个麻烦
> > 给我留个邮箱，我写了个demo。也复现了情况
> 
> [1043214265@qq.com](mailto:1043214265@qq.com) 谢谢

已发送

**Comment by donkingliang** [comment]
> > > 1626234345472218.mp4 这个麻烦
> > > 给我留个邮箱，我写了个demo。也复现了情况
> > 
> > 
> > [1043214265@qq.com](mailto:1043214265@qq.com) 谢谢
> 
> 已发送

多谢反馈，是因为我在判断RecycleView水平滑动时，写错了一个判断条件。这个问题我会在后续的版本中修复。

在RecycleView套多一层FrameLayout的方式是可行的，因为这个错误的判断只会影响ConsecutiveScrollerLayout的直接子view，只要不是直接子view，就没有问题。

**Comment by ujffdi** [comment]
> > > > 1626234345472218.mp4 这个麻烦
> > > > 给我留个邮箱，我写了个demo。也复现了情况
> > > 
> > > 
> > > [1043214265@qq.com](mailto:1043214265@qq.com) 谢谢
> > 
> > 
> > 已发送
> 
> 多谢反馈，是因为我在判断RecycleView水平滑动时，写错了一个判断条件。这个问题我会在后续的版本中修复。
> 
> 在RecycleView套多一层FrameLayout的方式是可行的，因为这个错误的判断只会影响ConsecutiveScrollerLayout的直接子view，只要不是直接子view，就没有问题。

麻烦您了，这个库很好用，一直用在项目中

**Comment by DynastyOrz** [comment]
感谢哥们探路，我正好也遇到这个问题了

**Comment by donkingliang** [comment]
> 感谢哥们探路，我正好也遇到这个问题了

新版本已修复这个问题。
