### ISSUE TITLE
子布局多向滑动冲突问题

### ISSUE THREAD

**Issue by 317Isaac** [donkingliang/ConsecutiveScroller#214]
现需要实现一个自定义View在长按后可自由滑动类似坐标图的模式。
当这个View在ConsecutiveScroller中时，move事件在dispatchTouchEvent中已经将Y坐标固定，导致无法竖直滑动。
能否修改为监听器模式，监听子布局选择是否需要固定子布局event的Y坐标？

**Comment by donkingliang** [comment]
> 现需要实现一个自定义View在长按后可自由滑动类似坐标图的模式。
> 当这个View在ConsecutiveScroller中时，move事件在dispatchTouchEvent中已经将Y坐标固定，导致无法竖直滑动。
> 能否修改为监听器模式，监听子布局选择是否需要固定子布局event的Y坐标？

不能，如果你想你的自定义View能同时滑动水平方向和垂直方向，你只能设置layout_isConsecutive=false。因为子view跟ConsecutiveScroller整体滑动时，垂直滑动事件是由ConsecutiveScroller消费的，子view不能处理。

当然，你可以通过requestDisallowInterceptTouchEvent来让ConsecutiveScroller不拦截事件，这样就需要你自己处理滑动事件的分发和解决滑动冲突了。

**Comment by 317Isaac** [comment]
现在问题就是我想根据需要动态修改控件的layout_isConsecutive=false。和requestDisallowInterceptTouchEvent。但是因为处理Y坐标是在dispatchTouchEvent中根据滑动状态修改的，一旦滑动开始后就无法修改该状态 ，导致设置的属性和requestDisallowInterceptTouchEvent均无法影响已经被固定的Y坐标

**Comment by donkingliang** [comment]
动态修改layout_isConsecutive属性后，在下一次事件序列才生效。如果你是在触摸的过程中修改layout_isConsecutive属性，你可以在修改后，动态向ConsecutiveScroller的dispatchTouchEvent传一个ACTION_DOWN的MotionEvent事件，让滑动状态重置。

**Comment by 317Isaac** [comment]
手动触发ACTION_DOWN还是会导致其他问题，我这边想是否可以增加一个重置滑动方向的方法，但是这样可能对滑动系统有侵入性

**Comment by donkingliang** [comment]
> 手动触发ACTION_DOWN还是会导致其他问题，我这边想是否可以增加一个重置滑动方向的方法，但是这样可能对滑动系统有侵入性

外部除了触发ACTION_DOWN事件外，无法通过其他方法重置滑动状态。如果要改源码的话，需要注意对其他滑动情况的影响，ConsecutiveScroller固定Y坐标，是为了防止子view水平滑动时触发了自己的垂直滑动，导致不跟ConsecutiveScroller整体滑动。所以原来的设计了，子view想要自由滑动，必须先设置layout_isConsecutive=false，脱离整体滑动。

像你这个先整体滑动，长按后自由滑动的情况，通过动态设置layout_isConsecutive可以切换，但是在同一个事件系列中切换后，无法重置滑动状态，只能在下一次事件序列才生效。

或许你需要修改源码来满足你的需求，或者固定layout_isConsecutive=false，让事件由子view处理，然后自己处理子view与父view的滑动冲突。
