### ISSUE TITLE
getScrollChild方法返回对象异常

### ISSUE THREAD

**Issue by 317Isaac** [donkingliang/ConsecutiveScroller#215]
static View getScrollChild(View view) {
        if (view != null) {
            ViewGroup.LayoutParams lp = view.getLayoutParams();

            if (lp instanceof ConsecutiveScrollerLayout.LayoutParams) {
                int childId = ((ConsecutiveScrollerLayout.LayoutParams) lp).scrollChild;
                View child = view.findViewById(childId);
                if (child != null) {
                    return child;
                }
            }
        }
        return view;
    }

获取需要滑动布局时，外层布局未设置scrollChild属性，默认childId=0，通过findViewById返回的child 为布局内一个TextView，导致获取滑动布局出错

**Comment by 317Isaac** [comment]
找到的那个TextView是动态inflate然后添加进去的。我打了断点，看到结果是childID=0，然后findviewByID时候获取到了这个textview。

感觉这边是不是给scrollChild属性增加一个默认值？findViewById时候如若ID=View.NO_ID(-1)就会直接返回null。这边是不是增加一个默认值，未进行设置的时候scrollChild参数是-1

**Comment by donkingliang** [comment]
> 找到的那个TextView是动态inflate然后添加进去的。我打了断点，看到结果是childID=0，然后findviewByID时候获取到了这个textview。
> 
> 感觉这边是不是给scrollChild属性增加一个默认值？findViewById时候如若ID=View.NO_ID(-1)就会直接返回null。这边是不是增加一个默认值，未进行设置的时候scrollChild参数是-1

是的，应该给scrollChild默认值为View.NO_ID，我之前没有考虑到view的id会为0的情况。
