### ISSUE TITLE
当我使用ConsecutiveScrollerLayout作为CoordinatorLayout的一部分并设置了app:layout_behavior="@string/bottom_sheet_behavior"时

### ISSUE THREAD

**Issue by tromoLi** [donkingliang/ConsecutiveScroller#219]
ConsecutiveScrollerLayout内部超过两个控件，滑上去之后超出原有位置的部分不会响应滑动事件了

**Comment by donkingliang** [comment]
请描述一下具体的表现和提供布局代码

**Comment by tromoLi** [comment]
最外层用CoordinatorLayout包裹，内层先是一个AppBarLayout，然后是ConsecutiveScrollerLayout，ConsecutiveScrollerLayout设置app:layout_behavior="@string/bottom_sheet_behavior"，ConsecutiveScrollerLayout内部添加几个textview和若干recyclerview。向上滑动触发ConsecutiveScrollerLayout到顶部，然后ConsecutiveScrollerLayout的上半部分（超过原有位置的）就不会响应滑动事件了

**Comment by tromoLi** [comment]
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:fitsSystemWindows="true">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
  <androidx.coordinatorlayout.widget.CoordinatorLayout
            android:id="@+id/coo_wallet"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_0"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/">

            <com.google.android.material.appbar.AppBarLayout
                android:id="@+id"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                app:elevation="@dimen/dp_0">
。。。
                </com.google.android.material.appbar.AppBarLayout>
                               <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
                                           android:layout_width="match_parent"
                                            android:layout_height="wrap_content"
                                             app:layout_behavior="@string/bottom_sheet_behavior"
                                                     >
                                            <textview.../>
                                            <textview.../>
                                              <androidx.recyclerview.widget.RecyclerView... />
                                              <androidx.recyclerview.widget.RecyclerView... />
                               </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
                       </androidx.coordinatorlayout.widget.CoordinatorLayout>

    </androidx.constraintlayout.widget.ConstraintLayout>类似这样

**Comment by donkingliang** [comment]
这不是ConsecutiveScrollerLayout引起的问题吧。我把ConsecutiveScrollerLayout换成NestedScrollView也会有这种问题。但是把AppBarLayout换成LinearLayout就没有问题了。应该是AppBarLayout引起的事件冲突。

**Comment by tromoLi** [comment]
您好，我也找到问题了，应该是我上面的appbarlayout子控件设置了scrollflag的问题，对的，感谢解答，问题我关闭了
