### ISSUE TITLE
似乎平滑滚动到某个控件，不能往回滚动？

### ISSUE THREAD

**Issue by Matchas-xiaobin** [donkingliang/ConsecutiveScroller#23]
似乎平滑滚动到某个控件，不能往回滚动？下面的控件可以滑下去，上面的控件就滑不上来了

**Comment by Matchas-xiaobin** [comment]
smoothScrollToChild这个方法，传入前面的子控件不会滚动，传入后面的会滚动

**Comment by donkingliang** [comment]
> smoothScrollToChild这个方法，传入前面的子控件不会滚动，传入后面的会滚动
多谢反馈，确实有个判断写反了。我后面跟新一下，谢谢！

**Comment by Matchas-xiaobin** [comment]
能分享这么好用的东西，我们才是要谢谢你呢。顺便想问下，如果我想快速 平滑滚动到指定控件位置，怎么做呢？类似rv里面一个屏幕内可显示10条，然后当前在100条，快速滚动回到第一条的话，一般都是先scrollToPosition(20),然后在smoothToPosition(0)这样子，就能快速到第一条了。

**Comment by donkingliang** [comment]
ConsecutiveScroller也有scrollToChild和smoothScrollToChild两种滑动到指定方法。但都是以它的直接子view为目标的。

**Comment by donkingliang** [comment]
已修复
