### ISSUE TITLE
滑动下级子View使用上拉加载会把悬停栏给顶上去，有没有解决办法呢

### ISSUE THREAD

**Issue by zs18340282344** [donkingliang/ConsecutiveScroller#230]
__

**Comment by donkingliang** [comment]
监听上拉时的布局偏移，使用ConsecutiveScrollerLayout的setStickyOffset调整悬停栏的位置。

参考我的demo中的ViewPagerActivity、ViewPager2Activity的例子

**Comment by zs18340282344** [comment]
大神怎么提高滑动速度呢，在滑动的过程和正常的列表对比滑动的速度慢一些，我可以更改滑动速度吗

**Comment by donkingliang** [comment]
不能更改滑动速度。如果你修改源码，可以给fling方法的参数velocityY乘以一个系数，将fling的velocityY放大。
