### ISSUE TITLE
大神每次滑动只能滑动两三个item,怎样增加滑动距离呢

### ISSUE THREAD

**Issue by zs18340282344** [donkingliang/ConsecutiveScroller#232]

**Comment by donkingliang** [comment]
什么意思，你是fling没有惯性吗？

**Comment by zs18340282344** [comment]
惯性特别短，比如在微信朋友圈我滑一下可以滚很远，但是在我使用的这个控件里嵌套的recyclerview滑动一次只能滑动大概23个item惯性特别小

**Comment by zs18340282344** [comment]
demo里也是这样的，我把item设置200dp然后用单手操作手机的时候，用大拇指向上下滑动，滚动距离特别近，就得不断地滑滑滑

**Comment by zs18340282344** [comment]
> 什么意思，你是fling没有惯性吗？

惯性特别短，比如在微信朋友圈我滑一下可以滚很远，但是在我使用的这个控件里嵌套的recyclerview滑动一次只能滑动大概23个item惯性特别小

**Comment by zs18340282344** [comment]
> 什么意思，你是fling没有惯性吗？

demo里也是这样的，我把item设置200dp然后用单手操作手机的时候，用大拇指向上下滑动，滚动距离特别近，就得不断地滑滑滑

**Comment by donkingliang** [comment]
你可以通过修改源码放大fling方法的速度。外部没有办法修改滑动速度

**Comment by zs18340282344** [comment]
> 你可以通过修改源码放大fling方法的速度。外部没有办法修改滑动速度

我就是想修改源码在哪里改呢 fling((int) velocityY*2);这样改吗？

**Comment by donkingliang** [comment]
是的，在调用fling方法时把参数放大；或者在fling方法内部把传入的参数放大

**Comment by zs18340282344** [comment]
> 是的，在调用fling方法时把参数放大；或者在fling方法内部把传入的参数放大

我放大后怎么没什么明显感觉呢
