### ISSUE TITLE
ConsecutiveViewPager+Recyclerview不满一屏数据也可以向上滑动

### ISSUE THREAD

**Issue by rayzeng0221** [donkingliang/ConsecutiveScroller#233]
大佬，ConsecutiveViewPager下的Fragment布局是Recyclerview，当我的Recyclerview的数据没有超出屏幕的时候，应该不能让他滑动，超出多少数据滑动多少，这个该怎么解决呀？

**Comment by donkingliang** [comment]
你的Fragment或者Recyclerview还有其他布局吧。如果Fragment内容不满一屏，那么你应该设置Fragment的view为wrap_content，因为如果设置为match_parent，那么它至少要占满一屏的空间
