### ISSUE TITLE
文档中未及时  不知道是否有此功能

### ISSUE THREAD

**Issue by billdizl** [donkingliang/ConsecutiveScroller#234]
项目中要实现吸顶功能,对吸顶功能设置一定的偏移量,当点击让某一控件吸顶view实现吸顶功能时(使用smoothScrollToChild(吸顶view)),那么该吸顶view下面的布局会有一定的偏移量,这个如何解决

**Comment by donkingliang** [comment]
你想要的效果是view吸顶时离顶部有一定的偏移量，还是view吸顶时下面的布局再往上滑动一定的偏移量？

**Comment by donkingliang** [comment]
你可以使用setStickyOffset设置吸顶到顶部的偏移，使用smoothScrollToChild(view,offset))设置自动滑动时的上下偏移。

**Comment by billdizl** [comment]
已解决该问题,
吸顶和自动滑动时两个独立的功能，没有关联性，所以他们之间的偏移需要自己设置。

smoothScrollToChild的功能类似于recyclerview的scrollToPosition，是用于布局定位的，跟吸顶没有必然联系。
