### ISSUE TITLE
RecyclerView.addOnScrollListener()会失效

### ISSUE THREAD

**Issue by Jason0501** [donkingliang/ConsecutiveScroller#235]

**Comment by donkingliang** [comment]
是的，监听滑动要使用ConsecutiveScrollerLayout的setOnVerticalScrollChangeListener。只能监听ConsecutiveScrollerLayout的滑动，不能单独监听子view的滑动了。

**Comment by Jason0501** [comment]
> 是的，监听滑动要使用ConsecutiveScrollerLayout的setOnVerticalScrollChangeListener。只能监听ConsecutiveScrollerLayout的滑动，不能单独监听子view的滑动了。

ok
