### ISSUE TITLE
ConsecutiveScrollerLayout获取ownScrollY的滑动距离不对

### ISSUE THREAD

**Issue by guochuanpei** [donkingliang/ConsecutiveScroller#238]
![image](https://user-images.githubusercontent.com/24664660/146132801-78b3cf56-7dc7-45cd-8a7c-47b8413557f4.png)
如图  “动态计算的高度”那行日志是我ConsecutiveScrollerLayout布局里面包裹的rv的高度，在rv没滑出屏幕的时候ownScrollY的距离是正确的，但是rv滑出屏幕后，ownScrollY的距离就会变得不正确 。

**Comment by donkingliang** [comment]
ownScrollY是所有子view的scrollY+ConsecutiveScrollerLayout的scrollY。而rv如果item的高度不是固定的，那么它的scrollY也是不确定的，所以如果你rv的item高度不固定，ownScrollY也是不正确的。

另外，你动态计算的rv高度是怎么计算的？

**Comment by guochuanpei** [comment]
感谢回复
我的页面里rv是初始加载五张图片，点击查看更多会把其余的三十几张图片加载出来，动态计算高度是这么计算的
![image](https://user-images.githubusercontent.com/24664660/146138434-5f73a3ac-d9bf-40d5-aa76-9715ad3719dd.png)

**Comment by guochuanpei** [comment]
> ownScrollY是所有子view的scrollY+ConsecutiveScrollerLayout的scrollY。而rv如果item的高度不是固定的，那么它的scrollY也是特殊的，所以如果你的item高度不固定，自己的ScrollY也是不正确的。
> 
> 另外，你动态计算的rv高度是怎么计算的？

**Comment by guochuanpei** [comment]
就是说如果在rv里不固定item高度的话 那么scrollY的值在把rv滑出去也是不能拿到正确的，由于我们列表里的图片高度不确定 所以item里只能写成wrap_content  这种情况下有什么办法能拿到准确的scrollY值吗？

**Comment by donkingliang** [comment]
> 就是说如果在rv里不固定item高度的话 那么scrollY的值在把rv滑出去也是不能拿到正确的，由于我们列表里的图片高度不确定 所以item里只能写成wrap_content 这种情况下有什么办法能拿到准确的scrollY值吗？

无法获取准确的scrollY，因为rv的item复用机制，它只会加载出现在屏幕中的item，然后根据这几个item的高度平均值*item个数来估算自己的列表总高度和滑动偏移，所以它本身就不是一个确定值。只有当每一个item高度一样时，这个估值才是正确的

**Comment by guochuanpei** [comment]
> > 就是说如果在rv里不固定item高度的话 那么scrollY的值在把rv滑出去也是不能拿到正确的，由于我们列表里的图片高度不确定 所以item里只能写成wrap_content 这种情况下有什么办法能拿到准确的scrollY值吗？
> 
> 无法获取准确的scrollY，因为rv的item复用机制，它只会加载出现在屏幕中的item，然后根据这几个item的高度平均值*item个数来估算自己的列表总高度和滑动偏移，所以它本身就不是一个确定值。只有当每一个item高度一样时，这个估值才是正确的

感谢大佬回复，我用了判断控件显示隐藏的偏门解决了。。。。
