### ISSUE TITLE
关于IConsecutiveScroller接口的2个方法的含义

### ISSUE THREAD

**Issue by luoxiong94** [donkingliang/ConsecutiveScroller#240]
// 返回当前需要滑动的下级view。在一个时间点里只能有一个view可以滑动。
public View getCurrentScrollerView(View containerView);

 //  返回所有可以滑动的子view。由于ConsecutiveScrollerLayout允许它的子view包含多个可滑动的子view，所以返回一个view列表。
public List<View> getScrolledViews(View containerView);

我其实不太明白这2个方法具体的作用场景,

    <MyFrameLayout
        android:id="@+id/flContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <FrameLayout
            android:id="@+id/llEmpty"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </FrameLayout>

    </MyFrameLayout>

请问 如果 MyFrameLayout 实现了IConsecutiveScroller 接口, 那么getCurrentScrollerView 和 getScrolledViews 分别传什么啊?

**Comment by donkingliang** [comment]
传MyFrameLayout里需要滑动的那个子view。比如例子中的RecyclerView。

getScrolledViews 返回的是需要滑动的全部子view。MyFrameLayout里可以包含多个可以滑动的view。

getCurrentScrollerView 返回的是当前需要滑动的view，在一个时间点里，只能有一个view响应滑动，这需要自己处理什么时候滑动那个view。
