### ISSUE TITLE
关于让Fragment中的View吸顶的问题

### ISSUE THREAD

**Issue by luoxiong94** [donkingliang/ConsecutiveScroller#244]
Activity根布局ConsecutiveScrollerLayout 嵌套TextView、ConsecutiveViewPager，TextView吸顶。ConsecutiveViewPager里面是两个Fragment，Fragment里面又是ConsecutiveScrollerLayout 嵌套TextView。此时如何让Fragment里面的TextView吸顶在Activity的TextView的下面？

**Comment by donkingliang** [comment]
设置Fragment里面的TextView吸顶。并且，如果Activity的ConsecutiveScrollerLayout设置autoAdjustHeightAtBottomView属性。或者Fragment里的ConsecutiveScrollerLayout设置adjustHeightOffset。这样Fragment的TextView就不会被Activity的TextView挡住

[adjustHeightOffset](https://github.com/donkingliang/ConsecutiveScroller/wiki/2.%E5%B8%83%E5%B1%80%E5%90%B8%E9%A1%B6#autoadjustheightatbottomview%E5%B1%9E%E6%80%A7%E5%92%8Cadjustheightoffset%E5%B1%9E%E6%80%A7)

**Comment by luoxiong94** [comment]
谢谢

**Comment by luoxiong94** [comment]
可以让Activity 和 Fragment的 TextView 同时吸顶吗?

**Comment by luoxiong94** [comment]
谢谢回复.
