### ISSUE TITLE
通过rv获取findFirstVisibleItemPosition 不准了

### ISSUE THREAD

**Issue by luoxiong94** [donkingliang/ConsecutiveScroller#247]
如果1个页面, 嵌套了3个rv , 依次是 rv1 , rv2,  rv3,  如果当前屏幕显示的item是 rv2 的时候,  通过rv1 获取 findFirstVisibleItemPosition 等方法都不准了,  因为rv1 没在屏幕内了,  返回的应该是-1 才对, 但实际还是最后1次rv1显示的postion,  请问有啥办法获取rv1当前可见item的position吗?

**Comment by huangssh** [comment]
请问怎么解决的？遇到同样的问题RecyclerView还没有展示第一页的item已经被视为可见项，按道理还没有滚到recyclerView, findFirstVisibleItemPosition应该返回-1的。
