### ISSUE TITLE
给GridlayoutManager设置倒序，会无法滑动出去

### ISSUE THREAD

**Issue by Matchas-xiaobin** [donkingliang/ConsecutiveScroller#260]
给GridlayoutManager通过按钮点击，修改 reverseLayout = true，然后就会发现，滑动限定在了这个recyclerView里面了，如果这个recyclerView高度填充了屏幕高度，那么就会导致：当这个列表滑动到它的顶部了，继续滑没有作用，当这个列表滑动到底部了，也会无法继续滑动。如果这个recyclerView的高度没有充满屏幕，比如只有一半的屏幕高度，并且，距离滑动到这个列表还有一定的距离，这个时候，是无法手指从上往下滑动，但是可以从下往上滑动。大概就这样子，如果有需要，我可以去录个视频。

**Comment by donkingliang** [comment]
已修复，你更新最新版试一下

**Comment by Matchas-xiaobin** [comment]
已更新，问题已解决，谢谢！
