### ISSUE TITLE
[建议] 加个限定子控件最大高度的方法

### ISSUE THREAD

**Issue by Matchas-xiaobin** [donkingliang/ConsecutiveScroller#262]
具体来讲就是，放了一个recyclerView，高度是wrap_content，但是我希望这个recyclerview的高度，最大不超过一个特定的高度，这个功能可以设定为需要配合layout_isConsecutive="false"这个属性一起用才能生效。
然后就是，如果这个限定高度，可以选择设置固定的最大高度，或者设为这个父控件的高度的百分比高度就更好了（最大还是和目前一样，不能超过父控件的高度），方便兼容一些大屏设备，和横竖屏切换效果。

**Comment by donkingliang** [comment]
一般来说，限定最大/最小宽高，应该是在View实现的功能的，具体就是重写onMeasure等相关方法。而不应该由父布局限定，所以你应该写一个能指定最大高度的recyclerView

**Comment by Matchas-xiaobin** [comment]
我觉得既然能让一个自适应高度的rv能限定在不超过父控件的高度内，那么把这个限制开放个自定义值应该是可以的，这样就不用专门为了这个实现去重写一个rv。
