### ISSUE TITLE
ConsecutiveScrollerLayout+ConsecutiveViewPager2,ConsecutiveViewPager2的高度无法自适应，可以帮忙看看吗

### ISSUE THREAD

**Issue by yangqb** [donkingliang/ConsecutiveScroller#264]
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
            android:id="@+id/scrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/color_0E0E0E"
            android:scrollbars="none">
 <androidx.core.widget.NestedScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
<LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="vertical">
 </LinearLayout>
            </androidx.core.widget.NestedScrollView>
<com.donkingliang.consecutivescroller.ConsecutiveViewPager2
                android:id="@+id/viewPager"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="#1F1F1F" />
        </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

下面是fragment的布局
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#1F1F1F">

        </androidx.recyclerview.widget.RecyclerView>
    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

我有四个fragment每个高度都不一样，但是实际情况是一样的。

**Comment by donkingliang** [comment]
ViewPager和ViewPager2本来就是不能自适应高度的

**Comment by yangqb** [comment]
> ViewPager和ViewPager2本来就是不能自适应高度的

我修改你的demo中MyFragment的recyclerview的数据可以做到高度不一样呢

**Comment by yangqb** [comment]
> ViewPager和ViewPager2本来就是不能自适应高度的

是应为我的MyFragment的根布局不是ConsecutiveScrollerLayout吗？我的Fragment继承的是封装后的

**Comment by donkingliang** [comment]
我说的不是高度自适应吧，是你的布局超出一屏就没法滑动了吧。Fragment的根布局需要是ConsecutiveScrollerLayout或者RecyclerView\ScrollView等可以滑动的控件，才能滑动的

**Comment by yangqb** [comment]
> 我说的不是高度自适应吧，是你的布局超出一屏就没法滑动了吧。Fragment的根布局需要是ConsecutiveScrollerLayout或者RecyclerView\ScrollView等可以滑动的控件，才能滑动的

嗯嗯，我刚刚自己也试了，确实是更布局不是ConsecutiveScrollerLayout导致的

**Comment by yangqb** [comment]
有个新的问题，我的ConsecutiveScrollerLayout+ConsecutiveViewPager2是没有吸顶view的，当我滑动一段距离，切换ConsecutiveViewPager2中的每个fragment，每个fragmnet滑动距离都是一样的。

**Comment by yangqb** [comment]
有个新的问题，我的ConsecutiveScrollerLayout+ConsecutiveViewPager2是没有吸顶view的，当我滑动一段距离，切换ConsecutiveViewPager2中的每个fragment，每个fragmnet滑动距离都是一样的。

**Comment by yangqb** [comment]
有个新的问题，我的ConsecutiveScrollerLayout+ConsecutiveViewPager2是没有吸顶view的，当我滑动一段距离，切换ConsecutiveViewPager2中的每个fragment，每个fragmnet滑动距离都是一样的。

**Comment by yangqb** [comment]
有个新的问题，我的ConsecutiveScrollerLayout+ConsecutiveViewPager2是没有吸顶view的，当我滑动一段距离，切换ConsecutiveViewPager2中的每个fragment，其他fragmnet的内容也移动了一段距离。
