### ISSUE TITLE
设置下沉模式添加悬浮偏移会占据顶部空间

### ISSUE THREAD

**Issue by rayzeng0221** [donkingliang/ConsecutiveScroller#270]
页面设置了沉浸式状态栏，设置了下沉模式，然后吸顶View会跑到状态栏去，设置了吸顶偏移后直接占据了下沉布局的状态栏空间，我想要的只是吸顶View下移到状态栏下面  而不是连下沉布局也下移到状态栏下面了。

**Comment by donkingliang** [comment]
下沉布局也是一个吸顶view，也会受吸顶偏移影响

**Comment by rayzeng0221** [comment]
那要怎样才能实现我那样的效果？

**Comment by donkingliang** [comment]
你可以不用吸顶偏移，比如在布局顶部设置一个空白透明的的吸顶View来占位状态栏空间，这个吸顶View默认是Gone的，在下沉View吸顶的时候才VISIBLE。思路大概是这样，具体你就根据自己的实际情况设置

**Comment by JokeenZhang** [comment]
能设置吸顶View始终悬浮，而不会占用一个独立的空间吗？类似如下效果

![Snipaste_2023-02-10_10-52-32](https://user-images.githubusercontent.com/33319484/217991434-bcd82152-dcf5-47cb-b7c5-0e78d63afaf9.png)

**Comment by donkingliang** [comment]
> 能设置吸顶View始终悬浮，而不会占用一个独立的空间吗？类似如下效果
> 
> ![Snipaste_2023-02-10_10-52-32](https://user-images.githubusercontent.com/33319484/217991434-bcd82152-dcf5-47cb-b7c5-0e78d63afaf9.png)

放在顶部不就可以了吗

**Comment by JokeenZhang** [comment]
我想要的效果是，进入时，吸顶view不显示（alpha为0），随着滑动逐渐显示，并且一直悬浮。现在是在进入页面后，会有一个占位空间，也就是吸顶view自己，因为吸顶view的透明度为0，所以显示默认的背景色
