### ISSUE TITLE
设置margin无效果

### ISSUE THREAD

**Issue by ZhangAnLei** [donkingliang/ConsecutiveScroller#28]

**Comment by donkingliang** [comment]
是的，我在文档上有说了，不支持子view的margin，推荐子View间的间距可以通过Space设置。

**Comment by ZhangAnLei** [comment]
作者你好，我现在遇到的需求是这样的怎么设置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "donkingliang"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 下午5:32
收件人: "donkingliang/ConsecutiveScroller"<ConsecutiveScroller@noreply.github.com&gt;; 
抄送: "深驻我心"<2393394550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [donkingliang/ConsecutiveScroller] 设置margin无效果 (#28)





 
是的，我在文档上有说了，不支持子view的margin，推荐子View间的间距可以通过Space设置。

**Comment by donkingliang** [comment]
用Space代替你的margin边距。比如设置10dp的边距，可以这样
<Space
        android:layout_width="0dp"
        android:layout_height="10dp"/>

**Comment by donkingliang** [comment]
<Space
        android:layout_width="0dp"
        android:layout_height="10dp"/>

**Comment by donkingliang** [comment]
`<Space
        android:layout_width="0dp"
        android:layout_height="10dp"/>`

**Comment by ZhangAnLei** [comment]
您好，就是我现在的需求是这样的，请问下这种需求可以实现吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"donkingliang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上6:11
收件人:&nbsp;"donkingliang/ConsecutiveScroller"<ConsecutiveScroller@noreply.github.com&gt;;
抄送:&nbsp;"深驻我心"<2393394550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donkingliang/ConsecutiveScroller] 设置margin无效果 (#28)





 
<Space android:layout_width="0dp" android:layout_height="10dp"/&gt;

**Comment by donkingliang** [comment]
我没有看到你发的是什么？好像github有的问题。你发我QQ吧 1043214265
