### ISSUE TITLE
SmartRefreshLayout + CoordinatorLayout + ConsecutiveScrollerLayout 来回滑动RecyclerView 列表item抖动

### ISSUE THREAD

**Issue by qinhongfei** [donkingliang/ConsecutiveScroller#287]
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.scwang.smart.refresh.layout.SmartRefreshLayout
            android:id="@+id/cart_common_refresh"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_constraintBottom_toTopOf="@+id/cart_common_bottom_cl"
            app:layout_constraintTop_toTopOf="parent">

            <androidx.coordinatorlayout.widget.CoordinatorLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <com.google.android.material.appbar.AppBarLayout
                    android:id="@+id/cart_common_sift_abl"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/resource_transparent"
                    android:orientation="vertical"
                    app:elevation="0dp"
                    app:layout_behavior="com.tianma.base.widget.behavior.AppBarLayoutBehavior">

                    <androidx.constraintlayout.widget.ConstraintLayout
                        android:id="@+id/cart_common_sift_cl"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="15dp"
                        app:layout_scrollFlags="scroll|enterAlways">

                        <TextView
                            android:id="@+id/cart_common_cut_prices"
                            android:layout_width="69dp"
                            android:layout_height="wrap_content"
                            android:layout_marginStart="15dp"
                            android:background="@drawable/shape_18dp_fffffff_bg"
                            android:paddingVertical="4dp"
                            android:paddingStart="19dp"
                            android:paddingEnd="6dp"
                            android:text="@string/goods_cut_prices"
                            android:textColor="@color/resource_black"
                            android:textSize="@dimen/sp_14"
                            app:layout_constraintStart_toStartOf="parent"
                            app:layout_constraintTop_toTopOf="parent" />

                        <TextView
                            android:id="@+id/cart_common_frequently_purchased"
                            android:layout_width="69dp"
                            android:layout_height="28dp"
                            android:layout_marginStart="15dp"
                            android:background="@drawable/shape_18dp_fffffff_bg"
                            android:paddingVertical="4dp"
                            android:paddingStart="19dp"
                            android:paddingEnd="6dp"
                            android:text="@string/goods_frequently_purchased"
                            android:textColor="@color/resource_black"
                            android:textSize="@dimen/sp_14"
                            app:layout_constraintStart_toEndOf="@+id/cart_common_cut_prices"
                            app:layout_constraintTop_toTopOf="parent" />
                    </androidx.constraintlayout.widget.ConstraintLayout>
                </com.google.android.material.appbar.AppBarLayout>

                <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
                    android:id="@+id/cart_common_csl"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginTop="10dp"
                    app:layout_behavior="@string/appbar_scrolling_view_behavior">

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/cart_common_rlv"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:overScrollMode="never" />

                    <androidx.legacy.widget.Space
                        android:layout_width="0dp"
                        android:layout_height="15dp" />

                    <TextView
                        android:id="@+id/cart_common_recommend_tv"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:drawableStart="@mipmap/recommend_left_iv"
                        android:drawableEnd="@mipmap/recommend_right_iv"
                        android:drawablePadding="10dp"
                        android:text="@string/goods_cart_recommend_label1"
                        app:layout_align="CENTER" />

                    <androidx.legacy.widget.Space
                        android:id="@+id/cart_common_recommend_space"
                        android:layout_width="0dp"
                        android:layout_height="15dp" />

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/cart_common_recommend_rlv"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:overScrollMode="never" />

                </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
            </androidx.coordinatorlayout.widget.CoordinatorLayout>
        </com.scwang.smart.refresh.layout.SmartRefreshLayout>

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/cart_common_bottom_cl"
            android:layout_width="match_parent"
            android:layout_height="64dp"
            android:background="@color/white"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">

            <CheckBox
                android:id="@+id/cart_common_all_select_cb"
                style="@style/CustomCheckboxTheme"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="18dp"
                android:layout_marginTop="13dp"
                app:layout_constraintBaseline_toBaselineOf="@+id/cart_common_bottom_tv1"
                app:layout_constraintStart_toStartOf="parent" />

            <TextView
                android:id="@+id/cart_common_bottom_tv1"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="8dp"
                android:text="@string/shopcart_tv1"
                android:textColor="@color/black"
                android:textSize="16sp"
                app:layout_constraintBaseline_toBaselineOf="@+id/cart_common_del"
                app:layout_constraintStart_toEndOf="@id/cart_common_all_select_cb"
                app:layout_goneMarginBaseline="-26dp" />

            <TextView
                android:id="@+id/cart_common_select_num_tv"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="3dp"
                android:layout_marginBottom="9dp"
                android:text="(已选0个)"
                android:textColor="@color/text_color_2"
                android:textSize="12sp"
                android:visibility="invisible"
                app:layout_constraintStart_toStartOf="@id/cart_common_bottom_tv1"
                app:layout_constraintTop_toBottomOf="@id/cart_common_bottom_tv1" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/cart_common_center_cl"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="70dp"
                app:layout_constraintBottom_toBottomOf="@+id/cart_common_bt"
                app:layout_constraintStart_toEndOf="@id/cart_common_bottom_tv1"
                app:layout_constraintTop_toTopOf="@+id/cart_common_bt">

                <TextView
                    android:id="@+id/cart_common_tv2"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="@string/shopcart_tv2"
                    android:textColor="@color/black"
                    android:textSize="@dimen/sp_12"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/cart_common_tv3"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="2dp"
                    android:text="@string/rmb_symbol"
                    android:textColor="@color/primary_color"
                    android:textSize="@dimen/sp_12"
                    app:layout_constraintBottom_toBottomOf="@id/cart_common_tv2"
                    app:layout_constraintStart_toEndOf="@id/cart_common_tv2" />

                <TextView
                    android:id="@+id/cart_common_all_money_tv"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="2dp"
                    android:text="0.00"
                    android:textColor="@color/primary_color"
                    android:textSize="@dimen/sp_12"
                    app:layout_constraintBottom_toBottomOf="@id/cart_common_tv2"
                    app:layout_constraintStart_toEndOf="@id/cart_common_tv3" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginBottom="3dp"
                    android:text="@string/shopcart_tv4"
                    android:textColor="@color/common_tv_grey_color"
                    android:textSize="@dimen/sp_12"
                    app:layout_constraintStart_toStartOf="@id/cart_common_tv2"
                    app:layout_constraintTop_toBottomOf="@id/cart_common_all_money_tv" />

            </androidx.constraintlayout.widget.ConstraintLayout>

            <TextView
                android:id="@+id/cart_common_clean"
                android:layout_width="80dp"
                android:layout_height="28dp"
                android:layout_marginEnd="10dp"
                android:drawableStart="@mipmap/cart_clean"
                android:gravity="center_vertical"
                android:paddingLeft="4dp"
                android:text="@string/goods_fast_clean"
                android:textColor="@color/primary_color"
                android:textSize="@dimen/sp_14"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="@+id/cart_common_del"
                app:layout_constraintEnd_toStartOf="@+id/cart_common_add_collect" />

            <Button
                android:id="@+id/cart_common_add_collect"
                android:layout_width="80dp"
                android:layout_height="28dp"
                android:layout_marginEnd="10dp"
                android:background="@drawable/shape_14dp_outline_f2f0f0"
                android:text="@string/goods_add_collect"
                android:textColor="@color/resource_black"
                android:textSize="@dimen/sp_14"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="@+id/cart_common_del"
                app:layout_constraintEnd_toStartOf="@+id/cart_common_del" />

            <Button
                android:id="@+id/cart_common_del"
                android:layout_width="80dp"
                android:layout_height="28dp"
                android:layout_marginEnd="10dp"
                android:layout_marginBottom="26dp"
                android:background="@drawable/shape_14dp_outline_f2f0f0"
                android:text="@string/edit_finish_tv1"
                android:textColor="@color/resource_black"
                android:textSize="@dimen/sp_14"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent" />

            <Button
                android:id="@+id/cart_common_bt"
                android:layout_width="112dp"
                android:layout_height="36dp"
                android:layout_marginEnd="10dp"
                android:background="@drawable/shape_16dp_primary_radiu"
                android:text="@string/shopcart_tv3"
                android:textColor="@color/white"
                android:textSize="@dimen/sp_16"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
        </androidx.constraintlayout.widget.ConstraintLayout>

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
第一次请求数据从上到下滑动没问题，当滑到顶部再次往下滑动时候会出现 第二个 recycleview的子item抖动，请问是ConsecutiveScrollerLayout 导致 recycleview复用机制不生效吗？

**Comment by donkingliang** [comment]
如果滑动抖动是因为item高度不一致，你可以试一下这个：https://github.com/donkingliang/ConsecutiveScroller/issues/255
或者看这个：
![image](https://user-images.githubusercontent.com/5499532/228123077-55a34ef7-866f-45c6-ad87-7245da305403.png)

**Comment by qinhongfei** [comment]
是的，第二个recycleview是使用了瀑布流布局，它的子项高度会动态改变

**Comment by qinhongfei** [comment]
您好，我是去除了id为cart_common_recommend_rlv的RecyclerView的瀑布流并把子项高度设置为一样高，还是会有来回滑动后页面逐渐抖动的现象，他看起来像是没有执行RecyclerView的复用机制。id为cart_common_recommend_rlv的RecyclerView是搭配谷歌的paging3一起使用的
