### ISSUE TITLE
ConsecutiveScrollerLayout 子控件的visibility失效

### ISSUE THREAD

**Issue by qinhongfei** [donkingliang/ConsecutiveScroller#289]
ConsecutiveScrollerLayout 子控件的visibility失效，代码如下：

<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
                    android:id="@+id/cart_common_csl"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginTop="10dp"
                    app:layout_behavior="@string/appbar_scrolling_view_behavior">

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/cart_common_rlv"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:overScrollMode="never"
                        android:tag="InterceptRequestLayout" />

                    <androidx.legacy.widget.Space
                        android:layout_width="0dp"
                        android:layout_height="15dp" />

                    <LinearLayout
                        android:id="@+id/cart_common_recommend_load"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal"
                        android:gravity="center_vertical"
                        app:layout_align="CENTER">

                        <ImageView
                            android:id="@+id/cart_common_recommend_load_iv"
                            android:layout_width="15dp"
                            android:layout_height="15dp" />

                        <TextView
                            android:id="@+id/cart_common_recommend_load_tv"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center_horizontal"
                            android:layout_marginLeft="6dp"
                            android:text="@string/goods_cart_recommend_label2"
                            android:textSize="14sp"
                            android:textColor="#111111" />
                    </LinearLayout>

                    <TextView
                        android:id="@+id/cart_common_recommend_tv"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:drawableStart="@mipmap/recommend_left_iv"
                        android:drawableEnd="@mipmap/recommend_right_iv"
                        android:drawablePadding="10dp"
                        android:text="@string/goods_cart_recommend_label1"
                        android:visibility="gone"
                        app:layout_align="CENTER"
                        />

                    <androidx.legacy.widget.Space
                        android:id="@+id/cart_common_recommend_space"
                        android:layout_width="0dp"
                        android:layout_height="15dp" />

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/cart_common_recommend_rlv"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:overScrollMode="never" />

                </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
我测试是可以的。没有复现你的问题
