### ISSUE TITLE
子Veiw不满一屏的时候，也能滑动。

### ISSUE THREAD

**Issue by liupengchao92** [donkingliang/ConsecutiveScroller#29]
发现ConsecutiveScrollerLayout设置layout_height为match_parent，嵌套子Veiw的内容不满一屏的时候，控件也可以滑动，而且还能滑出屏幕。layout_height设为wrap_content时候，子View上面会出现一大片空白强制填满屏幕，键盘弹出空白区域就没了，键盘消失后又有了，好像键盘会影响ConsecutiveScrollerLayout的滑动，遇到这种问题了吗？

**Comment by donkingliang** [comment]
这个问题已经解决啦，你用的不是最新的版本吧

**Comment by liupengchao92** [comment]
我更新了一下，的确可以了。谢谢了
