### ISSUE TITLE
初始化的时候RV的复用机制会失效

### ISSUE THREAD

**Issue by tanlei02** [donkingliang/ConsecutiveScroller#294]
数据一次性全部绑定到视图上
![image](https://github.com/donkingliang/ConsecutiveScroller/assets/128780773/9d93ed8a-4624-4cbc-9e4d-3e90cc1f9c29)

**Comment by donkingliang** [comment]
ConsecutiveScroller不会影响RV的复用机制，初始化时只会加载一屏幕的item。你的RV是否嵌套了其他滑动布局，或者其他原因影响的

**Comment by tanlei02** [comment]
> ConsecutiveScroller不会影响RV的复用机制，初始化时只会加载一屏幕的item。你的RV是否嵌套了其他滑动布局，或者其他原因影响的

跑的demo就是你给的demo，你可以试一下

**Comment by donkingliang** [comment]
你打印一下position。你打印的log应该是多个RV，每个RV加载一屏数据，所以有那么多

**Comment by tanlei02** [comment]
> 你打印一下position。你打印的log应该是多个RV，每个RV加载一屏数据，所以有那么多

了解你的意思了，感谢
