### ISSUE TITLE
如果给WebView设置了固定高度，会有问题。

### ISSUE THREAD

**Issue by SherlockGougou** [donkingliang/ConsecutiveScroller#3]
如题。

**Comment by SherlockGougou** [comment]
另外一个问题：我app内部使用的WebView是腾讯的X5内核。就算我设置高度为match，他也是有问题的。请问这个我需要如何更改源码来兼容呢？

**Comment by donkingliang** [comment]
如果把WebView设置固定高度而不是match，那么应该让WebView自己滑动，而不是跟着父布局以前滑动，否则会让布局显示断层。设置app:layout_isConsecutive="false"可以让WebView滑动。

对于腾讯X5的WebView，我看了一下他的源码，发现他是一个FrameLayout嵌套WebView，重写他的scrollBy方法，让它把滑动事件交给它的WebView即可。我这文档上添加这这个说明，你可以去看一下。

**Comment by SherlockGougou** [comment]
好的，谢谢回复！
