### ISSUE TITLE
不够流畅，有卡顿的情况

### ISSUE THREAD

**Issue by skywolfwen** [donkingliang/ConsecutiveScroller#30]
ConsecutiveScroller 中放入两个 RecyclerView，使用的都是多 itemType（因为padding的问题所以才使用两个RecyclerView），然后滑动到某个 item 就会卡，整体的滑动体验也不是很好

**Comment by donkingliang** [comment]
卡顿有没有可能是列表处理不好引起的。你不用ConsecutiveScroller列表滑动是流畅的吗？

**Comment by skywolfwen** [comment]
> 卡顿有没有可能是列表处理不好引起的。你不用ConsecutiveScroller列表滑动是流畅的吗？

嗯，用单个的 RecyclerView 是很流畅的，只是设计稿上给的样式就比较不容易实现了

**Comment by donkingliang** [comment]
更新的新版本对滑动做了优化
