### ISSUE TITLE
吸顶布局，能否设置点击重新滚动回到当前的位置？

### ISSUE THREAD

**Issue by Alexxiaopang** [donkingliang/ConsecutiveScroller#31]
比如，子布局分别是ABCD，B设置了吸顶，这时候下拉了到了D，能否点击一下B重新滚回到B；
这边用smoothScrollToChild(C)，但是吸顶布局B会盖住C的一部分，能否一下子会到C的全部？

**Comment by donkingliang** [comment]
你不能smoothScrollToChild(B)吗？

**Comment by Alexxiaopang** [comment]
smoothScrollToChild(B)不执行，没反应

**Comment by donkingliang** [comment]
smoothScrollToChild往回滚的时候有bug，这一些情况下滑动不起作用。这个bug已经修复了。但是我还没有更新版本。你可以先下载代码使用。

**Comment by donkingliang** [comment]
我可能过两个再发版本，因为新增了一些功能和优化还在测试。

**Comment by Alexxiaopang** [comment]
好的，那我先clone版本，本地依赖，谢了
