### ISSUE TITLE
支持 RecyclerView 子View拖动

### ISSUE THREAD

**Issue by JiayuanChan** [donkingliang/ConsecutiveScroller#33]
ConsecutiveScroller 嵌套多个 RecyclerView  ，其中的某一个可以实现item拖动吗？

**Comment by donkingliang** [comment]
可以横向滑动，但是不能上下拖动。

**Comment by donkingliang** [comment]
你是使用ItemTouchHelper吗？我更新了新版本，或许可以支持，我也没有测试过，因为我这次更新是滑动事件的优化处理，所以没有去考虑对ItemTouchHelper的支持。

**Comment by JiayuanChan** [comment]
是的，使用 ItemTouchHelper ，我试了一下可以，但是如果RecyclerView 撑满全屏的时候，拖动到底部、顶部边界的时候，滚动有点问题

**Comment by donkingliang** [comment]
嗯，因为没有对ItemTouchHelper做支持。ItemTouchHelper拖动时的滚动可能跟ConsecutiveScrollerLayout的滑动方式有点冲突。

**Comment by JiayuanChan** [comment]
后期有没有计划做这个的支持呢？？

**Comment by donkingliang** [comment]
目前没有，毕竟这种需求的应用是少数。以后可能会支持。

**Comment by JiayuanChan** [comment]
结合 CollapsingToolbarLayout 使用时，CollapsingToolbarLayout 不起作用

**Comment by donkingliang** [comment]
是的。不能跟CollapsingToolbarLayout一起使用
