### ISSUE TITLE
这个库是不是就不支持recyleview的加载更多了，我配合BaseQuickAdapter的加载更多使用发现只会生效一次

### ISSUE THREAD

**Issue by 643063150** [donkingliang/ConsecutiveScroller#34]
这个库是不是就不支持recyleview的加载更多了，我配合BaseQuickAdapter的加载更多使用发现只会生效一次，后面就不会生效了

**Comment by donkingliang** [comment]
可以配合SmartRefreshLayout等第三方的加载库使用。SmartRefreshLayout嵌套ConsecutiveScrollerLayout

**Comment by 643063150** [comment]
是我写的方式有问题，不好意思哈，是可以的
