### ISSUE TITLE
界面显示不完整

### ISSUE THREAD

**Issue by Zhao187** [donkingliang/ConsecutiveScroller#35]
布局里面嵌套recyclerview,recyclerview数据是后台返回的，界面显示不完整

**Comment by Zhao187** [comment]
后面内容看不到

**Comment by Zhao187** [comment]
NestedScrollView 就没有一点问题可以完整展示界面

**Comment by donkingliang** [comment]
界面显示不完整是指界面滑动不到底部吗？你使用的版本是什么？

**Comment by Zhao187** [comment]
使用版本1.5.1  滑动到一半就不能够滑动了，到达不了底部，布局里面添加了recycleview,recycleview数据是从网络动态获取的,滑动不到底部,但是不用recycleview就没有问题.

**Comment by Zhao187** [comment]
麻烦解决一下项目中用了一下发现报错了

**Comment by donkingliang** [comment]
什么报错？能提供一下报错信息吗？

**Comment by Zhao187** [comment]
我说的报错是界面显示不全问题，无法向下滚动，滑动不到底部吗

**Comment by donkingliang** [comment]
能加一下我QQ吗？我想了解一下具体的情况，因为我这边无法复现。1043214265
