### ISSUE TITLE
不接入网络请求都没有闪烁，接入之后闪烁很严重，大概率

### ISSUE THREAD

**Issue by Alexxiaopang** [donkingliang/ConsecutiveScroller#36]

**Comment by donkingliang** [comment]
你好，你说的闪烁是什么？接入网络请求是做了什么操作？

**Comment by Alexxiaopang** [comment]
先说一下我的布局，根布局是LinearLayout，因为头部顶部还有其他的东西要处理，不需要滑动
然后是SmartRefreshLayout包裹的ConsecutiveScrollerLayout；

ConsecutiveScrollerLayout里面从上到下分别是webview   + 多个 ConstraintLayout（activity根据网络请求会动态隐藏） +  RecyclerView

然后就是在activity里面请求网络，webview加载数据，RecyclerView加载数据，ConstraintLayout动态显隐藏

其他没做什么操作了，这都是正常的加载然后显示，对了，webview加载的是富文本，用的是
loadDataWithBaseURL

**Comment by Alexxiaopang** [comment]
我说的闪烁是整个页面狂闪，

**Comment by donkingliang** [comment]
你使用的是最新的1.5.1或者2.5.0版本吗?

**Comment by Alexxiaopang** [comment]
在你上传代码的前一天，我clone下来用的，因为之前的有滚动bug，clone的代码没有滚动bug

还有请教一个问题，能否监听是否某个view滚动到顶部了，或者某个view的坐标

**Comment by donkingliang** [comment]
你试一下最新的代码是否有你说的问题。监听某个view滚动到顶部，你可以使用findFirstVisibleView()获取当前显示的第一个view来判断。
`scrollerLayout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY) {
                // 获取显示的第一个view
              View view = scrollerLayout.findFirstVisibleView();
            }
        });`

**Comment by Alexxiaopang** [comment]
闪烁已经解决了，我显示隐藏动态都调用checkLayoutChange，就不会闪烁了
不支持CoordinatorLayout 的appbar_scrolling_view_behavior 的联动么？

**Comment by donkingliang** [comment]
不支持CoordinatorLayout的联动，两者的滑动处理方式不同

**Comment by Pro-Z** [comment]
> 闪烁已经解决了，我显示隐藏动态都调用checkLayoutChange，就不会闪烁了
> 不支持CoordinatorLayout 的appbar_scrolling_view_behavior 的联动么？

怎么解决闪烁的?我也遇到这个问题了
