### ISSUE TITLE
在嵌套滑动的过程中，如果子view的n个子view不想嵌套滑的话，有什么可行的办法么

### ISSUE THREAD

**Issue by Lemniscate317** [donkingliang/ConsecutiveScroller#37]

**Comment by donkingliang** [comment]
给子view设置app:layout_isConsecutive="false"，那么这个子view和他的下级view都不会跟ConsecutiveScrollerLayout一起滑动。

**Comment by Lemniscate317** [comment]
十分感谢，新版本151是可以的

**Comment by Lemniscate317** [comment]
在fragment中其实有点问题。activity中用framelayout承接fragment，在fragment的布局中添加app:layout_isConsecutive="false"，如果判定到是横向滑，那么再竖向滑是不会动的。如果是判定到竖向滑，那么即使添加了app:layout_isConsecutive="false"这个flag，其实还是无效的

**Comment by donkingliang** [comment]
layout_isConsecutive这个设置只能设置在ConsecutiveScrollerLayout的直接子view，设置到其他层级的view是无效的。

ConsecutiveScrollerLayout不支持一个事件序列可以横行和竖向滑动，所以判断为一个方向滑动，另一个方向是不能滑动的。这是ConsecutiveScrollerLayout本身的设计。
