### ISSUE TITLE
可滑动的View是自定义子View中的子View，页面只能显示一屏范围，有什么解决方案吗？

### ISSUE THREAD

**Issue by Leelion96** [donkingliang/ConsecutiveScroller#38]
比如首页为Tablayout+ViewPager，ViewPager内嵌套A和B两个页面，A的页面还是为TabLayout + ViewPager, B为RecyclerView.
首页的ViewPager继承Iconsecutive接口后可以正常的显示及滑动B页面，但A页面就只能显示一屏的范围。有办法获取到子View的子View作为滑动View吗？ 
还有一个小点是，sticky粘滞是只能在父布局中实现吗，比如想要页面A中的tablayout粘滞，是否只能另想办法了？
问题有点多，希望大佬能看一哈~十分感谢

**Comment by donkingliang** [comment]
在首页的ViewPager的getCurrentScrollerView和getScrolledViews方法中也可以返回A页面的ViewPager下的滑动子view，这样它就可以滑动了。但是IConsecutiveScroller接口要求滑动的控件应该跟嵌套它的子view的高度保持一致，你的页面A的ViewPager的高和首页的ViewPager高不一样，所以可能会导致ConsecutiveScrollerLayout计算滑动范围时有偏差。
sticky吸顶的view需要是ConsecutiveScrollerLayout的直接子view，不支持子view下的子view吸顶，所以做不到让A页面的TabLayout吸顶。

**Comment by Leelion96** [comment]
> 在首页的ViewPager的getCurrentScrollerView和getScrolledViews方法中也可以返回A页面的ViewPager下的滑动子view，这样它就可以滑动了。但是IConsecutiveScroller接口要求滑动的控件应该跟嵌套它的子view的高度保持一致，你的页面A的ViewPager的高和首页的ViewPager高不一样，所以可能会导致ConsecutiveScrollerLayout计算滑动范围时有偏差。
> sticky吸顶的view需要是ConsecutiveScrollerLayout的直接子view，不支持子view下的子view吸顶，所以做不到让A页面的TabLayout吸顶。

我这边首页使用了demo里的MyViewPager，确实是可以滑动的，但滑动的范围只有一屏高度，这个就是所说的计算滑动范围片偏差吗？

**Comment by donkingliang** [comment]
不是。我在demo里的MyViewPager只是一个演示的列子，但这不是通用的写法。你需要根据自己的业务去实现getCurrentScrollerView和getScrolledViews方法。比如你的例子中，getCurrentScrollerView返回的应该是A页面下的ViewPager的子view或者b页面的rv。getScrolledViews方法返回的应该是A页面下的ViewPager的子view和b页面的rv。

也就是说getCurrentScrollerView返回的是当前需要滑动的view。getScrolledViews方法返回的是所有需要滑动的view。

**Comment by Leelion96** [comment]
> 不是。我在demo里的MyViewPager只是一个演示的列子，但这不是通用的写法。你需要根据自己的业务去实现getCurrentScrollerView和getScrolledViews方法。比如你的例子中，getCurrentScrollerView返回的应该是A页面下的ViewPager的子view或者b页面的rv。getScrolledViews方法返回的应该是A页面下的ViewPager的子view和b页面的rv。
> 
> 也就是说getCurrentScrollerView返回的是当前需要滑动的view。getScrolledViews方法返回的是所有需要滑动的view。

好的，我再去研究下。谢谢大佬

**Comment by Leelion96** [comment]
重写MyViewPager的getCurrentScrollerView和getScrolledViews方法后，出现了只能滑动前两个tab的问题，后面的高度就只有一屏了，我猜是ViewPager一开始默认只加载了两个RV，后面再加载出来的就没办法同步高度了？
目前我的布局是首页Tablayout+ViewPager，两个Tab对应页面A和B，A为ViewPager，B为RV，A的内部也是RV，重写MyViewPager后我打日志能看到CurrentScrollerView是A里面的某个RV，getScrolledViews也返回了当前ViewPager加载的3个RV以及页面B的一个RV。

是不是得放弃用ViewPager嵌套ViewPager这个方案了0.0

**Comment by Leelion96** [comment]
> 不是。我在demo里的MyViewPager只是一个演示的列子，但这不是通用的写法。你需要根据自己的业务去实现getCurrentScrollerView和getScrolledViews方法。比如你的例子中，getCurrentScrollerView返回的应该是A页面下的ViewPager的子view或者b页面的rv。getScrolledViews方法返回的应该是A页面下的ViewPager的子view和b页面的rv。
> 
> 也就是说getCurrentScrollerView返回的是当前需要滑动的view。getScrolledViews方法返回的是所有需要滑动的view。

重写MyViewPager的getCurrentScrollerView和getScrolledViews方法后，出现了只能滑动前两个tab的问题，后面的高度就只有一屏了，我猜是ViewPager一开始默认只加载了两个RV，后面再加载出来的就没办法同步高度了？
目前我的布局是首页Tablayout+ViewPager，两个Tab对应页面A和B，A为ViewPager，B为RV，A的内部也是RV，重写MyViewPager后我打日志能看到CurrentScrollerView是A里面的某个RV，getScrolledViews也返回了当前ViewPager加载的3个RV以及页面B的一个RV。

是不是得放弃用ViewPager嵌套ViewPager这个方案了0.0

**Comment by donkingliang** [comment]
你是怎么实现这两个方法的，能给我看一下吗？

**Comment by Leelion96** [comment]
> 你是怎么实现这两个方法的，能给我看一下吗？

public View getCurrentScrollerView() {
        int count = getChildCount();
        for (int i = 0; i < count; i++) {
            View view = getChildAt(i);
            if (view.getX() == getScrollX()) {
                if(view instanceof SecondViewPager){
                    SecondViewPager secondViewPager = (SecondViewPager)view;
                    MyRecyclerView recyclerView = (MyRecyclerView)secondViewPager.getChildAt(secondViewPager.getCurrentItem());
                    return recyclerView;
                }else {
                    return view;
                }
            }
        }
        return this;
    }

    /**
     * 返回全部需要滑动的下级view
     * @return
     */
    @Override
    public List<View> getScrolledViews() {
        List<View> views = new ArrayList<>();
        int count = getChildCount();
        if (count > 0) {
            for (int i = 0; i < count; i++) {
                View view = getChildAt(i);
                if(view instanceof SecondViewPager){
                    SecondViewPager secondViewPager = (SecondViewPager)view;
                    for (int j = 0; j < secondViewPager.getChildCount(); j++) {
                        views.add(secondViewPager.getChildAt(i));
                    }

                }else {
                    views.add(view);
                }

            }
        } else {
            views.add(this);
        }
        return views;
    }

**Comment by Leelion96** [comment]
不过我已经在寻求其他的方式了，单ViewPager,联动两个Tablayout，快做出来了，配合大佬的库果然丝般顺滑。ViewPager嵌套的方案应该不会再采用了。

**Comment by Leelion96** [comment]
我在demo中试验成功了，到项目里初步改写，结果发现B页面那个RecyclerView在滑动的时候会闪烁··
这个RecyclerView内部包含横的RecyclerView类型的Item，但是我在demo里也模拟了多类型、RV嵌套Rv的情况，DEMO里就没问题··好奇怪

**Comment by Leelion96** [comment]
而且加到项目里之后发现滑动有点不顺畅，蛋疼- -  不过这是其他问题了，此问题我关闭了。
