### ISSUE TITLE
吸顶TabLayout后滑动到指定的View可否开放个接口加上吸顶View的高度

### ISSUE THREAD

**Issue by cs9420** [donkingliang/ConsecutiveScroller#39]
现在点击TabLayout后想滑动到指定的View但是只能滚动到指定滑动View的top，TabLayout会掩盖一部分

**Comment by donkingliang** [comment]
你知道TabLayout在吸顶，那么是肯定是可以获取TabLayout的高度的。你可以调用scrollToChild滑动指定view后再调用scrollBy滑动TabLayout的高度。
但是如果你是调用smoothScrollToChild滑动到指定的view，那么 就不能这样做了，因为smoothScrollToChild无法知道什么时候滑动完成。

**Comment by cs9420** [comment]
好的 感谢你的回复
