### ISSUE TITLE
感觉不是很跟手

### ISSUE THREAD

**Issue by skywolfwen** [donkingliang/ConsecutiveScroller#4]
之前用的RecyclerView的item的方式显示WebView,虽然不被推荐（高度只能wrap_content），但加载完成后滑动得很流畅，然后用改成用这个库，感觉滑动起来没有单纯的RecyclerView那么爽

**Comment by donkingliang** [comment]
我对滑动进行了优化，采用RecyclerView的滑动处理方式。现在的滑动应该接近于RecyclerView的体验。

**Comment by skywolfwen** [comment]
> 我对滑动进行了优化，采用RecyclerView的滑动处理方式。现在的滑动应该接近于RecyclerView的体验。

非常感谢
