### ISSUE TITLE
ViewPager中使用多Type类型的RecyclerView，fling时页面抖动闪烁

### ISSUE THREAD

**Issue by Leelion96** [donkingliang/ConsecutiveScroller#41]
使用单一Type的Rv没有问题，在多Type的Rv中，每次不同的type在attachView以及detachView的过程中，整个页面频闪。
另外还一个小问题，配合SmartRefreshLayout使用，下拉加载更多的时候，顶部Sticky的布局被整体上移了，暂时失去了粘滞的效果，这个问题有解的可能吗？

**Comment by donkingliang** [comment]
多谢反馈。ViewPager嵌套RecyclerView时确实有点问题，我后面会修复。
SmartRefreshLayout加载更多时会把布局上移，这是SmartRefreshLayout需要显示下拉尾部的处理，我们无法干预它的处理，也没有办法获取到它上移的偏移量，所以这个问题目前是解决不了的。

**Comment by Leelion96** [comment]
> 多谢反馈。ViewPager嵌套RecyclerView时确实有点问题，我后面会修复。
> SmartRefreshLayout加载更多时会把布局上移，这是SmartRefreshLayout需要显示下拉尾部的处理，我们无法干预它的处理，也没有办法获取到它上移的偏移量，所以这个问题目前是解决不了的。

了解，谢谢大佬~

**Comment by LzDocker** [comment]
@Leelion96 两种解决方式：1. xml 中解决     app:srlFooterTranslationViewId="@id/viewPager"    这样就可以了          2. 在代码中处理 Smart 没有暴露 mFooterTranslationViewId 的setter 方法，你可以继承一下增加这个方法，然后在代码中动态设置footer 影响的viewid 就可以了  
@donkingliang 很棒的库

**Comment by donkingliang** [comment]
ViewPager嵌套RecyclerView的滑动问题已解决更新。

**Comment by LzDocker** [comment]
@donkingliang 我看了一下   在多Type的Rv中，每次不同的type在attachView以及detachView的过程中，整个页面频闪。  这个问题，粗暴的把 onlayout 中的  checkLayoutChange 方法注掉好像不闪了，没发现有其他影响，你可以试试

**Comment by donkingliang** [comment]
> @donkingliang 我看了一下 在多Type的Rv中，每次不同的type在attachView以及detachView的过程中，整个页面频闪。 这个问题，粗暴的把 onlayout 中的 checkLayoutChange 方法注掉好像不闪了，没发现有其他影响，你可以试试

这个问题已经解决了的。你可以试一下新的版本，应该是没有问题了的。
