### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by Lemniscate317** [donkingliang/ConsecutiveScroller#44]
《relativelayout》
         《scrolllayout这个库》
                   《linearlayout》
                           《img》
                           《linearlayout横向》
                     《recycleview》

以上是大致的布局
为了能够在padding网上滑动的时候也能看见view，当我给scrolllayout加上clipToPadding=false。
当我往上滑的时候，发现横向linearout置顶了。应该是因为clipToPadding=false。导致某些计算有问题。

**Comment by donkingliang** [comment]
这个不是bug，因为clipToPadding=false会让布局在Padding的范围内也可见。所以横向linearlayout在paddingTop的区域时也是可见的。而scrolllayout是调节子view的滑动事件的，它不会影响子view的实际大小，所以当recycleview滑动到scrolllayout的paddingTop时，再滑动实际上就是滑动recycleview的内容，scrolllayout的内容已经滑到底了。所以横向linearlayout停留在paddingTop的区域。

**Comment by Lemniscate317** [comment]
了解了
