### ISSUE TITLE
webview和其上的textview

### ISSUE THREAD

**Issue by 317764920** [donkingliang/ConsecutiveScroller#45]
webview加载了一段html代码，上面的textview也加载了一段文本 ，都是通过网络请求回来的数据设置的，设置完成后，不会滚动到最顶部，而是停留在webview的顶部

**Comment by donkingliang** [comment]
不会滚动到最顶部?? 是滑动不到顶部吗？你使用的版本是多少？

**Comment by 317764920** [comment]
2.5.0，我贴一下布局的代码吧 ，这是个文章详情 ，我这边网络请求成功后，会设置title的文字和webview的内容，然后这个title被滚动到屏幕外了，我需要往下拉一下才能看到这个textview
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:overScrollMode="never"
        android:scrollbars="none">

        <TextView
            android:id="@+id/tv_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingStart="@dimen/dp12"
            android:paddingTop="13dp"
            android:paddingEnd="@dimen/dp12"
            android:paddingBottom="13dp"
            android:text="标题"
            android:textColor="#ff333333"
            android:textSize="24sp" />

        <View
            style="@style/StyleDividerThinTheme"
            android:layout_height="13dp"
            android:background="@color/transparent" />

        <com.xxx.articles.widget.MyRelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <WebView
                android:id="@+id/webView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginStart="@dimen/dp8"
                android:layout_marginEnd="@dimen/dp8"
                android:overScrollMode="never"
                android:scrollbars="none" />

        </com.xxx.articles.widget.MyRelativeLayout>

        <View
            style="@style/StyleDividerThinTheme"
            android:layout_height="5dp"
            android:background="#eee" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerview_recommend"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never" />

        <View
            style="@style/StyleDividerThinTheme"
            android:layout_height="5dp"
            android:background="#eee" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerview_comment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:overScrollMode="never" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

    <View
        style="@style/StyleDividerThinTheme"
        android:background="#eee" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">


    </LinearLayout>

</LinearLayout>
`

**Comment by 317764920** [comment]
> 不会滚动到最顶部?? 是滑动不到顶部吗？你使用的版本是多少？

我明白了 ，是因为我textview设置了padding，我套了一个布局就好了
