### ISSUE TITLE
关于吸顶问题

### ISSUE THREAD

**Issue by BruceeWang** [donkingliang/ConsecutiveScroller#46]
有办法设置多个吸顶view同时吸附在屏幕最上方么？是需要重写某些方法么？比如吸顶view1和view2同时吸附在屏幕的最上端么？

**Comment by donkingliang** [comment]
你好，你可以参考一下这位朋友的
https://github.com/donkingliang/ConsecutiveScroller/pull/20/commits/f361b4e5c3e71d5c3444bba955410cb2b1431e72#diff-a69a208f8ed978904a8e9253d0ec733e
不过他的fork比较旧，你可以下载最新代码，安装他的提交记录修改试一下。

我会在后面的版本加在这个功能。

**Comment by donkingliang** [comment]
新版本已添加常驻吸顶的功能：
app:isPermanent="true"
