### ISSUE TITLE
结合ViewPager2使用滑动太过顺畅

### ISSUE THREAD

**Issue by c4jeff** [donkingliang/ConsecutiveScroller#47]
viewPager2嵌套Fragment：ConsecutiveScroller包裹的webView，
上下滑动WebView很容易跑偏，变左右滑动了，稍微一点斜划都会
换ViewPager是没有这个问题

**Comment by donkingliang** [comment]
这样因为ViewPager2本身对事件滑动就比较灵敏，手指滑动时左右移动一下，就用于触发ViewPager2的滑动。
