### ISSUE TITLE
请问为什么类似这样的TextView设置margin无效呢?一定要嵌套一个ViewGroup,这样太麻烦了吧

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#48]
<?xml version="1.0" encoding="utf-8"?>
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
       <TextView
           android:background="#33ff0000"
           android:textColor="#999999"
           android:textSize="14dp"
           android:padding="10dp"
           android:layout_margin="16dp"
           android:layout_width="match_parent"
           android:layout_height="wrap_content"
           android:text="这个TextView设置的margin无效" />

</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
因为ConsecutiveScrollerLayout不支持margin属性。

**Comment by roybill** [comment]
好的,谢谢
