### ISSUE TITLE
ConsecutiveScrollerLayout 上webview+下Recycleview  webview 无法到顶部

### ISSUE THREAD

**Issue by ROOMPAN** [donkingliang/ConsecutiveScroller#49]
ConsecutiveScrollerLayout 上webview+下Recycleview   webview  加载带图片网页,ConsecutiveScrollerLayout无法回到顶部,而是停留到网页图片位置

**Comment by donkingliang** [comment]
你好，能把你写的布局和你的网页url发一下给我吗？我这边测试一下。

**Comment by ROOMPAN** [comment]
方便留个微信吗?  我加你
