### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sun804336516** [donkingliang/ConsecutiveScroller#5]

**Comment by sun804336516** [comment]
不是全屏的话 这个布局就滑不动

**Comment by donkingliang** [comment]
能具体说一下你的问题吗？你说的不是全屏是那种情况。是ConsecutiveScrollerLayout设置了固定高度或者wrap_content。还是说它里面的子view设置固定高度了？

**Comment by donkingliang** [comment]
如果一个可滚动的子view设置了固定高度，而不是wrap_content或者match_parent，那么它无法与ConsecutiveScrollerLayout作为一个整体滑动，这时候需要给子view设置app:layout_isConsecutive="false"，让它自己处理滑动事件。这种情况属于我在文档说的局部滑动的情况。

**Comment by sun804336516** [comment]
<com.sxw.baseui.view.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/space_50">

这样就不能滑动了

**Comment by sun804336516** [comment]
> 能具体说一下你的问题吗？你说的不是全屏是那种情况。是ConsecutiveScrollerLayout设置了固定高度或者wrap_content。还是说它里面的子view设置固定高度了？

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/space_50">

这样就不能滑动了

**Comment by sun804336516** [comment]
> > 能具体说一下你的问题吗？你说的不是全屏是那种情况。是ConsecutiveScrollerLayout设置了固定高度或者wrap_content。还是说它里面的子view设置固定高度了？
> 
> ```
> <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:layout_marginTop="@dimen/space_50">
> ```
> 
> 这样就不能滑动了

父布局是LinearLayout

**Comment by donkingliang** [comment]
多谢反馈。这个问题已解决更新了。

**Comment by sun804336516** [comment]
> 多谢反馈。这个问题已解决更新了。
厉害
