### ISSUE TITLE
根布局是consecutive，需求原因，用约束布局或者线性布局包裹recycleview，显示不全

### ISSUE THREAD

**Issue by Alexxiaopang** [donkingliang/ConsecutiveScroller#50]
consecutive包裹约束布局，约束布局包裹recycleview，加载到数据的时候，recycleview只能显示出一屏的高度，我发现嵌套的最大高度也只是一个屏幕的高度

**Comment by donkingliang** [comment]
我的文档了有说明，滑动的view必须是ConsecutiveScroller的直接子View，所以你需要ConsecutiveScroller嵌套recycleview，不能中间夹一层约束布局。
