### ISSUE TITLE
请问作者,该怎么实现类似coordinatorlayout的一种效果?请进来看看详细描述

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#51]
我最外层父容器是ConsecutiveScrollerLayout. 里面有上, 中 , 下 三部分内容,最上面是一个背景图和文字
,中间是一个横向的tablayout, 下面是viewpager,viewpager中的fragment都是垂直的列表,现在我设置中间的tablayout吸顶,也就是往上滑动的时候会吸顶,当我中间内容吸顶的时候,怎样可以让上部分内容中的文字设置到最顶部的title上呢?

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout实现不了像coordinatorlayout这样的过渡效果。你可以监听ConsecutiveScrollerLayout的滑动，当滑动到吸顶的时候，就自己去设置顶部的title。
ConsecutiveScrollerLayout监听滑动，使用setOnVerticalScrollChangeListener方法。
