### ISSUE TITLE
请问嵌套两个RecyclerView第二个显示不全是怎么回事

### ISSUE THREAD

**Issue by skywolfwen** [donkingliang/ConsecutiveScroller#52]
在ConsecutiveScrollerLayout下有两个RecyclerView，每个RecyclerView都有一个父布局用来设置圆角，但加了父布局第二个RecyclerView就显示不全内容，只能显示前几个item

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout要直接嵌套RecyclerView，不能中间再嵌套一层父布局。如果你中间一定要嵌套一层父布局，需要让这个布局实现IConsecutiveScroller接口。具体请看文档中的“滑动子view的下级view”。

**Comment by skywolfwen** [comment]
> ConsecutiveScrollerLayout要直接嵌套RecyclerView，不能中间再嵌套一层父布局。如果你中间一定要嵌套一层父布局，需要让这个布局实现IConsecutiveScroller接口。具体请看文档中的“滑动子view的下级view”。

原来如此，谢谢大佬，我完全给当成 NestedScrollView 用了 (^▽^)
