### ISSUE TITLE
吸顶的View可以设置offset吗？距离容器顶部offset高度时，就开始吸顶

### ISSUE THREAD

**Issue by SherlockGougou** [donkingliang/ConsecutiveScroller#53]
就比如ConsecutiveScroller中包含了一个吸顶View，我不想让他到达顶部再吸顶，想让他距离顶部offset距离时就开始吸顶。我看源码中有个
```
/**
     * 子View吸顶
     *
     * @param child
     * @param offset
     */
    @SuppressLint("NewApi")
    private void stickyChild(View child, int offset) {
        child.setY(getScrollY() - offset);
        child.setTranslationZ(1);

        // 把View设置为可点击的，避免吸顶View与其他子View重叠是，触摸事件透过吸顶View传递给下面的View，
        // 导致ConsecutiveScrollerLayout追踪布局的滑动出现偏差
        child.setClickable(true);
    }
```

不知道如何通过代码调用。

**Comment by donkingliang** [comment]
这个方法的offset是后面的吸顶view把前面的吸顶view顶出屏幕的offset，调用这个方法不能实现你想要的效果的。

你想要的效果是吸顶view距离顶部一段距离就悬停。那么布局不就被截断成两部分了吗，顶部到吸顶view的区域也会显示布局。

**Comment by SherlockGougou** [comment]
看一下我的页面：
![image](https://user-images.githubusercontent.com/17920617/82419838-7f120e00-9ab1-11ea-83d0-dba8cab8eceb.png)
![image](https://user-images.githubusercontent.com/17920617/82419858-89340c80-9ab1-11ea-810e-9c65624cd0b9.png)
第一张图，是未滚动的效果；第二张图是需要实现的效果，综合、佣金那一行需要吸顶。因为我顶部包括状态栏都有渐变的处理，所以我的ConsecutiveScroller是全屏高度的，然后把顶部的导航栏，覆盖到了ConsecutiveScroller上面，在通过ConsecutiveScroller的滚动距离，控制的顶部导航栏的透明度。

**Comment by SherlockGougou** [comment]
想要达到的效果，就是吸顶的View置于顶部导航栏的底下。

**Comment by SherlockGougou** [comment]
好像是有点儿奇葩了哈😂

**Comment by donkingliang** [comment]
当吸顶时导航栏不透明了，这样倒是看不出布局成两部分了。
目前没有方法可以设置，不过如果你下载代码修改也很简单。
![1589962112(1)](https://user-images.githubusercontent.com/5499532/82421948-65be9100-9ab4-11ea-914f-f79b1d651c53.png)
![1589962112](https://user-images.githubusercontent.com/5499532/82421954-67885480-9ab4-11ea-84ef-b24ebf96955e.png)
红框的40改成你需要的偏移量就可以了。

**Comment by donkingliang** [comment]
现在只能改源码，后面我会添加个方法设置这个偏移量

**Comment by SherlockGougou** [comment]
感谢！我试试

**Comment by jiqianwen** [comment]
我看源码里面增加了设置偏移量的方法，我下载源码引用module设置偏移量，为什么没效果，求教

**Comment by donkingliang** [comment]
> 我看源码里面增加了设置偏移量的方法，我下载源码引用module设置偏移量，为什么没效果，求教

让我看看你的代码

**Comment by jiqianwen** [comment]
> > 我看源码里面增加了设置偏移量的方法，我下载源码引用module设置偏移量，为什么没效果，求教
> 
> 让我看看你的代码

![image](https://user-images.githubusercontent.com/26268908/82517143-0e213380-9b4f-11ea-868e-71789274d3c4.png)

**Comment by jiqianwen** [comment]
> > 我看源码里面增加了设置偏移量的方法，我下载源码引用module设置偏移量，为什么没效果，求教
> 
> 让我看看你的代码

方便留个QQ或者微信吗？这边交流好麻烦

**Comment by donkingliang** [comment]
qq：1043214265

**Comment by donkingliang** [comment]
功能已更新：
// 设置吸顶到顶部的距离
scrollerLayout.setStickyOffset(offset);

**Comment by longjunye** [comment]
@donkingliang 吸底的效果是不是也用stickyOffset来达到？

**Comment by donkingliang** [comment]
> @donkingliang 吸底的效果是不是也用stickyOffset来达到？

不是，吸顶是通过在滑动时设置子view的Y坐标，让它停留在顶部。而stickyOffset是设置吸顶view的停留位置的，默认是顶部，可以通过stickyOffset让它停留在离顶部100p偏移量的位置。

**Comment by longjunye** [comment]
@donkingliang 那吸底能给个solution么？

**Comment by donkingliang** [comment]
> @donkingliang 那吸底能给个solution么？

ConsecutiveScrollerLayout没有实现吸底的功能。但是你可以按照吸顶的思路自己实现吸底功能。

监听ConsecutiveScrollerLayout滑动，然后判断和计算吸底view的位置，设置需要吸顶的view的y坐标，让它保持在底部。

**Comment by longjunye** [comment]
好的，非常感谢，和我想的差不多



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： donkingliang <notifications@github.com>
日期: 2020/11/18 下午7:05 (GMT+08:00)
收件人： donkingliang/ConsecutiveScroller <ConsecutiveScroller@noreply.github.com>
抄送： longjunye <longjun.ye@hotmail.com>, Comment <comment@noreply.github.com>
主题： Re: [donkingliang/ConsecutiveScroller] 吸顶的View可以设置offset吗？距离容器顶部offset高度时，就开始吸顶 (#53)


@donkingliang<https://github.com/donkingliang> 那吸底能给个solution么？

ConsecutiveScrollerLayout没有实现吸底的功能。但是你可以按照吸顶的思路自己实现吸底功能。

监听ConsecutiveScrollerLayout滑动，然后判断和计算吸底view的位置，设置需要吸顶的view的y坐标，让它保持在底部。

―
