### ISSUE TITLE
大佬帮忙看下我这布局，外层嵌套 SmartRefreshLayout，导致不能触发加载更多

### ISSUE THREAD

**Issue by Rethen** [donkingliang/ConsecutiveScroller#54]
<?xml version="1.0" encoding="utf-8"?>

<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <include
            android:id="@+id/nav_title_back"
            layout="@layout/nav_title_back" />

        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/srl_view"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">

            <com.scwang.smartrefresh.header.MaterialHeader
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

           <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
               android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/n_bg_gray_x_black"
                android:scrollbars="vertical">

                <com.youth.banner.Banner
                    android:id="@+id/banner"
                    android:layout_width="match_parent"
                    android:layout_height="200dp"
                    android:background="@drawable/icon_banner_default"
                    app:banner_default_image="@drawable/icon_banner_default"
                    app:indicator_drawable_selected="@drawable/banner_select"
                    app:indicator_drawable_unselected="@drawable/banner_unselect"
                    app:indicator_height="8dp"
                    app:indicator_margin="3dp"
                    app:indicator_width="8dp"
                    app:layout_scrollFlags="scroll" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="10dp" />

                <LinearLayout
                    android:id="@+id/ll_intraday_hot_stock"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/n_bg_white_black"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/tv_intraday_hot_stock_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:paddingStart="14dp"
                        android:paddingTop="14dp"
                        android:paddingEnd="14dp"
                        android:text="@string/intraday_hot_stock"
                        android:textColor="@color/tv_black_main"
                        android:textSize="15sp" />

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/rv_intraday_hot_stock"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="14dp" />

                </LinearLayout>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="10dp" />

                <LinearLayout
                    android:id="@+id/ll_pursuit_of_profit"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/n_bg_white_black"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/tv_pursuit_of_profit_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:paddingStart="14dp"
                        android:paddingTop="14dp"
                        android:paddingEnd="14dp"
                        android:text="@string/pursuit_of_profit"
                        android:textColor="@color/tv_black_main"
                        android:textSize="15sp" />

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/rv_pursuit_of_profit"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="14dp" />

                </LinearLayout>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="10dp" />

                <LinearLayout
                    android:id="@+id/ll_trading_dynamics"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/n_bg_white_black"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/tv_trading_dynamics_title"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:padding="14dp"
                        android:text="@string/trading_dynamics"
                        android:textColor="@color/tv_black_main"
                        android:textSize="15sp" />

                    <TextView
                        android:id="@+id/tv_trading_dynamics_info"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:padding="8dp"
                        android:paddingStart="14dp"
                        android:paddingEnd="14dp"
                        android:textColor="@color/bg_color_home_nodify"
                        android:textSize="13sp" />

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/rv_trading_dynamics"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="14dp" />

                    <TextView
                        android:id="@+id/tv_view_see_more"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:gravity="center_horizontal"
                        android:text="@string/view_see_more" />

                </LinearLayout>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="10dp" />

                <LinearLayout
                    android:id="@+id/ll_all_items"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/n_bg_white_black"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/tv_all_items_title"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:padding="14dp"
                        android:text="@string/all_items"
                        android:textColor="@color/tv_black_main"
                        android:textSize="15sp" />

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="45dp"
                        android:background="@color/n_bg_gray_black"
                        android:paddingStart="14dp"
                        android:paddingEnd="14dp">

                        <LinearLayout
                            android:id="@+id/ll_rank_letter"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:gravity="center_vertical">

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginRight="3dp"
                                android:text="@string/quote_stock_code"
                                android:textColor="@color/tv_gray_1"
                                android:textSize="14sp" />

                            <ImageView
                                android:id="@+id/iv_rank_letter"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:padding="1dp"
                                android:src="@drawable/n_ic_sort" />
                        </LinearLayout>

                        <View
                            android:layout_width="0dp"
                            android:layout_height="match_parent"
                            android:layout_weight="1" />

                        <LinearLayout
                            android:id="@+id/ll_rank_range"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:gravity="center_vertical|right">

                            <TextView
                                android:id="@+id/tv_rank_range"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="8dp"
                                android:layout_marginRight="3dp"
                                android:text="@string/quote_chg"
                                android:textColor="@color/tv_gray_1"
                                android:textSize="14sp" />

                            <ImageView
                                android:id="@+id/iv_rank_range"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:padding="1dp"
                                android:src="@drawable/n_ic_sort_down" />
                        </LinearLayout>
                    </LinearLayout>

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/rv_all_items"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="14dp" />

                </LinearLayout>

           </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    </LinearLayout>

</layout>

**Comment by donkingliang** [comment]
你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?

**Comment by Rethen** [comment]
> 你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?

不是最新版本的，不是横向滑动的，RecyclerView 版本是28.0.0

**Comment by Rethen** [comment]
> 你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?

你的库版本是3.5.1

**Comment by Rethen** [comment]
> 你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?

难道不支持多个嵌套吗？

**Comment by donkingliang** [comment]
> > 你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?
> 
> 难道不支持多个嵌套吗？

垂直滑动的view需要是ConsecutiveScrollerLayout的直接子view，如果要多层嵌套，可以参考文档中的“滑动子view的下级view”实现IConsecutiveScroller接口，并且实现时注意文档上说的细节。

**Comment by Rethen** [comment]
> > > 你使用的是最新版本吗？我看的你有几个RecyclerView是嵌套在LinearLayout里的，这些是横向滑动的吗?
> > 
> > 
> > 难道不支持多个嵌套吗？
> 
> 垂直滑动的view需要是ConsecutiveScrollerLayout的直接子view，如果要多层嵌套，可以参考文档中的“滑动子view的下级view”实现IConsecutiveScroller接口，并且实现时注意文档上说的细节。

如果是这样的话，那我必须要自定义父布局，也就是LinearLayout

**Comment by donkingliang** [comment]
我看你的布局，是完全可以不必把RecyclerView嵌套在LinearLayout里的，如果你这样做只是为了能方便设置布局的背景或者控制布局区域的显示和隐藏，那么我建议你可以去掉RecyclerView外层的LinearLayout，这样实现更加简单和高效。

**Comment by donkingliang** [comment]
去掉嵌套，让RecyclerView直接嵌套在ConsecutiveScrollerLayout。ConsecutiveScrollerLayout不支持子view的margin，你可以把RecyclerView 的layout_marginTop用一个空白view或者Space来设置边界效果。

**Comment by Rethen** [comment]
> layout_marginTop

你这么一说，好像确实是可以优化一下，我去掉试下
