### ISSUE TITLE
recyclerView的Item设置成ImageView 无法显示问题

### ISSUE THREAD

**Issue by w296365959** [donkingliang/ConsecutiveScroller#55]
recyclerView 竖向，Item是ImageView  ，iv高度wrap_content，
无法显示Rv的内容

**Comment by donkingliang** [comment]
能提供一下你的布局和adapter代码吗？

**Comment by w296365959** [comment]
直接子View是使用的FramLayout 代码内从替换成Fragment, RecyclerView在这个Fragment内

**Comment by donkingliang** [comment]
RecyclerView需要是ConsecutiveScrollerLayout的直接子view。你这样写RecyclerView的父布局就不是ConsecutiveScrollerLayout了。
如果你一定要多层嵌套，需要参考文档中的“滑动子view的下级view”，给ConsecutiveScrollerLayout的直接子view实现IConsecutiveScroller接口。

**Comment by w296365959** [comment]
好的我后面试试

**Comment by w296365959** [comment]
我这找了下原因，发现问题是由于我这图片加载的时候 重新计算图片宽高比 然后重新设置ImageView宽高,导致显示不了 
glide 直接加载图片可以显示的
 `.into(new SimpleTarget<Bitmap>() {
                        @Override
                        public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                            int imageWidth = resource.getWidth();
                            int imageHeight = resource.getHeight();

                            //宽度固定,然后根据原始宽高比得到此固定宽度需要的高度
                            int height = screenWidth * imageHeight / imageWidth;
                            ViewGroup.LayoutParams para = mImageView.getLayoutParams();
                            para.height = height;
                            para.width = screenWidth;
                            mImageView.setImageBitmap(resource);
                        }
                    });`
