### ISSUE TITLE
能否添加方法获取正在吸顶的View，或者添加吸顶View的实时监听

### ISSUE THREAD

**Issue by Alexxiaopang** [donkingliang/ConsecutiveScroller#56]
如题，想动态更改吸顶view的背景，吸顶时候一个颜色，正常的时候一个颜色

**Comment by donkingliang** [comment]
你可以setOnVerticalScrollChangeListener监听滑动变化，然后判断一个子view是否吸顶。child.getTop() <= scrollerLayout.getScrollY();
滑动监听会在滑动时多次回调。

后面我会提供监听吸顶变化和获取吸顶view的方法。

**Comment by donkingliang** [comment]
已更新
