### ISSUE TITLE
CoordinatorLayout下面使用ConsecutiveScroller无法上下滑动

### ISSUE THREAD

**Issue by xiangxm** [donkingliang/ConsecutiveScroller#57]
在CoordinatorLayout下面使用ConsecutiveScroller添加了
                app:layout_behavior="@string/appbar_scrolling_view_behavior" 这个效果，无法滑动，请问有啥解决办法吗？ 我想在ConsecutiveScroller 里面展示webview 这两个又是在CoordinatorLayout的下面，因为顶部有个图片的banner
`
        <androidx.coordinatorlayout.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">`

**Comment by donkingliang** [comment]
CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。

我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。

**Comment by donkingliang** [comment]
现在你可以自己自定义ConsecutiveScroller，给它实现NestedScrollingChild接口，应该也是可以的。

**Comment by xiangxm** [comment]
> CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> 
> 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。

 谢谢大佬的解答。 我尝试去写一下

**Comment by xyZangGit** [comment]
> > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> 
> 谢谢大佬的解答。 我尝试去写一下

请问你解决这个问题了么

**Comment by donkingliang** [comment]
> > > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> > 
> > 
> > 谢谢大佬的解答。 我尝试去写一下
> 
> 请问你解决这个问题了么

现在你使用最新的版本即可。2.6.0或者3.6.0。

**Comment by xyZangGit** [comment]
> > > > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > > > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> > > 
> > > 
> > > 谢谢大佬的解答。 我尝试去写一下
> > 
> > 
> > 请问你解决这个问题了么
> 
> 现在你使用最新的版本即可。2.6.0或者3.6.0。

好的大大，我试一下

**Comment by xyZangGit** [comment]
> > > > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > > > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> > > 
> > > 
> > > 谢谢大佬的解答。 我尝试去写一下
> > 
> > 
> > 请问你解决这个问题了么
> 
> 现在你使用最新的版本即可。2.6.0或者3.6.0。

非常感谢解决了我的问题，但是惯性滑动好像有些问题，下面是我的 布局文件，手指如果向上惯性滑动会抖动，滑不上去，除非手指不离开屏幕，才可以连贯滑动

<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/lucency"
    tools:context="jp.wasabeef.example.acty.ScrollNestRvActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/lucency"
        app:elevation="0dp">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/CollapsingToolbarLayout"
            android:layout_width="match_parent"
            android:layout_height="250dp"
            android:background="@color/blue"
            android:fitsSystemWindows="true"
            app:contentScrim="@color/lucency"
            app:layout_collapseParallaxMultiplier="0"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:statusBarScrim="@android:color/transparent"
            app:titleEnabled="false">

            <androidx.viewpager2.widget.ViewPager2
                android:id="@+id/vp2"
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:layout_marginTop="25dp"
                app:layout_collapseMode="parallax"
                app:layout_collapseParallaxMultiplier="0"
                app:layout_scrollFlags="scroll|exitUntilCollapsed|snap" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/scroll_csl"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="-30dp"
        android:background="@drawable/top50_shape_white"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="40dp"
                android:text="京东方做的饭男的付"
                android:textSize="20sp" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:gravity="center_vertical">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:text="舒服舒服的" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:text="舒服舒服的" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:text="舒服舒服的" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:text="舒服舒服的" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:text="舒服舒服的" />
            </LinearLayout>
        </LinearLayout>

        <WebView
            android:id="@+id/webview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by xyZangGit** [comment]
> > > > > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > > > > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> > > > 
> > > > 
> > > > 谢谢大佬的解答。 我尝试去写一下
> > > 
> > > 
> > > 请问你解决这个问题了么
> > 
> > 
> > 现在你使用最新的版本即可。2.6.0或者3.6.0。
> 
> 好的大大，我

> > > > CoordinatorLayout能协调的子view需要是实现了NestedScrollingChild接口的view，比如RecyclerView，NestedScrollView等。ConsecutiveScroller没有实现NestedScrollingChild接口，所以协调不了的。
> > > > 我后面会考虑给ConsecutiveScroller实现NestedScrollingChild接口。
> > > 
> > > 
> > > 谢谢大佬的解答。 我尝试去写一下
> > 
> > 
> > 请问你解决这个问题了么
> 
> 现在你使用最新的版本即可。2.6.0或者3.6.0。

大大，我现在用的是2.6.0版本，上划惯性滑动抖动问题是否可以解决，或者提供一下思路

**Comment by donkingliang** [comment]
我修改了一下嵌套滑动的处理，你下载我的代码导入你的项目，试一下是否还有问题。

**Comment by xyZangGit** [comment]
> 我修改了一下嵌套滑动的处理，你下载我的代码导入你的项目，试一下是否还有问题。

非常感谢，解决了我的问题，我用的最新的源码

**Comment by xyZangGit** [comment]
> 我修改了一下嵌套滑动的处理，你下载我的代码导入你的项目，试一下是否还有问题。
会偶现出现划不动的情况。。。。最新发现的bug

**Comment by xyZangGit** [comment]
> 我修改了一下嵌套滑动的处理，你下载我的代码导入你的项目，试一下是否还有问题。

可否加扣扣或者微信反馈，在这里 效率有点低，我的扣扣：942803679

**Comment by xyZangGit** [comment]
> 我修改了一下嵌套滑动的处理，你下载我的代码导入你的项目，试一下是否还有问题。

测试发现，问题还是比较大的
