### ISSUE TITLE
Recyclerview的item滑动问题

### ISSUE THREAD

**Issue by ArcGhh** [donkingliang/ConsecutiveScroller#58]
假设Recyclerview的某个item是个横向滚动的Recyclerview，也就是嵌套Recyclerview。
会出现这种情况：那个横向滚动的item特别卡顿

**Comment by donkingliang** [comment]
手指滑动和fling都会卡顿吗？你试一下如果横向的Recyclerview不是嵌套在Recyclerview，而且嵌套在ConsecutiveScroller，会卡顿吗？

**Comment by ArcGhh** [comment]
横向的Recyclerview不是嵌套在Recyclerview时,手指滑动几乎不会出现卡顿
如果是嵌套在Recyclerview，偶尔会出现卡顿。
按这种情况来看，应该和ConsecutiveScroller没关系了
