### ISSUE TITLE
滑动过程中页面内容明显抖动 

### ISSUE THREAD

**Issue by daiwenbo88** [donkingliang/ConsecutiveScroller#6]
在滑动过程中 特别是文字内容 抖动厉害 需要怎么优化

**Comment by donkingliang** [comment]
你在ConsecutiveScrollerLayout里嵌套的是什么控件？能让我看一下你的布局是怎么写的吗？

**Comment by daiwenbo88** [comment]
有个吸顶的需求 头布局 用的 ConstraintLayout

**Comment by daiwenbo88** [comment]
<androidx.constraintlayout.widget.ConstraintLayout
                            android:id="@+id/head_root_view"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content">

                            <ImageView
                                android:id="@+id/product_image"
                                android:layout_width="@dimen/dp_90"
                                android:layout_height="@dimen/dp_90"
                                android:layout_marginLeft="@dimen/dp_15"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toTopOf="parent" />

                            <TextView
                                android:id="@+id/product_name"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:text="瑞蓝2号丰卧蚕"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_16"
                                app:layout_constraintLeft_toRightOf="@+id/product_image"
                                app:layout_constraintRight_toLeftOf="@+id/reference_standard"
                                app:layout_constraintTop_toTopOf="parent" />

                            <TextView
                                android:id="@+id/product_price"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_6"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintLeft_toRightOf="@+id/product_image"
                                app:layout_constraintTop_toBottomOf="@+id/product_name" />

                            <TextView
                                android:id="@+id/average_price"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_6"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintLeft_toRightOf="@+id/product_image"
                                app:layout_constraintTop_toBottomOf="@+id/product_price" />

                            <TextView
                                android:id="@+id/select_count"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_6"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintLeft_toRightOf="@+id/product_image"
                                app:layout_constraintTop_toBottomOf="@+id/average_price" />

                            <TextView
                                android:id="@+id/reservation_count"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintBottom_toBottomOf="@+id/select_count"
                                app:layout_constraintLeft_toRightOf="@+id/select_count"
                                app:layout_constraintTop_toTopOf="@+id/select_count" />

                            <TextView
                                android:id="@+id/case_count"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintBottom_toBottomOf="@+id/select_count"
                                app:layout_constraintLeft_toRightOf="@+id/reservation_count"
                                app:layout_constraintTop_toTopOf="@+id/select_count" />

                            <TextView
                                android:id="@+id/origin_name"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginTop="@dimen/dp_20"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_15"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintRight_toLeftOf="@+id/line_one"
                                app:layout_constraintTop_toBottomOf="@+id/product_image" />

                            <View
                                android:id="@+id/line_one"
                                android:layout_width="@dimen/dp_1"
                                android:layout_height="@dimen/dp_25"
                                android:background="#f6f9f9"
                                app:layout_constraintBottom_toBottomOf="@+id/origin_name_str"
                                app:layout_constraintLeft_toRightOf="@+id/origin_name"
                                app:layout_constraintRight_toLeftOf="@+id/market_time"
                                app:layout_constraintTop_toTopOf="@+id/origin_name" />

                            <TextView
                                android:id="@+id/market_time"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_15"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_one"
                                app:layout_constraintRight_toLeftOf="@+id/line_two"
                                app:layout_constraintTop_toTopOf="@+id/origin_name" />

                            <View
                                android:id="@+id/line_two"
                                android:layout_width="@dimen/dp_1"
                                android:layout_height="@dimen/dp_25"
                                android:background="#f6f9f9"
                                app:layout_constraintBottom_toBottomOf="@+id/line_one"
                                app:layout_constraintLeft_toRightOf="@+id/market_time"
                                app:layout_constraintRight_toLeftOf="@+id/molecular_weight"
                                app:layout_constraintTop_toTopOf="@+id/line_one" />

                            <TextView
                                android:id="@+id/molecular_weight"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_15"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_two"
                                app:layout_constraintRight_toLeftOf="@+id/line_three"
                                app:layout_constraintTop_toTopOf="@+id/origin_name" />

                            <View
                                android:id="@+id/line_three"
                                android:layout_width="@dimen/dp_1"
                                android:layout_height="@dimen/dp_25"
                                android:background="#F6F9F9"
                                app:layout_constraintBottom_toBottomOf="@+id/line_one"
                                app:layout_constraintLeft_toRightOf="@+id/molecular_weight"
                                app:layout_constraintRight_toLeftOf="@+id/expiration_date"
                                app:layout_constraintTop_toTopOf="@+id/line_one" />

                            <TextView
                                android:id="@+id/expiration_date"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_15"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_three"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/origin_name" />

                            <TextView
                                android:id="@+id/origin_name_str"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginTop="@dimen/dp_5"
                                android:gravity="center"
                                android:text="产      地"
                                android:textColor="@color/col_777777"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintRight_toLeftOf="@+id/line_one"
                                app:layout_constraintTop_toBottomOf="@+id/origin_name" />

                            <TextView
                                android:id="@+id/market_time_str"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:text="上市时间"
                                android:textColor="@color/col_777777"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_one"
                                app:layout_constraintRight_toLeftOf="@+id/line_two"
                                app:layout_constraintTop_toTopOf="@+id/origin_name_str" />

                            <TextView
                                android:id="@+id/molecular_weight_str"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:text="中分子"
                                android:textColor="@color/col_777777"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_two"
                                app:layout_constraintRight_toLeftOf="@+id/line_three"
                                app:layout_constraintTop_toTopOf="@+id/origin_name_str" />

                            <TextView
                                android:id="@+id/expiration_date_str"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:ellipsize="end"
                                android:gravity="center"
                                android:maxLines="1"
                                android:text="1-2年"
                                android:textColor="@color/col_777777"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintHorizontal_weight="1"
                                app:layout_constraintLeft_toRightOf="@+id/line_three"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/molecular_weight_str" />

                            <View
                                android:id="@+id/layer_content"
                                android:layout_width="match_parent"
                                android:layout_height="@dimen/dp_45"
                                android:layout_marginTop="@dimen/dp_20"
                                android:padding="@dimen/dp_15"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/origin_name_str" />

                            <TextView
                                android:id="@+id/hot_chat_count"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:drawableLeft="@drawable/icon_hot_chat"
                                android:drawablePadding="@dimen/dp_4"
                                android:text="9702"
                                android:textColor="#FF1E1D"
                                android:textSize="@dimen/sp_16"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_content"
                                app:layout_constraintLeft_toLeftOf="@+id/layer_content"
                                app:layout_constraintTop_toTopOf="@+id/layer_content" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="人正在热聊"
                                android:textColor="@color/col_333333"
                                android:textSize="@dimen/sp_12"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_content"
                                app:layout_constraintLeft_toRightOf="@+id/hot_chat_count"
                                app:layout_constraintTop_toBottomOf="@+id/origin_name_str"
                                app:layout_constraintTop_toTopOf="@+id/layer_content" />

                            <ImageView
                                android:id="@+id/arrow_right"
                                android:layout_width="@dimen/dp_4"
                                android:layout_height="@dimen/dp_6"
                                android:layout_marginRight="@dimen/dp_15"
                                android:background="@drawable/right_arrow"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_content"
                                app:layout_constraintRight_toRightOf="@+id/layer_content"
                                app:layout_constraintTop_toTopOf="@+id/layer_content" />

                            <androidx.constraintlayout.widget.helper.Layer
                                android:id="@+id/layer_chat"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:padding="@dimen/dp_3"
                                app:constraint_referenced_ids="chat_user_head,chat_msg"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_content"
                                app:layout_constraintRight_toLeftOf="@+id/arrow_right"
                                app:layout_constraintTop_toTopOf="@+id/layer_content" />

                            <ImageView
                                android:id="@+id/chat_user_head"
                                android:layout_width="@dimen/dp_15"
                                android:layout_height="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_5"
                                android:background="@color/col_333333"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_chat"
                                app:layout_constraintRight_toLeftOf="@+id/chat_msg"
                                app:layout_constraintTop_toTopOf="@+id/layer_chat" />

                            <TextView
                                android:id="@+id/chat_msg"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginRight="@dimen/dp_10"
                                android:text="昨天刚做完，现在感…"
                                android:textColor="#5982D4"
                                android:textSize="@dimen/sp_10"
                                app:layout_constraintBottom_toBottomOf="@+id/layer_chat"
                                app:layout_constraintRight_toLeftOf="@+id/arrow_right"
                                app:layout_constraintTop_toTopOf="@+id/layer_chat" />


                            <TextView
                                android:id="@+id/drug_efficacy_title"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_20"
                                android:text="药品特色"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/layer_content" />

                            <TextView
                                android:id="@+id/drug_efficacy"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:textColor="@color/col_555555"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toRightOf="@+id/drug_efficacy_title"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/drug_efficacy_title" />

                            <TextView
                                android:id="@+id/drug_ingredient_title"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_10"
                                android:text="成        份"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/drug_efficacy_title" />

                            <TextView
                                android:id="@+id/drug_ingredient"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:textColor="@color/col_555555"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toRightOf="@+id/drug_ingredient_title"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/drug_ingredient_title" />

                            <TextView
                                android:id="@+id/nature_type_title"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_10"
                                android:text="性质类型"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/drug_ingredient_title" />

                            <TextView
                                android:id="@+id/drug_nature_type"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:textColor="@color/col_555555"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toRightOf="@+id/nature_type_title"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/nature_type_title" />

                            <TextView
                                android:id="@+id/drug_advantage_title"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_10"
                                android:text="优        点"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/nature_type_title" />

                            <TextView
                                android:id="@+id/drug_advantage"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:textColor="@color/col_555555"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toRightOf="@+id/drug_advantage_title"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/drug_advantage_title" />

                            <TextView
                                android:id="@+id/drug_defect_title"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginTop="@dimen/dp_10"
                                android:text="缺        点"
                                android:textColor="@color/col_aaabb3"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/drug_advantage_title" />

                            <TextView
                                android:id="@+id/drug_defect"
                                android:layout_width="0dp"
                                android:layout_height="wrap_content"
                                android:layout_marginLeft="@dimen/dp_15"
                                android:layout_marginRight="@dimen/dp_15"
                                android:ellipsize="end"
                                android:maxLines="1"
                                android:textColor="@color/col_555555"
                                android:textSize="@dimen/sp_13"
                                app:layout_constraintLeft_toRightOf="@+id/drug_defect_title"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toTopOf="@+id/drug_defect_title" />

                            <ImageView
                                android:id="@+id/reference_standard"
                                android:layout_width="@dimen/dp_48"
                                android:layout_height="@dimen/dp_48"
                                android:layout_marginRight="@dimen/dp_15"
                                android:layout_marginBottom="@dimen/dp_2"
                                android:background="@drawable/icon_reference_standard"
                                app:layout_constraintBottom_toBottomOf="@+id/average_price"
                                app:layout_constraintRight_toRightOf="parent" />

                            <View
                                android:layout_width="match_parent"
                                android:layout_height="@dimen/dp_5"
                                android:layout_marginTop="@dimen/dp_30"
                                android:background="@color/col_f3f7f7"
                                app:layout_constraintBottom_toBottomOf="parent"
                                app:layout_constraintLeft_toLeftOf="parent"
                                app:layout_constraintRight_toRightOf="parent"
                                app:layout_constraintTop_toBottomOf="@+id/drug_defect" />
                        </androidx.constraintlayout.widget.ConstraintLayout>

**Comment by daiwenbo88** [comment]
这个是头布局 下面就tab 和viewpage 头布局里面的文字内容较多 但是布局很简单 滑动的时候 文字抖动厉害

**Comment by donkingliang** [comment]
你的viewpage是不是也是可以垂直滑动的，如果是，那么你的问题可能跟下面这个问题一样。 https://github.com/donkingliang/ConsecutiveScroller/issues/2
需要给viewpage设置app:layout_isConsecutive="false"属性，不过这样它就不能跟ConsecutiveScroller整体滑动了。
我后面会考虑给ConsecutiveScroller单独处理一下嵌套viewpage的情况。

**Comment by itzihao** [comment]
RecyclerView 滑动过程也抖动很厉害....

**Comment by itzihao** [comment]
图片内容比较多，下滑过程很明显。。。。

**Comment by donkingliang** [comment]
> RecyclerView 滑动过程也抖动很厉害....

多谢反馈，RecyclerView抖动的问题，我做了一些优化了。
