### ISSUE TITLE
吸顶布局问题

### ISSUE THREAD

**Issue by LatlngV** [donkingliang/ConsecutiveScroller#60]
页面由三部分组成，上面是一个高度固定的 viewgroup，中间是吸顶 TextView，下面是 RecyclerView。当 RecyclerView 不满一屏时，RecyclerView 继续往上滑会超过吸顶 View

**Comment by donkingliang** [comment]
超过吸顶 View，那么底部是变成空白了吗

**Comment by LatlngV** [comment]
底部是空白，就是往上滑吸顶布局会覆盖在 RecyclerView 上面，应该 RecyclerView 在吸顶布局下面

**Comment by donkingliang** [comment]
如果布局可以滑动，那么吸顶的view滑到最顶的时候当然是会覆盖在下面的布局上面的。
是不是你的RecyclerView是match_parent的，所以就算你的数据不满一屏，RecyclerView的高度还是会占满一屏的空间。你的RecyclerView高度应该设置为wrap_content。
