### ISSUE TITLE
类似新闻详情的页面,里面有WebView,我在Webview数据加载完后的回调中添加滚动到评论区的代码,为什么无效呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#61]
日志有打印,但是不会自动滚动到评论的地方,下面是代码,这个回调是WebView的:
 mWebView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url);
                //返回true
                return true;
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                //网页加载完成后才显示所有内容
                mProgressBar.setVisibility(View.GONE);
                mContentLayout.setVisibility(View.VISIBLE);
                boolean isComment = getIntent().getBooleanExtra("isComment", false);//是否点击的评论  (是点击评论进来的,直接滚动到评论)
                if (isComment) {
                    mScrollerLayout.scrollToChild(mCommentPosition);//
                    LogUtils.d("1146  "+isComment);   //这个日志有打印,但是没有滚动到评论
                }
            }
}

**Comment by donkingliang** [comment]
mCommentPosition是什么？是评论区的View布局吗？这边布局是不是mScrollerLayout的子view？

**Comment by donkingliang** [comment]
你现在在onGlobalLayout调用scrollToChild应该是没有问题的吧。
这个问题其实是因为页面在加载的过程中，控件的高度是还没有确定的，这时候调用滑动，位置可能就会出现偏出。所以需要延迟一下

**Comment by donkingliang** [comment]
监听器回调后，建议你把它移除，避免下次布局发生变化时再回调

**Comment by roybill** [comment]
谢谢,这样可行
