### ISSUE TITLE
吸顶以后下面的webview被覆盖了一部分

### ISSUE THREAD

**Issue by wonderfulive** [donkingliang/ConsecutiveScroller#62]
先说一下，上面是个scrollview，中间有一个可吸顶的layout，下面时webview，当滑动到吸顶的位置时，设置中间的layout和webview的isConsecutive属性为false，这时候webview会被中间吸顶的layout遮盖一部分

**Comment by donkingliang** [comment]
吸顶的布局本来就是要覆盖在普通布局的上面的。这样正常的。

如果你的webview是最底部的view，你可以通过修改webview的布局高度减去吸顶view的高度。这样吸顶view就覆盖不到webview了 。
