### ISSUE TITLE
2.6.1版本下又出现了滑动不流畅的问题

### ISSUE THREAD

**Issue by skywolfwen** [donkingliang/ConsecutiveScroller#63]
ConsecutiveScroller 嵌套 RecyclerView，2.6.0 版本可以流畅滑动，但2.6.1版本在滑动得过程中会突然停住，有时候当它突然停住的时候继续用手指滑也滑不动，几秒钟后又可以滑动了

**Comment by donkingliang** [comment]
你好，能提供一下你的布局给我排查一下吗?
或者你下载最新的代码试一下还有没有问题。主分支的代码

**Comment by skywolfwen** [comment]
> 你好，能提供一下你的布局给我排查一下吗?
> 或者你下载最新的代码试一下还有没有问题。主分支的代码

布局如下

<SmartRefreshLayout>
       <ConsecutiveScrollerLayout>
              <Space>
              <ViewStub>
              <ConstraintLayout>
              <RecyclerView>
              <Space>
              <ConstraintLayout>
              <RecyclerView>
       </ConsecutiveScrollerLayout>
</SmartRefreshLayout>

**Comment by skywolfwen** [comment]
布局是这样的
<SmartRefreshLayout>
<ConsecutiveScrollerLayout>

<Space/>
<ViewStub/>
<Space/>
<ConstraintLayout/>
<RecyclerView/>
<Space/>
<ConstraintLayout/>
<RecyclerView/>

</ConsecutiveScrollerLayout>
</SmartRefreshLayout>

**Comment by skywolfwen** [comment]
布局大概是这样的，都是ConsecutiveScrollerLayout的子 View

SmartRefreshLayout
ConsecutiveScrollerLayout

Space
ViewStub
Space
ConstraintLayout
RecyclerView
Space
ConstraintLayout
RecyclerView

/ConsecutiveScrollerLayout
/SmartRefreshLayout

**Comment by skywolfwen** [comment]
大佬，新版本还是有用手指快速滑动会卡住的情况，我安装demo后尝试也是有这个问题的，你可以试试用手指在列表还在滑动的时候就去滑动（速度可以快些）应该可以复现，还是2.6.0之后才有的问题
