### ISSUE TITLE
[bug] 水平滑动后再垂直滑动出现滑动事件不响应

### ISSUE THREAD

**Issue by Lyon1994** [donkingliang/ConsecutiveScroller#66]
手指按下，先水平滑动任意距离，手指不要抬起再垂直滑动，此时view并不会响应垂直方向的触摸事件
![temp123](https://user-images.githubusercontent.com/8456652/83626061-806e2b00-a5c7-11ea-9b06-9308cddcec21.png)

**Comment by donkingliang** [comment]
不是bug。ConsecutiveScroller的设计是同一个事件序列，如果判断为水平滑动，就不会响应垂直滑动；如果判断为垂直滑动，就不会响应水平滑动。
因为如果支持同时响应垂直和水平滑动，有一些控件会出现滑动冲突。
