### ISSUE TITLE
scrollToChild 方法会滑动到吸顶布局下面

### ISSUE THREAD

**Issue by LatlngV** [donkingliang/ConsecutiveScroller#68]
我调用了setStickyOffset 设置吸顶布局距离顶部的距离，然后调用 scrollToChild 方法，结果下面的布局会多滑动一部分，我不设置吸顶布局到顶部的距离测试了一下，依然会多滑动一块

**Comment by donkingliang** [comment]
scrollToChild是将view滑动到顶部，而吸顶view是覆盖在其他view上面的。所以view滑动到顶部时，自然是会被吸顶的view覆盖到。

**Comment by donkingliang** [comment]
因为顶部是父布局的上边缘，而不是吸顶view的下边缘
