### ISSUE TITLE
支持SmartRefreshLayout 

### ISSUE THREAD

**Issue by open9527** [donkingliang/ConsecutiveScroller#7]
支持内部,或者外部嵌套SmartRefreshLayout么?

**Comment by donkingliang** [comment]
支持外部嵌套SmartRefreshLayout

**Comment by 317764920** [comment]
@donkingliang 我这边发现上拉加载不起作用呢 ，下拉刷新是没问题的

**Comment by 317764920** [comment]
@donkingliang 
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        app:srlEnablePreviewInEditMode="true">

        <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
            android:id="@+id/scrollerLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:overScrollMode="never"
            android:scrollbars="none">

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="13dp"
                android:background="@color/transparent" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/tv_date"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/dp12"
                    android:layout_marginEnd="@dimen/dp12"
                    android:text="时间"
                    android:textColor="#ff999999"
                    android:textSize="12sp" />

                <View
                    style="@style/StyleDividerThinTheme"
                    android:layout_height="13dp"
                    android:background="@color/transparent" />

                <TextView
                    android:id="@+id/tv_title"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/dp12"
                    android:layout_marginEnd="@dimen/dp12"
                    android:text="标题"
                    android:textColor="#ff333333"
                    android:textSize="24sp" />

            </LinearLayout>

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="13dp"
                android:background="@color/transparent" />

            <com.mxcj.articles.widget.MyRelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <WebView
                    android:id="@+id/webView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginStart="@dimen/dp12"
                    android:layout_marginEnd="@dimen/dp12"
                    android:overScrollMode="never"
                    android:scrollbars="none" />

            </com.mxcj.articles.widget.MyRelativeLayout>

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="5dp"
                android:background="#eee" />

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="14dp"
                android:background="@color/transparent" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/dp12"
                    android:layout_marginEnd="@dimen/dp12"
                    android:text="相关阅读"
                    android:textColor="#ff333333"
                    android:textSize="16sp" />
            </LinearLayout>

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="2dp"
                android:background="@color/transparent" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recyclerview_recommend"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:overScrollMode="never" />

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="5dp"
                android:background="#eee" />

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="14dp"
                android:background="@color/transparent" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/dp12"
                    android:layout_marginEnd="@dimen/dp12"
                    android:text="评论区"
                    android:textColor="#ff333333"
                    android:textSize="16sp" />
            </LinearLayout>

            <View
                style="@style/StyleDividerThinTheme"
                android:layout_height="2dp"
                android:background="@color/transparent" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recyclerview_comment"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:overScrollMode="never" />

        </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

    <View
        style="@style/StyleDividerThinTheme"
        android:background="#eee" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp48"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/tv_comment"
            android:layout_width="0dp"
            android:layout_height="34dp"
            android:layout_marginStart="@dimen/dp18"
            android:layout_marginEnd="@dimen/dp18"
            android:layout_weight="1"
            android:background="@drawable/articles_bg_click_comment"
            android:gravity="center_vertical"
            android:paddingStart="@dimen/dp10"
            android:paddingEnd="@dimen/dp10"
            android:text="我来说两句..."
            android:textColor="#ffa7a7a7"
            android:textSize="14sp" />

        <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <ImageButton
                android:id="@+id/ib_comment"
                android:layout_width="@dimen/dp48"
                android:layout_height="@dimen/dp48"
                android:background="@drawable/style_selector_base"
                android:src="@mipmap/articles_icon_comment" />

            <com.mxcj.component_ui.widget.badge.BadgeView
                android:id="@+id/badge_comment"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="top|end"
                android:layout_margin="7dp" />

        </FrameLayout>

        <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <ImageButton
                android:id="@+id/ib_collect"
                android:layout_width="@dimen/dp48"
                android:layout_height="@dimen/dp48"
                android:background="@drawable/style_selector_base"
                android:src="@mipmap/articles_icon_collect" />

            <com.mxcj.component_ui.widget.badge.BadgeView
                android:id="@+id/badge_collect"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="top|end"
                android:layout_margin="7dp" />

        </FrameLayout>

        <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <ImageButton
                android:id="@+id/ib_like"
                android:layout_width="@dimen/dp48"
                android:layout_height="@dimen/dp48"
                android:background="@drawable/style_selector_base"
                android:src="@mipmap/articles_icon_like" />

            <com.mxcj.component_ui.widget.badge.BadgeView
                android:id="@+id/badge_like"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="top|end"
                android:layout_margin="7dp" />

        </FrameLayout>

        <ImageButton
            android:id="@+id/ib_share"
            android:layout_width="@dimen/dp48"
            android:layout_height="@dimen/dp48"
            android:background="@drawable/style_selector_base"
            android:src="@mipmap/articles_icon_share" />

    </LinearLayout>

</LinearLayout>
`

**Comment by donkingliang** [comment]
你的SmartRefreshLayout设置了上拉加载了吗。SmartRefreshLayout默认是不开启上拉加载的哦

**Comment by 317764920** [comment]
@donkingliang 我找到问题了 ，是因为我这边设置了不满一屏不开启上拉 ，应该没什么问题了
