### ISSUE TITLE
RecyclerView item中的子view有点击事件时,会触发滚动

### ISSUE THREAD

**Issue by hyl87** [donkingliang/ConsecutiveScroller#71]
布局层级如下:
ConsecutiveScrollerLayout
    view
    view
    view
    view
    ConsecutiveScrollerLayout 包含了一个可以滚动的fragment
ConsecutiveScrollerLayout

**Comment by donkingliang** [comment]
你点击时是不是手指有移动啊。我github的demo里的RecyclerView Item就是设置点击监听的，不会触发滑动啊。

**Comment by hyl87** [comment]
@donkingliang   fragment 里面的 RecyclerView  包含了视频控件,点击的时候就会触发滚动,滚动到顶部,

**Comment by hyl87** [comment]
![image](https://user-images.githubusercontent.com/1303038/84261101-c7bb6500-ab4d-11ea-9589-ee6870a50c41.png)
这是点击调试的时候触发了 这里的滚动

**Comment by hyl87** [comment]
![image](https://user-images.githubusercontent.com/1303038/84261468-63e56c00-ab4e-11ea-8d0f-6544034f233b.png)
![image](https://user-images.githubusercontent.com/1303038/84261501-6fd12e00-ab4e-11ea-9836-367ccd88a9e7.png)

**Comment by hyl87** [comment]
点击的时候 触发的断点截图,

**Comment by donkingliang** [comment]
让我看一下你的布局是怎么写的。你的RecyclerView或者ConsecutiveScroller是不是写了固定高度啊。滑动的view的高度要么设置wrap_content，要么设置match_parent

**Comment by hyl87** [comment]
![image](https://user-images.githubusercontent.com/1303038/84263130-7d3be780-ab51-11ea-8968-ba3e1c05d3fc.png)

**Comment by hyl87** [comment]
里面其他的布局都不是滚动的

**Comment by donkingliang** [comment]
那你说的recyclerview是那个，是在那里的？

**Comment by hyl87** [comment]
在fragment里面,高度也没有写死 是 march_parent

**Comment by donkingliang** [comment]
让我看一下你的fragment布局

**Comment by hyl87** [comment]
<androidx.recyclerview.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/rvDynamicList"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    android:paddingTop="20dp" />
就这一个

**Comment by donkingliang** [comment]
你加一下我QQ吧：1043214265
