### ISSUE TITLE
是否有api支持，禁用滑动的？

### ISSUE THREAD

**Issue by pengjunhong** [donkingliang/ConsecutiveScroller#72]
现在有这样一个场景，ConsecutiveScroller 包裹 webview ，webview中有视频，然后点击切换全屏，会出现滚动。

**Comment by donkingliang** [comment]
没有。你可以试一下下载代码，注释掉onLayout方法中的checkLayoutChange这句代码，这句代码是在布局发生变化时调整滑动位置的。我估计是切换全屏时布局发生改变，所以出现滚动。
