### ISSUE TITLE
部分机型最后一个RecyclerView的最后一条数据展示不完全,请进来帮忙看看

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#74]
设置了recyclerview的这两个属性也无效       mcRecyclerView.setHasFixedSize(true);
        mRecyclerView.setNestedScrollingEnabled(false);
我的布局是这样的:
  <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tl_home">
		
		......其他布局
		
		   <androidx.recyclerview.widget.RecyclerView
                android:layout_marginTop="8dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_constraintTop_toBottomOf="@id/tv_temp_ten" />
				
				   <androidx.recyclerview.widget.RecyclerView
                android:layout_marginTop="8dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_constraintTop_toBottomOf="@id/tv_temp_ten" />

  
        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:visibility="visible"
            android:background="@color/white">

            <TextView
                android:id="@+id/tv_temp_ten"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="12dp"
                android:text="推荐个人服务商"
                android:textColor="#222222"
                android:textSize="16dp"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/tv_home_personal_service_more"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:drawableRight="@mipmap/right_arrow_small"
                android:padding="12dp"
                android:text="查看更多"
                android:textColor="#666666"
                android:textSize="13dp"
                app:layout_constraintBottom_toBottomOf="@id/tv_temp_ten"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="@id/tv_temp_ten" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_home_personal_service"
                android:layout_marginTop="8dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_constraintTop_toBottomOf="@id/tv_temp_ten" />

        </androidx.constraintlayout.widget.ConstraintLayout>
		
 </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
你最后一个RecyclerView是rv_home_personal_service吗？你要把RecyclerView嵌套在ConsecutiveScrollerLayout下，不能嵌套在子view下。也就是说，滑动布局不能多层嵌套。

**Comment by roybill** [comment]
是的,最后一个就是rv_home_personal_service.我要嵌套父容器的原因是这个库的直接子类不能直接设置margin,需要有父容器才可以设置.感觉不能设置margin很难受,能不能加上这个功能呢???

**Comment by donkingliang** [comment]
可以设置左右margin，不能设置上下margin，因为设置上下margin布局显示会断层，而且滑动计算会有冲突。我在文档有写解决方案的，使用Space效果是一样的

**Comment by roybill** [comment]
我试了一下,为什么这样直接设置左右marginLeft无效呢?
  <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout

   <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_home_personal_service"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="20dp"
            android:layout_marginTop="8dp" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
