### ISSUE TITLE
ViewPager +fragment，fragment中是recyclerview 功能是可以LoadMore

### ISSUE THREAD

**Issue by zhangshuyang88** [donkingliang/ConsecutiveScroller#75]
作者你好，我的问题是当我给fragment中的recyclerview设置LoadMore时候，我的fragment跟布局设置成ConsecutiveScrollerlayout，在嵌套smart 刷新，刷新里面是recyclerview 这种，问题是条目没有显示全，不能LoadModre，这种情况咱们应该怎么处理呢

**Comment by donkingliang** [comment]
看文档最后的注意事项，SmartRefreshLayout等刷新框架只能最嵌套在外层，不能嵌套在里面。

**Comment by zhangshuyang88** [comment]
嗯嗯，我看到那块的文档啦，我问题没有说清楚，重新和你说下哈，我现在布局是一个商城的首页，最上层是一个banner，下面是一个九宫格，在下面是一个tablayout+viewpager，整个布局可以下拉刷新，tabLayout 吸顶。viewpager+fragment 展示不同的列表，需要有一个LoadMore， 我如果大布局用咱们ConsecutiveScrollerlayout，viewpager 中里面如果要LoadMore列表滑不到底部，就不能LoadMore了，有啥方式能解决这个种情况嘛～谢谢🙏

**Comment by donkingliang** [comment]
你使用的ViewPager是ConsecutiveViewPager吗？

**Comment by donkingliang** [comment]
另外你ViewPager 里的fragment要LoadMore，也不能使用SmartRefreshLayout，因为它也是嵌套在里面的。

**Comment by zhangshuyang88** [comment]
嗯嗯，是的，用的是ConsecutiveViewPager，那这种情况的话有啥方式解决这种情况嘛

**Comment by zhangshuyang88** [comment]
如果放在大布局刷新哒话，就是在LoadMore的时候LoadMore的布局会把吸顶顶上去，这种方式咱们有没有好的解决办法呀～谢谢🙏

**Comment by donkingliang** [comment]
如果你想让里面的RecyclerView也能LoadMore，可以使用非嵌套布局的加载方式，比如BaseQuickAdapter的加载更多功能。

**Comment by zhangshuyang88** [comment]
奥奥，好的，我试一下～非常感谢🙏
