### ISSUE TITLE
请问作者,如何能够获取到ConsecutiveScroller子布局中的view是否可见呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#76]
我这样不行,值一直未变
1.布局:
   <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/csl_home"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        
        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:visibility="visible">

			
            <com.to.aboomy.banner.Banner
                android:id="@+id/banner_home_top"
                android:layout_width="match_parent"
                android:layout_height="170dp"
                app:layout_constraintTop_toTopOf="parent" />

            <View
                android:id="@+id/view_temp"
                android:layout_width="match_parent"
                android:layout_height="1dp"
                app:layout_constraintBottom_toBottomOf="@id/banner_home_top" />

            <TextView
                android:layout_width="match_parent"
                android:layout_height="30dp"
                app:layout_constraintTop_toBottomOf="@id/banner_home_top" />
				
				 
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_home_tender_project"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:visibility="visible" />
			
			     </androidx.constraintlayout.widget.ConstraintLayout>
				 
   </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

2.代码:
        mScrollerLayout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY) {
                ConstraintLayout constraintLayout = (ConstraintLayout) mScrollerLayout.getChildAt(0);
                Banner banner = (Banner) constraintLayout.getChildAt(0);
                int visibility = banner.getVisibility();  //一直为0
                boolean shown = banner.isShown();       //一直为true
                boolean b = banner.hasWindowFocus();    //一直为true
                LogUtils.d("1043  "+b+"   banner"+banner);
            }
        });

**Comment by donkingliang** [comment]
如果你的Banner是第一个view，你可以这样判断：
scrollerLayout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY) {
                if (scrollerLayout.findFirstVisibleView() == banner){
                    // 显示在屏幕
                } else {
                    // 滑动出屏幕
                }
            }
        });

或者通过findFirstVisibleView()、findLastVisibleView()或者第一个显示在屏幕的view和最后一个显示在屏幕的view，判断你的view是否在这个范围。通过indexOfChild方法获取下标

**Comment by roybill** [comment]
谢谢,我现在根据高度去判断搞定了,如果滑动的距离超过了第一张banner的高度表示不可见:
        mScrollerLayout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY) {
                Banner banner = view.findViewById(R.id.banner_home_top);
                int height = banner.getHeight();//顶部轮播图的高度
//                LogUtils.d("1106  scroY= " + scrollY + "    oldS=" + oldScrollY + "   height" + height);
                if (scrollY > height) {
//                    LogUtils.d("1108  顶部轮播图不可见");
                    toolbar.setBackgroundColor(Color.parseColor("#FE7D01"));
                } else {
//                    LogUtils.d("1108  顶部轮播图可见");
                    toolbar.setBackgroundColor(Color.parseColor("#00000000"));
                }
            }
        });
