### ISSUE TITLE
recyclerview显示不全

### ISSUE THREAD

**Issue by Alexxiaopang** [donkingliang/ConsecutiveScroller#77]
ConsecutiveScrollerLayout 是最外层，
结构是：
ConsecutiveScrollerLayout
      其他组件
      吸顶布局
      recyclerview
      吸顶布局
      recyclerview
      吸顶布局
      recyclerview
ConsecutiveScrollerLayout
里面的吸顶或者rv都来自不同接口，有可能会没数据时候隐藏，当rv数据少时候，会显示不全

**Comment by donkingliang** [comment]
你的rv高度是wrap_content吗？显示不全是什么情况，是滑动不到底部吗？
