### ISSUE TITLE
任何margin都无效,上次说是marleft可以,我试了确实无效,请看布局

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#78]
一定要嵌套一个父容器才行,这样太难受了,可以优化一下吗?

 <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        
        <TextView
            android:layout_marginTop="50dp"
            android:layout_width="match_parent"
            android:layout_marginLeft="50dp"
            android:text="1111111111"
            android:layout_height="wrap_content"/>

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <EditText
                android:id="@+id/et_home_search"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="12dp"
                android:layout_marginRight="12dp"
                android:background="@drawable/topic_search_shape"
                android:drawableLeft="@mipmap/search"
                android:drawablePadding="10dp"
                android:hint="请输入搜索内容"
                android:padding="10dp"
                android:singleLine="true"
                android:textCursorDrawable="@null"
                android:textSize="14dp" />

        </FrameLayout>

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_easy_tender_type"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
        
        <Space
            android:layout_width="match_parent"
            android:layout_height="20dp"/>

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
layout_marginTop和layout_marginBottom不行，其他的是可以的。你的layout_marginLeft无效，是不是你使用的还是旧的版本啊？

**Comment by roybill** [comment]
我用的是2.5.0,    implementation 'com.github.donkingliang:ConsecutiveScroller:2.5.0'   . 我试试最新的
