### ISSUE TITLE
如果是RecyclerView的每个Item都是RecyclerView呢？

### ISSUE THREAD

**Issue by ujffdi** [donkingliang/ConsecutiveScroller#79]
是否支持

**Comment by donkingliang** [comment]
支持。不过如果你的item也是垂直的RecyclerView，我建议你不要这样做，RecyclerView嵌套RecyclerView性能会很差的。可以使用分组的RecyclerView，一个RecyclerView显示多个二级列表。
https://github.com/donkingliang/GroupedRecyclerViewAdapter

**Comment by ujffdi** [comment]
RecyclerView的item是个水平滑动的RecyclerView。滑动水平的RecyclerView并不是很灵敏。层级如下
ConsecutiveScrollerLayout 
---ConsecutiveViewPager
-----垂直RecyclerView 
-------item 是水平滑动的RecyclerView
然后把以上层级做个修改，就没什么什么问题
ConsecutiveScrollerLayout 
---ConsecutiveViewPager
-----水平滑动的RecyclerView

**Comment by donkingliang** [comment]
垂直RecyclerView嵌套水平RecyclerView，水平的RecyclerView是有可能会出现滑动不灵敏的，这是RecyclerView的滑动问题，你可以网上搜索一下有没有解决的方案。
