### ISSUE TITLE
子View中有ViewPager,但是ViewPager内的Fragment内容显示不全该如何解决呢?

### ISSUE THREAD

**Issue by roybill** [donkingliang/ConsecutiveScroller#81]
布局是这样的:

  <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:orientation="vertical"
        app:layout_constraintBottom_toTopOf="@id/cl_bottom"
        app:layout_constraintTop_toBottomOf="@id/tl_enterprise_provider">
		
		  <TextView
            android:text="内容"
            android:layout_width="match_parent"
            android:layout_height="100dp"/>

       <com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/stl_enterprise_provider"
            android:layout_width="match_parent"
            android:layout_height="41dp"
            app:layout_isSticky="true"
            android:background="#ffffff"
            app:tl_indicator_color="#FE7D01"
            app:tl_indicator_width="30dp"
            app:tl_textSelectColor="#222222"
            app:tl_textUnselectColor="#444444" />

			
        <androidx.viewpager.widget.ViewPager
            android:id="@+id/vp_enterprise_provider"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
ViewPager有使用库里的ConsecutiveViewPager，Fragment的根布局要使用ConsecutiveScrollerLayout或者其他滑动的view。

文档里有这些介绍。

**Comment by roybill** [comment]
感谢解答,已经搞定了,之前是直接引入就开始用了,我还是仔细看一遍这里的所有使用说明吧,避免反复再提问这些已有的功能了   :)
