### ISSUE TITLE
瀑布流样式不显示数据

### ISSUE THREAD

**Issue by qidianli** [donkingliang/ConsecutiveScroller#82]
给recycleview设置了layoutManager.setGapStrategy(StaggeredGridLayoutManager.GAP_HANDLING_NONE);后直接不显示数据了，害我找了半天

**Comment by qidianli** [comment]
而且滑动的很慢很卡，如果不加上述的方法会瀑布流会有闪动

**Comment by donkingliang** [comment]
数据不显示是因为你的RecyclerView设置了wrap_content吧。设置StaggeredGridLayoutManager.GAP_HANDLING_NONE时，本来就是wrap_content是不显示的

**Comment by qidianli** [comment]
我这边设置了这个wrap_content之前是可以的，我如果设置了match那就全屏了，我现在换成了百度的可以了，我发现用你这个控件的时候那个scrollbar的小条目一直在抖动，很卡的感觉，我的布局很简单是两个recycleview

**Comment by donkingliang** [comment]
recycleview的item是多类型或者各个item高度不一样时，scrollbar就会在滑动是动态变化。你用原生的recycleview的scrollbar也会这样
