### ISSUE TITLE
setOnVerticalScrollChangeListener 方法 可以把滑动状态返回么?

### ISSUE THREAD

**Issue by inshyma** [donkingliang/ConsecutiveScroller#83]
sdk version: 3.6.2

The updated scroll state. One of {@link #SCROLL_STATE_IDLE},
      {@link #SCROLL_STATE_DRAGGING} or {@link #SCROLL_STATE_SETTLING}.
case: 外部ConsecutiveScroller 把我里面的RecyclerView 的事件拦截了 
设置layout_isConsecutive false  不是我想要的

**Comment by donkingliang** [comment]
多谢反馈，我后面会把这个状态加上。
