### ISSUE TITLE
有没有方法支持滑动到某个view顶部的

### ISSUE THREAD

**Issue by 643063150** [donkingliang/ConsecutiveScroller#84]
有没有方法支持滑动到某个view顶部的  使用scrollto(view) 在页面足够长的时候只能把view显示在屏幕中央，使用scrollby(x,y) 传入v.getx,v.gety只会轻微滑动一下，scrollto也一样，不知道是不是因为v.gety获取到的值不正确

**Comment by donkingliang** [comment]
scrollToChild和smoothScrollToChild，滑动到指定子view的顶部

**Comment by 643063150** [comment]
scrollToChild就是我说的只能把view显示在中央的，smoothScrollToChild 可以正常到底部，但是有动画

**Comment by donkingliang** [comment]
发一下你的代码，我看一下

**Comment by 643063150** [comment]
scrollerLayout.scrollToChild(contentList);

**Comment by 643063150** [comment]
![caogou](https://user-images.githubusercontent.com/11732536/85244474-5c3f9480-b477-11ea-81ef-4435ffbf04b1.gif)

**Comment by 643063150** [comment]
scrollerLayout.smoothScrollToChild(contentList);
![caogous](https://user-images.githubusercontent.com/11732536/85244581-b0e30f80-b477-11ea-97bf-24239429d7a4.gif)

**Comment by 643063150** [comment]
在真机上效果一致  真机是华为畅享9Plus  9.0的系统

**Comment by donkingliang** [comment]
你是点击跳转就调用scrollToChild滑动布局吗？应该是因为你滑动布局的时候，上面的WebView加载还没完成，导致滑动的距离跟WebView的实际高度不对，你应该让WebView加载完成后在调用scrollToChild滑动，延迟一下，保证WebView的高度已经加载完成。

**Comment by 643063150** [comment]
我是在webview加载完成后再加载recyleview的 而且是在recyle刷新后才调用的` webView.setWebViewClient(new WebViewClient() {
            @Override
            public void onPageFinished(WebView view, String url) {
                mPresenter.getCommentList(id, PAGE_NUM);
                super.onPageFinished(view, url);
            }`

`  setData(isRefresh, commentEnerty.getData().getList());
       scrollerLayout.smoothScrollToChild(contentList);   `

**Comment by 643063150** [comment]
> 我是在webview加载完成后再加载recyleview的 而且是在recyle刷新后才调用的` webView.setWebViewClient(new WebViewClient() { @Override public void onPageFinished(WebView view, String url) { mPresenter.getCommentList(id, PAGE_NUM); super.onPageFinished(view, url); }`
> 
> ` setData(isRefresh, commentEnerty.getData().getList()); scrollerLayout.smoothScrollToChild(contentList); `
scrollerLayout.scrollToChild(contentList);也是在这个位置调用的

**Comment by donkingliang** [comment]
你调用scrollToChild时，延时一下试一下。比如：
webView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        scrollerLayout.scrollToChild(contentList);
                    }
                },500);
因为页面在加载数据的时候，view的高度可能是确定的
