### ISSUE TITLE
RecyclerView内使用Glide加载图片无法显示问题

### ISSUE THREAD

**Issue by w296365959** [donkingliang/ConsecutiveScroller#85]
`    Glide.with(mContext)
                    .asBitmap()
                    .load((String)itemData)
                    .into(new SimpleTarget<Bitmap>() {
                        @Override
                        public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                            int imageWidth = resource.getWidth();
                            int imageHeight = resource.getHeight();

                            //宽度固定,然后根据原始宽高比得到此固定宽度需要的高度
                            int height = screenWidth * imageHeight / imageWidth;
                            ViewGroup.LayoutParams para = mImageView.getLayoutParams();
                            para.height = height;
                            para.width = screenWidth;
                            mImageView.setImageBitmap(resource);
                        }
                    });`
RecyclerView 显示图片列表，对图片宽高重新设置后，无法显示

**Comment by w296365959** [comment]
后面使用重写ImageView的onMeasure `  @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec){
        Drawable d = getDrawable();

        if(d!=null){
            // ceil not round - avoid thin vertical gaps along the left/right edges
            int width = MeasureSpec.getSize(widthMeasureSpec);
            //高度根据使得图片的宽度充满屏幕计算而得
            int height = (int) Math.ceil((float) width * (float) d.getIntrinsicHeight() / (float) d.getIntrinsicWidth());
            setMeasuredDimension(width, height);
        }else{
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        }
    }` 
这样会出现，图片滑动过程闪烁现象

**Comment by donkingliang** [comment]
多谢反馈，是RecyclerView 的item高度滑动是动态变化，引起的闪烁，这个问题我后面会优化一下。
至于Glide加载图片无法显示，我这边没有重现到，不知道是什么原因引起的。
