### ISSUE TITLE
关于TabLayout+ConsecutiveViewPager +Fragment 使用问题

### ISSUE THREAD

**Issue by JiayuanChan** [donkingliang/ConsecutiveScroller#86]
ConsecutiveScrollerLayout最底部使用 TabLayout+ConsecutiveViewPager +Fragment，Fragment布局文件如下
`<?xml version="1.0" encoding="utf-8"?>
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">
    <cn.qingtui.xrb.board.ui.widget.ConsecutiveLinearLayout
        android:id="@+id/cfl_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:background="@android:color/white"
            android:clipToPadding="false" />
        <LinearLayout
            android:id="@+id/ll_comment_entrance"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:background="@android:color/transparent"
            android:orientation="vertical">
            <View
                android:layout_width="match_parent"
                android:layout_height="1px"
                android:background="#17030E2C" />
            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="start|center_vertical"
                android:paddingLeft="20dp"
                android:text="添加评论或@成员"
                android:textColor="#40030E2C"
                android:textSize="16dp" />
        </LinearLayout>
    </cn.qingtui.xrb.board.ui.widget.ConsecutiveLinearLayout>
</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>`
RecyclerView充满一屏数据时，最后一条数据总是会被遮挡一部分，请问改怎么解决这个问题呢？

**Comment by JiayuanChan** [comment]
布局文件
![image](https://user-images.githubusercontent.com/18372409/85352451-945adc00-b538-11ea-8f1a-cef80b85eb86.png)

效果图
![Screenshot_20200623_100905_com cisdi banli debug](https://user-images.githubusercontent.com/18372409/85352916-ac7f2b00-b539-11ea-9450-7b033f42108c.jpg)

**Comment by JiayuanChan** [comment]
ConsecutiveLinearLayout 的代码
![image](https://user-images.githubusercontent.com/18372409/85353052-f49e4d80-b539-11ea-92ed-f9b683adf0bb.png)

**Comment by donkingliang** [comment]
你应该去掉ConsecutiveLinearLayout这一层。RecyclerView的高度需要跟父布局的高度一样，才能正常滑动，所以你这样写是不行的，底部的ll_comment_entrance占据的一点空间，RecyclerView就不能充满全屏了。如果你一定要让ll_comment_entrance固定在底部，你可以自定义ConsecutiveFrameLayou，然后让RecyclerView的高度占满全屏的同时，底部paddingBottom 48dp，这样ll_comment_entrance就不会遮挡到RecyclerView的item了

**Comment by JiayuanChan** [comment]
是这样吗？我试了还是不得行
```
<?xml version="1.0" encoding="utf-8"?>
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical">
    <cn.qingtui.xrb.board.ui.widget.ConsecutiveFrameLayout
        android:id="@+id/cfl_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/white"
            android:paddingBottom="48dp"
            android:clipToPadding="false" />
        <LinearLayout
            android:id="@+id/ll_comment_entrance"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:layout_gravity="bottom"
            android:background="@android:color/transparent"
            android:orientation="vertical">
            <View
                android:layout_width="match_parent"
                android:layout_height="1px"
                android:background="#17030E2C" />
            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="start|center_vertical"
                android:paddingLeft="20dp"
                android:text="添加评论或@成员"
                android:textColor="#40030E2C"
                android:textSize="16dp" />
        </LinearLayout>
    </cn.qingtui.xrb.board.ui.widget.ConsecutiveFrameLayout>
</com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
```

**Comment by donkingliang** [comment]
还是会挡住底部吗？给我看一下你的ConsecutiveFrameLayout代码

**Comment by JiayuanChan** [comment]
![image](https://user-images.githubusercontent.com/18372409/85356822-814d0980-b542-11ea-854c-9ab4124a6d5d.png)
我写的是不是有问题

**Comment by donkingliang** [comment]
这样写没有问题啊。是RecyclerView滑不动，还是ll_comment_entrance挡住了RecyclerView的下面item？

**Comment by JiayuanChan** [comment]
还是ll_comment_entrance挡住了RecyclerView的下面item

**Comment by donkingliang** [comment]
![image](https://user-images.githubusercontent.com/5499532/85357813-c6723b00-b544-11ea-9fba-021577c6ffcb.png)
你这样写，不用paddingBottom

**Comment by JiayuanChan** [comment]
[试了一下，和之前我发的被遮挡的那种方式，这个实现卡顿比较明显，没有那么流畅。当往下滑的时候，到TabLayout的时候，会明显感觉顿一下，再次滑的时候才能继续往下滑。
[SVID_20200623_121240_1.mp4.zip](https://github.com/donkingliang/ConsecutiveScroller/files/4817119/SVID_20200623_121240_1.mp4.zip)

**Comment by donkingliang** [comment]
你下载代码，使用paddingBottom="48dp"试一下。不用再嵌套一层ConsecutiveScrollerLayout。我昨天修改了paddingBottom的bug了

**Comment by JiayuanChan** [comment]
试了下，可以了。但是会有另一个问题，滑起来不流畅，而且RecyclerView 的Item高度有时候还会有问题。我把你的代码拷贝到本地，将 ConsecutiveViewPager 中的 addView 你加的代码去掉后就不会有问题。
能加一个QQ微信啥的吗，有问题好描述一些
[SVID_20200624_110639_1.mp4.zip](https://github.com/donkingliang/ConsecutiveScroller/files/4823011/SVID_20200624_110639_1.mp4.zip)

**Comment by donkingliang** [comment]
QQ：1043214265

**Comment by JiayuanChan** [comment]
已添加。
在这个 RecyclerView 数据充满一屏的时候，我删除一条数据、插入一条数据，都会失败。有时候还会崩溃

![image](https://user-images.githubusercontent.com/18372409/85502443-e58ecc80-b619-11ea-97b2-066d19efaa41.png)
