### ISSUE TITLE
请问点击某个按钮随意滚动到recyclerview的某个指定条目，让这个条目显示在最顶层，该如何做？

### ISSUE THREAD

**Issue by MageLin** [donkingliang/ConsecutiveScroller#87]

**Comment by donkingliang** [comment]
ConsecutiveScroller没有提供方法滑动到recyclerview的某个指定条目，只有滑动到子view的方法：scrollToChild、smoothScrollToChild。但是你可以先调用scrollToChild滑动recyclerview到顶部，在调用recyclerview的scrollToPosition滑动到指定的条目。

**Comment by MageLin** [comment]
不幸的是，没有效果，大佬可以试一下

**Comment by donkingliang** [comment]
是没有把对应的item滑到顶部吧。因为scrollToPosition方法只能保证把item滑到可见区域，不能保证滑到顶部的。如果你要保证包item滑到顶部，要使用LinearLayoutManager的scrollToPositionWithOffset(position,offset)方法。offset传0即可
