### ISSUE TITLE
ConsecutiveScrollerLayout中嵌套ConsecutiveViewPager，ConsecutiveViewPager中嵌套一个使用SmartRefreshLayout加载更多的recyclerview

### ISSUE THREAD

**Issue by LunHongShao** [donkingliang/ConsecutiveScroller#88]
![image](https://user-images.githubusercontent.com/17739223/85950053-042ff300-b98d-11ea-8626-72fa24d722f9.png)
我安装文档说的，将SmartRefreshLayout放在最外层，在SmartRefreshLayout中嵌套一个ConsecutiveScrollerLayout，在ConsecutiveScrollerLayout再嵌套一个RecyclerView，此时不能上拉加载更多，也不能下拉刷新

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout中嵌套ConsecutiveViewPager，ConsecutiveViewPager嵌套SmartRefreshLayout。SmartRefreshLayout还是在ConsecutiveScrollerLayout内部的，所以不能这样嵌套。SmartRefreshLayout必须时在最外层才有效。
