### ISSUE TITLE
滑动到底部的时候它自动往上缩了

### ISSUE THREAD

**Issue by Heshuhao** [donkingliang/ConsecutiveScroller#89]
<?xml version="1.0" encoding="utf-8"?>
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/mRefreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/common_white"
        android:orientation="vertical"
        app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior">

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_8" />

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/dp_10"
            android:layout_marginRight="@dimen/dp_10">

            <com.youth.banner.Banner
                android:id="@+id/mBanner"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_120" />

        </FrameLayout>

        <com.limitedtec.baselibrary.widgets.ShadowLayout
            android:id="@+id/item_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_marginLeft="@dimen/dp_5"
            android:layout_marginTop="@dimen/dp_8"
            android:layout_marginRight="@dimen/dp_5"
            android:background="@color/common_white"
            app:yc_bottomShow="true"
            app:yc_cornerRadius="@dimen/dp_5"
            app:yc_dx="0dp"
            app:yc_dy="0dp"
            app:yc_leftShow="true"
            app:yc_rightShow="true"
            app:yc_shadowColor="@color/default_shadow_color"
            app:yc_shadowLimit="@dimen/dp_5"
            app:yc_topShow="false">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/bg_radius_white_ds"
                android:orientation="vertical">

                <com.limitedtec.baselibrary.widgets.CustomNoTouchRecyclerView
                    android:id="@+id/rv_label"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingTop="@dimen/dp_5"
                    android:paddingBottom="@dimen/dp_5" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/dp_40"
                    android:gravity="center_vertical"
                    android:paddingLeft="@dimen/dp_10"
                    android:paddingRight="@dimen/dp_10">

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center_vertical"
                        android:orientation="horizontal">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="无界事件"
                            android:textColor="@color/main_color_333333"
                            android:textSize="@dimen/dp_14"
                            android:textStyle="bold" />

                        <ImageView
                            android:layout_width="@dimen/dp_8"
                            android:layout_height="@dimen/dp_8"
                            android:layout_marginLeft="@dimen/dp_4"
                            android:layout_marginRight="@dimen/dp_4"
                            android:src="@drawable/yuan_logo" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="最新"
                            android:textColor="@color/main_color"
                            android:textSize="@dimen/dp_14"
                            android:textStyle="bold" />

                    </LinearLayout>

                    <ViewFlipper
                        android:id="@+id/vf_notice"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="@dimen/dp_5"
                        android:layout_marginRight="@dimen/dp_5"
                        android:layout_weight="1"
                        android:inAnimation="@anim/vf_anim_in"
                        android:outAnimation="@anim/vf_anim_out" />

                </LinearLayout>

            </LinearLayout>

        </com.limitedtec.baselibrary.widgets.ShadowLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_218"
            android:layout_marginLeft="@dimen/dp_10"
            android:layout_marginTop="@dimen/dp_10"
            android:layout_marginRight="@dimen/dp_10"
            android:orientation="horizontal"
            android:visibility="visible">

            <RelativeLayout
                android:id="@+id/ll_new_people"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:scaleType="centerCrop"
                    android:src="@drawable/icon_index_xrfl" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="新人福利"
                        android:textColor="@color/main_color_333333"
                        android:textSize="@dimen/dp_14"
                        android:textStyle="bold" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="100%成功参团"
                        android:textColor="@color/main_color_666666"
                        android:textSize="@dimen/dp_12" />

                </LinearLayout>

            </RelativeLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_marginLeft="@dimen/dp_8"
                android:layout_weight="1"
                android:orientation="vertical">

                <RelativeLayout
                    android:id="@+id/ll_High_commission"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="1"
                    android:orientation="vertical">

                    <ImageView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:adjustViewBounds="true"
                        android:scaleType="centerCrop"
                        android:src="@drawable/icon_index_gysp" />

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="@dimen/dp_10"
                        android:orientation="vertical">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="高佣商品"
                            android:textColor="@color/main_color_333333"
                            android:textSize="@dimen/dp_14"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="赚钱更容易"
                            android:textColor="@color/main_color_666666"
                            android:textSize="@dimen/dp_12" />

                    </LinearLayout>

                </RelativeLayout>

                <RelativeLayout
                    android:id="@+id/ll_Direct_supply"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_marginTop="@dimen/dp_8"
                    android:layout_weight="1"
                    android:orientation="vertical">

                    <ImageView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:adjustViewBounds="true"
                        android:scaleType="centerCrop"
                        android:src="@drawable/icon_index_gczg" />

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="@dimen/dp_10"
                        android:orientation="vertical">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="工厂直供"
                            android:textColor="@color/main_color_333333"
                            android:textSize="@dimen/dp_14"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center"
                            android:text="大牌出厂价"
                            android:textColor="@color/main_color_666666"
                            android:textSize="@dimen/dp_12" />

                    </LinearLayout>

                </RelativeLayout>

            </LinearLayout>

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_120"
            android:layout_marginLeft="@dimen/dp_10"
            android:layout_marginTop="@dimen/dp_10"
            android:layout_marginRight="@dimen/dp_10"
            android:background="@drawable/bg_radius_white_ds"
            android:orientation="horizontal">

            <RelativeLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/dp_10"
                android:layout_weight="1"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:scaleType="centerCrop"
                    android:src="@drawable/icon_index_hhzb" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_marginLeft="@dimen/dp_10"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="好货直播"
                        android:textColor="@color/common_white"
                        android:textSize="@dimen/dp_14"
                        android:textStyle="bold" />

                    <View
                        android:layout_width="@dimen/dp_40"
                        android:layout_height="@dimen/dp_4"
                        android:layout_marginTop="@dimen/dp_4"
                        android:background="@color/common_white" />

                </LinearLayout>

            </RelativeLayout>

            <RelativeLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_marginLeft="@dimen/dp_8"
                android:layout_marginTop="@dimen/dp_10"
                android:layout_weight="1"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/iv_billions_subsidies"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:scaleType="centerCrop"
                    android:src="@drawable/icon_index_bybt" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_marginLeft="@dimen/dp_10"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="百亿补贴"
                        android:textColor="@color/common_white"
                        android:textSize="@dimen/dp_14"
                        android:textStyle="bold" />

                    <View
                        android:layout_width="@dimen/dp_40"
                        android:layout_height="@dimen/dp_4"
                        android:layout_marginTop="@dimen/dp_4"
                        android:background="@color/common_white" />

                </LinearLayout>

            </RelativeLayout>

        </LinearLayout>

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabLayout"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_40"
            android:layout_marginBottom="@dimen/dp_10"
            android:background="@color/common_white"
            app:layout_isSticky="true"
            app:tabIndicatorColor="@color/main_color"
            app:tabIndicatorFullWidth="false"
            app:tabIndicatorHeight="2dp"
            app:tabMode="fixed"
            app:tabPaddingEnd="10dp"
            app:tabPaddingStart="10dp"
            app:tabRippleColor="@color/transparent"
            app:tabSelectedTextColor="@color/main_color"
            app:tabTextColor="@color/main_color_333333" />

  
        <com.donkingliang.consecutivescroller.ConsecutiveViewPager
            android:id="@+id/vp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/common_white"
            android:orientation="horizontal" />

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

</com.scwang.smartrefresh.layout.SmartRefreshLayout>

com.donkingliang.consecutivescroller.ConsecutiveViewPager  里面是RecyclerView  滑动到底部的时候它自动往上缩了下是为什么

**Comment by donkingliang** [comment]
你说的自动往上缩了下是什么情况。是布局自动推上去，回弹吗？如果是吸顶头部被推上去了，你可以设置吸顶便宜，让它固定
refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
    @Override
    public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
        // 上拉加载时，保证吸顶头部不被推出屏幕。
        // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
        scrollerLayout.setStickyOffset(offset);
    }
});

**Comment by zhangnianxiang** [comment]
> 你说的自动往上缩了下是什么情况。是布局自动推上去，回弹吗？如果是吸顶头部被推上去了，你可以设置吸顶便宜，让它固定
> refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
> @override
> public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
> // 上拉加载时，保证吸顶头部不被推出屏幕。
> // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
> scrollerLayout.setStickyOffset(offset);
> }
> });

![image](https://user-images.githubusercontent.com/4082398/86547480-c5d99b80-bf6b-11ea-9da9-a489484851fc.png)
![image](https://user-images.githubusercontent.com/4082398/86547505-d4c04e00-bf6b-11ea-8cce-47ced6e97bdf.png)

感觉题主遇到的问题应该跟我一样，就是下面一个viewpager，viewpager内部有recycleview的时候，到底部上啦的时候，会带上一片空白区域。

**Comment by Heshuhao** [comment]
> > 你说的自动往上缩了下是什么情况。是布局自动推上去，回弹吗？如果是吸顶头部被推上去了，你可以设置吸顶便宜，让它固定
> > refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
> > @override
> > public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
> > // 上拉加载时，保证吸顶头部不被推出屏幕。
> > // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
> > scrollerLayout.setStickyOffset(offset);
> > }
> > });
> 
> ![image](https://user-images.githubusercontent.com/4082398/86547480-c5d99b80-bf6b-11ea-9da9-a489484851fc.png)
> ![image](https://user-images.githubusercontent.com/4082398/86547505-d4c04e00-bf6b-11ea-8cce-47ced6e97bdf.png)
> 
> 感觉题主遇到的问题应该跟我一样，就是下面一个viewpager，viewpager内部有recycleview的时候，到底部上啦的时候，会带上一片空白区域。

对的我的也是这样。会带上一片空白区域。

**Comment by Heshuhao** [comment]
> 你说的自动往上缩了下是什么情况。是布局自动推上去，回弹吗？如果是吸顶头部被推上去了，你可以设置吸顶便宜，让它固定
> refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
> @override
> public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
> // 上拉加载时，保证吸顶头部不被推出屏幕。
> // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
> scrollerLayout.setStickyOffset(offset);
> }
> });

我可能题目没说太清楚，就是，滑动最底部的时候他会往下自动回弹一下，然后遮住一点item

**Comment by donkingliang** [comment]
> > 你说的自动往上缩了下是什么情况。是布局自动推上去，回弹吗？如果是吸顶头部被推上去了，你可以设置吸顶便宜，让它固定
> > refreshLayout.setOnMultiPurposeListener(new SimpleMultiPurposeListener() {
> > @override
> > public void onFooterMoving(RefreshFooter footer, boolean isDragging, float percent, int offset, int footerHeight, int maxDragHeight) {
> > // 上拉加载时，保证吸顶头部不被推出屏幕。
> > // 如果你本身就设置了吸顶偏移量，那么这里的offset计算你的偏移量加offset
> > scrollerLayout.setStickyOffset(offset);
> > }
> > });
> 
> ![image](https://user-images.githubusercontent.com/4082398/86547480-c5d99b80-bf6b-11ea-9da9-a489484851fc.png)
> ![image](https://user-images.githubusercontent.com/4082398/86547505-d4c04e00-bf6b-11ea-8cce-47ced6e97bdf.png)
> 
> 感觉题主遇到的问题应该跟我一样，就是下面一个viewpager，viewpager内部有recycleview的时候，到底部上啦的时候，会带上一片空白区域。

你的recycleview的内容是不是不满一屏啊。因为viewpager是占满一屏的，所以内容不满一屏时下面空白，是正常的。如果viewpager满一屏而recycleview不满一屏，recycleview高度可以设置为wrap_content

**Comment by donkingliang** [comment]
能加一下我的QQ，让我看一下你们的布局文件吗？ 1043214265
