### ISSUE TITLE
如何判断是否滚动完成

### ISSUE THREAD

**Issue by Dearyu** [donkingliang/ConsecutiveScroller#91]
如何判断是否滚动完成

**Comment by donkingliang** [comment]
setOnVerticalScrollChangeListener监听器有个scrollState参数，scrollState == ConsecutiveScrollerLayout.SCROLL_STATE_IDLE表示滑动停止

**Comment by Dearyu** [comment]
> setOnVerticalScrollChangeListener监听器有个scrollState参数，scrollState == ConsecutiveScrollerLayout.SCROLL_STATE_IDLE表示滑动停止

3.7.0版本支持了 看到了 之前是老版本
