### ISSUE TITLE
布局如下，嵌套2个recyclerview时，当下面的recyclerview数据超过一个屏幕，上面的recyclerview就会被移出屏幕外面。

### ISSUE THREAD

**Issue by pengjunhong** [donkingliang/ConsecutiveScroller#93]
<com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/scrollerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_toplist"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

        <TextView
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_68"
            android:paddingLeft="@dimen/dp_30"
            android:gravity="center_vertical"
            android:text="请到系统设置里更改消息通知"
            android:textSize="@dimen/sp_24"
            android:textColor="@color/color_999999"/>
        
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_commonlist"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>

**Comment by donkingliang** [comment]
你好，你说的上面的recyclerview就会被移出屏幕外面，是显示的时候TextView在最顶部，向下滑动才才能看到上面的rv吗？

**Comment by pengjunhong** [comment]
向下滑动才才能看到上面的rv

**Comment by donkingliang** [comment]
你使用的是最新的2.7.0版本吗？

**Comment by pengjunhong** [comment]
用的是2.6.2，但是我后面在上面加个space就可以了
