### ISSUE TITLE
一个奇怪的崩溃

### ISSUE THREAD

**Issue by 643063150** [donkingliang/ConsecutiveScroller#96]
java.lang.AbstractMethodError: abstract method "void com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout$OnScrollChangeListener.onScrollChange(android.view.View, int, int)"

滑动监听一设置就崩溃，在下载下来的代码上设置不会，自己的项目中就会崩溃
` layout.setOnVerticalScrollChangeListener(new ConsecutiveScrollerLayout.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollY, int oldScrollY, int scrollState) {

            }
        });`

一摸一样的写法 ，唯一的不同就是项目中的不是根布局

**Comment by donkingliang** [comment]
是不是使用的版本不一样，你使用的 是最新的版本吗？

**Comment by 643063150** [comment]
是最新版本implementation 'com.github.donkingliang:ConsecutiveScroller:4.0.0-support'  ，不会崩溃的是github刚下载的代码

**Comment by donkingliang** [comment]
你的代码是不是混淆了，导致找不到这个方法

**Comment by 643063150** [comment]
没有做过混淆

**Comment by donkingliang** [comment]
这很奇怪，这个错误是因为找不到方法，一般是因为编译时和运行时的版本不一样引起的。你应该没有在两个地方引入这个吧，你检查一下你在什么地方引入ConsecutiveScroller，在什么地方使用ConsecutiveScroller

**Comment by 643063150** [comment]
检查了一下，引入只有第一个地方又引入，使用的地方目前只有两个，一个没有设置滑动监听，一个就是现在写的设置了滑动监听，难道是studio缓存，今天我的studio布局查一直有问题

**Comment by donkingliang** [comment]
你查看一下你的项目的External Libraries 目录下的第三方包，是不是只有一个ConsecutiveScroller，版本号对不对？

**Comment by donkingliang** [comment]
再重启一下studio，重新构建一下，看行不行

**Comment by 643063150** [comment]
第三方应该是没有的 ，我让同事试了一下 也是崩溃，用gradle语法强制指定唯一版本还是会崩溃

**Comment by 643063150** [comment]
应该是support包的问题，我新建一个非Androidx项目 什么库都没有导入，只导入ConsecutiveScroller设置滑动监听，还是会崩溃

**Comment by 643063150** [comment]
不过应该是我自己项目的兼容问题，新建项目时没事的，不过还是想提个意见，能不能后续加入子view的 view也能吸顶，这样可以实现更多的效果

**Comment by donkingliang** [comment]
子view的view吸顶比较麻烦，因为要操作子view的子view，需要考虑嵌套层级问题。但是我有提供scrollToChildWithOffset方法设置滑动到子view距离顶部的偏移量。只有自己计算好子view的子vie到子view的顶部距离，就可以实现这种效果。
