### ISSUE TITLE
ViewPager嵌套Fragment 高度问题

### ISSUE THREAD

**Issue by z876335662** [donkingliang/ConsecutiveScroller#98]
按照你的demo 。Fragment 布局如何显示按view实际高度展示？这个第二个TAB改成只有两条数据 但是下滑还是会撑满一屏
![微信图片_20200711165807](https://user-images.githubusercontent.com/6060307/87220638-43504200-c398-11ea-947f-2b46b764355e.png)

**Comment by donkingliang** [comment]
不能。ViewPager是不能wrap_content的，所以就算里面的内容不满一屏，它也会占满一屏的
