### ISSUE TITLE
嵌套webview的时候，在起点网站的阅读页，章节目录无法滑动章节

### ISSUE THREAD

**Issue by SJJ-dot** [donkingliang/ConsecutiveScroller#99]

**Comment by donkingliang** [comment]
ConsecutiveScrollerLayout会拦截子view的滑动事件，如果你的滑动区域时webview里的局部区域，而不是整个webview，那么你需要给webview设置app:layout_isConsecutive="false"

**Comment by SJJ-dot** [comment]
> ConsecutiveScrollerLayout会拦截子view的滑动事件，如果你的滑动区域时webview里的局部区域，而不是整个webview，那么你需要给webview设置app:layout_isConsecutive="false"

但是这样就滚不动了……

**Comment by donkingliang** [comment]
是的，子view的滑动事件要么是由ConsecutiveScrollerLayout拦截处理的，要么是自己处理的。如果不设置layout_isConsecutive="false"就是ConsecutiveScrollerLayout拦截处理，这样webview内部的滑动区域就不能自己滑动；如果是webview自己处理滑动事件，就需要自己处理滑动冲突了，当webview滑动到边界时把滑动事件交给父布局。
